/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conexiondb;

import Metodos.metodos;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author Monkeyelgrande
 */
public class Backup extends javax.swing.JDialog {

    /**
     * Creates new form Backup
     */
    public Backup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        metodos.addEscapeListenerWindowDialog(this);
        this.setLocationRelativeTo(parent);
        lbl_mensaje.setVisible(false);
        cargar_ruta();
    }

    public void cargar_ruta() {
        ResultSet rs = DB_consultas_R_D.getTabla("select ruta_backup from configuraciones where id=1");
        try {
            while (rs.next()) {
                txt_ruta.setText(rs.getString("ruta_backup"));
            }
            rs.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_backup = new javax.swing.JButton();
        lbl_mensaje = new javax.swing.JLabel();
        lbl_mensaje1 = new javax.swing.JLabel();
        txt_ruta = new javax.swing.JTextField();
        btn_ruta = new javax.swing.JButton();
        btn_ruta1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btn_backup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_backup.setText("Backup");
        btn_backup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backupActionPerformed(evt);
            }
        });

        lbl_mensaje.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_mensaje.setForeground(new java.awt.Color(255, 255, 255));
        lbl_mensaje.setText("perfecto");

        lbl_mensaje1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_mensaje1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_mensaje1.setText("Ruta de almacenamiento de datos:");

        txt_ruta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btn_ruta.setText("... Cambiar Ruta");
        btn_ruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rutaActionPerformed(evt);
            }
        });

        btn_ruta1.setText("... Actualizar Ruta");
        btn_ruta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ruta1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_mensaje1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lbl_mensaje))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ruta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ruta1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(btn_backup)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_mensaje1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ruta)
                    .addComponent(btn_ruta1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_backup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_mensaje)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String executeCommand(String ruta, String databaseName, String databasePassword, String type) {

        File backupFilePath = new File(ruta);

        if (!backupFilePath.exists()) {
            JOptionPane.showMessageDialog(this, "La ruta espesificada no es valida\nVerifique que sea correcta");
            return "Error, con la ruta de almacenamiento";
        } else {

            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            String backupFileName = databaseName + "_" + sdf.format(new Date()) + ".sql";

            List<String> commands = getPgComands(databaseName, backupFilePath, backupFileName, type);
            if (!commands.isEmpty()) {
                try {
                    ProcessBuilder pb = new ProcessBuilder(commands);
                    pb.environment().put("PGPASSWORD", databasePassword);

                    Process process = pb.start();

                    try (BufferedReader buf = new BufferedReader(
                            new InputStreamReader(process.getErrorStream()))) {
                        String line = buf.readLine();
                        while (line != null) {
                            System.err.println(line);
                            line = buf.readLine();
                        }
                    }

                    process.waitFor();
                    process.destroy();

                    System.out.println("===> Success on " + type + " process.");
                } catch (IOException | InterruptedException ex) {
                    System.out.println("Exception: " + ex);
                }
            } else {
                System.out.println("Error: Invalid params.");
            }
            return "¡Perfecto! Base de datos guardada en: " + ruta;

        }
    }

    private List<String> getPgComands(String databaseName, File backupFilePath, String backupFileName, String type) {

        ArrayList<String> commands = new ArrayList<>();
        switch (type) {
            case "backup":
                commands.add("C:\\Program Files\\PostgreSQL\\9.4\\bin\\pg_dump");
                commands.add("-h"); //database server host
                commands.add("localhost");
                commands.add("-p"); //database server port number
                commands.add("5432");
                commands.add("-U"); //connect as specified database user
                commands.add("postgres");
                commands.add("-F"); //output file format (custom, directory, tar, plain text (default))
                commands.add("c");
                commands.add("-b"); //include large objects in dump
                commands.add("-v"); //verbose mode
                commands.add("-f"); //output file or directory name
                commands.add(backupFilePath.getAbsolutePath() + File.separator + backupFileName);
                commands.add("-d"); //database name
                commands.add(databaseName);
                break;
            case "restore":
                commands.add("C:\\Program Files\\PostgreSQL\\9.4\\bin\\pg_restore");
                commands.add("-h");
                commands.add("localhost");
                commands.add("-p");
                commands.add("5432");
                commands.add("-U");
                commands.add("postgres");
                commands.add("-d");
                commands.add(databaseName);
                commands.add("-v");
                commands.add(backupFilePath.getAbsolutePath() + File.separator + backupFileName);
                break;
            default:
                return Collections.EMPTY_LIST;
        }
        return commands;
    }
    File ruta;
    static String base;

    public static void consulta_database_name(String archivo) throws FileNotFoundException, IOException {
        String cadena;
        FileReader f = new FileReader(archivo);
        BufferedReader b = new BufferedReader(f);
        while ((cadena = b.readLine()) != null) {
//            System.out.println(cadena);
            base = cadena;
        }
        b.close();
    }

    private void btn_backupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backupActionPerformed

        try {
            consulta_database_name(new File("").getAbsolutePath() + "/src/database_name.txt");
        } catch (IOException ex) {

        }

        lbl_mensaje.setText(executeCommand(txt_ruta.getText(), base, "monkey", "backup"));
        lbl_mensaje.setVisible(true);
    }//GEN-LAST:event_btn_backupActionPerformed

    private void btn_rutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rutaActionPerformed
        JFileChooser explorador = new JFileChooser("\\desktop\\");
        explorador.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        explorador.setDialogTitle("Guardar base de de datos...");
        explorador.setFileFilter(new FileNameExtensionFilter("SQL", "sql"));
        int seleccion = explorador.showDialog(null, "Guardar!");
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");

        //analizamos la respuesta
        switch (seleccion) {
            case JFileChooser.APPROVE_OPTION:

                ruta = explorador.getSelectedFile();
                System.out.println("ruta: " + ruta);
                txt_ruta.setText(ruta + "");
                DBconfiguraciones dbc = new DBconfiguraciones();
                dbc.Actualizar_Ruta(ruta + "");
                break;

            case JFileChooser.CANCEL_OPTION:
                //dio click en cancelar o cerro la ventana
                break;

            case JFileChooser.ERROR_OPTION:
                System.out.println("llega aqui si sucede un error");
                break;

        }
    }//GEN-LAST:event_btn_rutaActionPerformed

    private void btn_ruta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ruta1ActionPerformed

        String manual_ruta = txt_ruta.getText();

        DBconfiguraciones dbc = new DBconfiguraciones();
        dbc.Actualizar_Ruta(manual_ruta + "");
    }//GEN-LAST:event_btn_ruta1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Backup dialog = new Backup(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_backup;
    private javax.swing.JButton btn_ruta;
    private javax.swing.JButton btn_ruta1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_mensaje;
    private javax.swing.JLabel lbl_mensaje1;
    private javax.swing.JTextField txt_ruta;
    // End of variables declaration//GEN-END:variables
}
