/*
 * Modulo Caja: dialogo para marcar como pagado un ingreso/egreso pendiente.
 * Rediseno: solo elige el fondo y actualiza id_fondo en la fila (sin abonos).
 */
package Caja;

import Metodos.metodos;
import modelos.Egresos;
import modelos.Fondos;
import modelos.Ingresos;

/**
 *
 * @author Monkeyelgrande
 */
public class jd_actualizar_pago extends javax.swing.JDialog {

    /**
     * Creates new form facturas
     */
    public static String id_cabecera, fecha, abono, formulario;

    public jd_actualizar_pago(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        metodos.addEscapeListenerWindowDialog(this);
        this.setLocationRelativeTo(parent);
        Fondos.mostrarFondos(jbox_Fondos);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbox_Fondos = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        btn_actualizar_pago = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jbox_Fondos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbox_Fondos.setForeground(new java.awt.Color(51, 51, 51));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Actualizar pago");

        btn_actualizar_pago.setBackground(new java.awt.Color(0, 102, 204));
        btn_actualizar_pago.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_actualizar_pago.setForeground(new java.awt.Color(255, 255, 255));
        btn_actualizar_pago.setText("Actualizar Pago");
        btn_actualizar_pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizar_pagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_actualizar_pago, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(jbox_Fondos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbox_Fondos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_actualizar_pago)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_actualizar_pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizar_pagoActionPerformed
        // fondo
        int Id_fondo = 1;
        try {
            Id_fondo = (jbox_Fondos.getItemAt(jbox_Fondos.getSelectedIndex()).getId());
        } catch (Exception e) {
            Id_fondo = (Fondos.TraerPredeterminado());
        }

        // Rediseno: el pago se registra asignando el fondo directo sobre la fila.
        switch (formulario) {
            case "ingreso":
                Ingresos.actualizar_estado(id_cabecera, Id_fondo + "");
                frm_ingresos.btn_actualizar.doClick();
                break;
            case "egreso":
                Egresos.actualizar_estado(id_cabecera, Id_fondo + "");
                frm_egresos.btn_actualizar.doClick();
                break;

        }

        this.dispose();
    }//GEN-LAST:event_btn_actualizar_pagoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar_pago;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<modelos.Fondos> jbox_Fondos;
    // End of variables declaration//GEN-END:variables
}
