/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Caja;

import Metodos.metodos;
import conexiondb.DB_consultas_R_D;
import java.io.File;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Monkeyelgrande
 */
public class jd_comparar_ingresos extends javax.swing.JDialog {

    /**
     * Creates new form jd_Ventas_diarias
     */
    DefaultTableModel modelIngresos = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false; //Con esto conseguimos que la tabla no se pueda editar
        }
    };
    DefaultTableModel model_WO = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false; //Con esto conseguimos que la tabla no se pueda editar
        }
    };
    DefaultTableModel modelAnalisis = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false; //Con esto conseguimos que la tabla no se pueda editar
        }
    };

    /** Caja cuyos ingresos se concilian: 1 = Caja, 2 = Caja Dos. */
    private final int idCaja;

    public jd_comparar_ingresos(java.awt.Frame parent, boolean modal, int idCaja) {
        super(parent, modal);
        this.idCaja = idCaja;
        initComponents();
        if (idCaja == 2) {
            jLabel13.setText("Comparativo Ingresos Entre Fechas - Caja Dos");
        }
        poner_fechas();
        LimpiarModelos();
    }

    public void poner_fechas() {
        try {
            String fecha1 = DB_consultas_R_D.obtener_fecha_dia1();
            Date date1 = new SimpleDateFormat("yyyy-MM-dd").parse(fecha1);
            jdate_fecha1.setDate(date1);

            String fecha2 = DB_consultas_R_D.obtener_fecha_dia_ultimo();
            Date date2 = new SimpleDateFormat("yyyy-MM-dd").parse(fecha2);
            jdate_fecha2.setDate(date2);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpop_1 = new javax.swing.JPopupMenu();
        jmenu_VerFactura1 = new javax.swing.JMenuItem();
        jpop_2 = new javax.swing.JPopupMenu();
        jmenu_2 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jpnl_tabla = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtabla_izquierda = new org.jdesktop.swingx.JXTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtabla_costos = new org.jdesktop.swingx.JXTable();
        btn_importar_ventas1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jdate_fecha1 = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jdate_fecha2 = new com.toedter.calendar.JDateChooser();
        btn_consultar = new javax.swing.JButton();
        btn_hoy = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtabla_Analisis = new org.jdesktop.swingx.JXTable();
        btn_analizar = new javax.swing.JButton();

        jmenu_VerFactura1.setText("Ver factura");
        jpop_1.add(jmenu_VerFactura1);

        jmenu_2.setText("jMenuItem1");
        jpop_2.add(jmenu_2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ANALISIS");

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setPreferredSize(new java.awt.Dimension(146, 80));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Comparativo Ingresos Entre Fechas");

        jButton2.setBackground(new java.awt.Color(102, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setMnemonic('w');
        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jButton2))
                .addGap(27, 27, 27))
        );

        jpnl_tabla.setBackground(new java.awt.Color(33, 33, 33));

        jtabla_izquierda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtabla_izquierda.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jtabla_izquierda.setRowHeight(20);
        jtabla_izquierda.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jScrollPane2.setViewportView(jtabla_izquierda);

        jtabla_costos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtabla_costos.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jtabla_costos.setRowHeight(20);
        jtabla_costos.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jScrollPane3.setViewportView(jtabla_costos);

        btn_importar_ventas1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_importar_ventas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Office_2.png"))); // NOI18N
        btn_importar_ventas1.setMnemonic('n');
        btn_importar_ventas1.setText("Impotar Libro Auxiliar WO");
        btn_importar_ventas1.setBorder(null);
        btn_importar_ventas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_importar_ventas1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Fecha inicio:");

        jdate_fecha1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Fecha fin:");

        jdate_fecha2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btn_consultar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bucar.png"))); // NOI18N
        btn_consultar.setMnemonic('r');
        btn_consultar.setText("Consulta");
        btn_consultar.setToolTipText("ATL+R");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        btn_hoy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_hoy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bucar.png"))); // NOI18N
        btn_hoy.setMnemonic('r');
        btn_hoy.setText("Hoy");
        btn_hoy.setToolTipText("ATL+R");
        btn_hoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hoyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnl_tablaLayout = new javax.swing.GroupLayout(jpnl_tabla);
        jpnl_tabla.setLayout(jpnl_tablaLayout);
        jpnl_tablaLayout.setHorizontalGroup(
            jpnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl_tablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnl_tablaLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdate_fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdate_fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_consultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hoy))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jpnl_tablaLayout.createSequentialGroup()
                        .addComponent(btn_importar_ventas1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 562, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpnl_tablaLayout.setVerticalGroup(
            jpnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl_tablaLayout.createSequentialGroup()
                .addGroup(jpnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnl_tablaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jpnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addGroup(jpnl_tablaLayout.createSequentialGroup()
                                .addGroup(jpnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_importar_ventas1)
                                    .addComponent(btn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_hoy, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnl_tablaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jdate_fecha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnl_tablaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jdate_fecha2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtabla_Analisis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtabla_Analisis.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jtabla_Analisis.setRowHeight(20);
        jtabla_Analisis.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jScrollPane4.setViewportView(jtabla_Analisis);

        btn_analizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_analizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Analyze.png"))); // NOI18N
        btn_analizar.setMnemonic('r');
        btn_analizar.setText("Analizar");
        btn_analizar.setToolTipText("ATL+R");
        btn_analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_analizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_analizar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_analizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1602, Short.MAX_VALUE)
            .addComponent(jpnl_tabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnl_tabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_importar_ventas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_importar_ventas1ActionPerformed
        try {
            for (int i = 0; i < model_WO.getRowCount(); i++) {
                model_WO.removeRow(i);
                i -= 1;
            }
        } catch (Exception e) {
        }

// Configuramos el modelo (mismos nombres de variables)
        model_WO.setColumnIdentifiers(new Object[]{"Fecha", "Doc Num", "Débitos"});
        model_WO.setRowCount(0); // limpiar por si ya tenía datos

        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos CSV", "csv");
        fileChooser.setFileFilter(filtro);

        int estado = fileChooser.showOpenDialog(this);
        if (estado == JFileChooser.APPROVE_OPTION) {
            File csvFile = fileChooser.getSelectedFile();

            try {
                // Leer todas las líneas del archivo en memoria
                java.util.List<String> lineas = java.nio.file.Files.readAllLines(csvFile.toPath());

                // Recorrer desde la línea 6 (índice 5) hasta la antepenúltima (length - 3)
                for (int i = 5; i < lineas.size() - 3; i++) {
                    String line = lineas.get(i);

                    // Separar por ';'
                    String[] parts = line.split(";", -1);

                    // Validar que existan al menos 7 columnas
                    if (parts.length < 7) {
                        continue;
                    }

                    // Extraer columnas solicitadas
                    String fecha = parts[2].trim(); // 3ra columna
                    String docNum = parts[5].trim(); // 6ta columna
                    String debStr = parts[6].trim(); // 7ma columna

                    // Normalizar y convertir Débitos a número
                    String debitosNormalizado = metodos.ReemplazarCaracteres(
                            metodos.EliminaCaracteres(debStr, "."),
                            ",", "."
                    );

                    double debitos = 0.0;
                    try {
                        debitos = debitosNormalizado.isEmpty() ? 0.0 : Double.parseDouble(debitosNormalizado);
                    } catch (NumberFormatException nfe) {
                        continue; // si no se puede convertir, se omite
                    }

                    // Omitir filas con débitos == 0
                    if (Math.abs(debitos) < 1e-9) {
                        continue;
                    }

                    // Agregar fila al modelo
                    model_WO.addRow(new Object[]{
                        fecha,
                        docNum,
                        metodos.formateador_dinero().format(debitos)
                    });
                }

                // Asignar el modelo a la JTable
                jtabla_costos.setModel(model_WO);

            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(
                        this,
                        "Error al leer el CSV: " + ex.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }


    }//GEN-LAST:event_btn_importar_ventas1ActionPerformed

    private void btn_analizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_analizarActionPerformed
        // --- Dentro del actionPerformed del botón "Analizar" ---

// Configurar modelo para la tabla de análisis
        modelAnalisis.setColumnIdentifiers(new Object[]{"Valor", "# en Izquierda", "# en Derecha", "Estado"});

        jtabla_Analisis.setModel(modelAnalisis);

// Índice de la columna a comparar (3ra columna = índice 2)
        final int COL_IZQ = 2;
        final int COL_DER = 2;

// Mapas de frecuencias (considera duplicados)
// Clave: valor redondeado a 2 decimales; Valor: cantidad de apariciones
        java.util.Map<Double, Integer> freqIzq = new java.util.HashMap<>();
        java.util.Map<Double, Integer> freqDer = new java.util.HashMap<>();

// Pequeña función para normalizar y parsear
        java.util.function.Function<Object, Double> parseMonto = (obj) -> {
            if (obj == null) {
                return 0.0;
            }
            String s = obj.toString().trim();
            if (s.isEmpty()) {
                return 0.0;
            }
            // mismo criterio que usas: quitar puntos, cambiar coma por punto
            String norm = metodos.ReemplazarCaracteres(
                    metodos.EliminaCaracteres(s, "."), ",", ".");
            try {
                double v = Double.parseDouble(norm);
                // Redondear a 2 decimales para comparar con estabilidad
                return Math.round(v * 100.0) / 100.0;
            } catch (NumberFormatException e) {
                return Double.NaN; // inválido
            }
        };

// ---- Recoger valores de la tabla izquierda ----
        for (int r = 0; r < jtabla_izquierda.getRowCount(); r++) {
            Object val = jtabla_izquierda.getValueAt(r, COL_IZQ);
            double monto = parseMonto.apply(val);
            if (Double.isNaN(monto)) {
                continue;
            }
            freqIzq.merge(monto, 1, Integer::sum);
        }

// ---- Recoger valores de la tabla derecha (jtabla_costos) ----
        for (int r = 0; r < jtabla_costos.getRowCount(); r++) {
            Object val = jtabla_costos.getValueAt(r, COL_DER);
            double monto = parseMonto.apply(val);
            if (Double.isNaN(monto)) {
                continue;
            }
            freqDer.merge(monto, 1, Integer::sum);
        }

// ---- Unir claves para comparar ambos lados ----
        java.util.Set<Double> allKeys = new java.util.TreeSet<>();
        allKeys.addAll(freqIzq.keySet());
        allKeys.addAll(freqDer.keySet());

// Totales para resumen
        int totalCountIzq = 0, totalCountDer = 0;
        double totalSumIzq = 0.0, totalSumDer = 0.0;

// Rellenar la tabla de análisis
        for (Double key : allKeys) {
            int cIzq = freqIzq.getOrDefault(key, 0);
            int cDer = freqDer.getOrDefault(key, 0);

            if (cIzq == 0 && cDer == 0) {
                continue; // no debería pasar
            }
            String estado;
            if (cIzq == cDer) {
                estado = "OK";
            } else if (cIzq > cDer) {
                estado = "Faltan en Derecha";
            } else {
                estado = "Sobran en Derecha";
            }

            modelAnalisis.addRow(new Object[]{
                metodos.formateador_dinero().format(key),
                cIzq,
                cDer,
                estado
            });

            // Totales
            totalCountIzq += cIzq;
            totalCountDer += cDer;
            totalSumIzq += key * cIzq;
            totalSumDer += key * cDer;
        }

// ---- Fila de resumen ----
        modelAnalisis.addRow(new Object[]{
            "— RESUMEN —",
            String.format("%d (Σ %s)", totalCountIzq, metodos.formateador_dinero().format(totalSumIzq)),
            String.format("%d (Σ %s)", totalCountDer, metodos.formateador_dinero().format(totalSumDer)),
            (Math.abs(totalSumIzq - totalSumDer) < 0.01 && totalCountIzq == totalCountDer) ? "CUADRA" : "NO CUADRA"
        });

    }//GEN-LAST:event_btn_analizarActionPerformed

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed

        try {
            for (int i = 0; i < modelIngresos.getRowCount(); i++) {
                modelIngresos.removeRow(i);
                i -= 1;
            }
        } catch (Exception e) {
        }

        String fecha1 = "", fecha2 = "";
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat sdf2 = new SimpleDateFormat("dd-MM-yyyy");
        fecha1 = sdf.format(jdate_fecha1.getDate());
        fecha2 = sdf.format(jdate_fecha2.getDate());

        String consulta = "select i.fecha, i.hora, i.total, i.descripcion from ingresos i where i.id_caja=" + idCaja + " and fecha between  '" + fecha1 + "' and '" + fecha2 + "' \n"
                + "\n"
                + "order by i.total";

        System.out.println(consulta);

        ResultSet rs = DB_consultas_R_D.getTabla(consulta);

        modelIngresos.setColumnIdentifiers(new Object[]{"Fecha", "Hora", "Total", "Descripcion"});
        try {
            while (rs.next()) {
                // añade los resultado a al modelo de tabla
                modelIngresos.addRow(new Object[]{sdf2.format(rs.getDate("fecha")), rs.getString("hora"), metodos.formateador_dinero().format(rs.getDouble("total")), rs.getString("descripcion")});
            }
            rs.close();
            // asigna el modelo a la tabla
            jtabla_izquierda.setModel(modelIngresos);

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void btn_hoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hoyActionPerformed
        jdate_fecha1.setDate(new java.util.Date());
        jdate_fecha2.setDate(new java.util.Date());
        btn_consultar.doClick();
    }//GEN-LAST:event_btn_hoyActionPerformed
    public void LimpiarModelos() {
        try {
            for (int i = 0; i < modelAnalisis.getRowCount(); i++) {
                modelAnalisis.removeRow(i);
                i -= 1;
            }
        } catch (Exception e) {
        }
        try {
            for (int i = 0; i < modelIngresos.getRowCount(); i++) {
                modelIngresos.removeRow(i);
                i -= 1;
            }
        } catch (Exception e) {
        }
        try {
            for (int i = 0; i < model_WO.getRowCount(); i++) {
                model_WO.removeRow(i);
                i -= 1;
            }
        } catch (Exception e) {
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_analizar;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_hoy;
    private javax.swing.JButton btn_importar_ventas1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private com.toedter.calendar.JDateChooser jdate_fecha1;
    private com.toedter.calendar.JDateChooser jdate_fecha2;
    private javax.swing.JMenuItem jmenu_2;
    private javax.swing.JMenuItem jmenu_VerFactura1;
    private javax.swing.JPanel jpnl_tabla;
    private javax.swing.JPopupMenu jpop_1;
    private javax.swing.JPopupMenu jpop_2;
    private org.jdesktop.swingx.JXTable jtabla_Analisis;
    private org.jdesktop.swingx.JXTable jtabla_costos;
    private org.jdesktop.swingx.JXTable jtabla_izquierda;
    // End of variables declaration//GEN-END:variables
}
