/*
 * Modulo Caja: visualizador de detalle de un ingreso o egreso.
 * Portado de cajadiaria; el formulario que lo abre llena sus componentes.
 */
package Caja;

import Metodos.metodos;
import conexiondb.DB_consultas_R_D;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Monkeyelgrande
 */
public class jd_ver_in_egre extends javax.swing.JDialog {

    /**
     * Creates new form jif_crear_ingreso_mecancia
     */
    public static DefaultTableModel modelo_fotos = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false; //Con esto conseguimos que la tabla no se pueda editar
        }
    };
    public String ruta_foto = "";

    public jd_ver_in_egre() {
        initComponents();
        this.setLocationRelativeTo(this);
        jtxa_descripcion.setWrapStyleWord(true);
        metodos.addEscapeListenerWindowDialog(this);
        lbl_cuenta_nombre.setVisible(false);
        lbl_cuenta_titulo.setVisible(false);
        jtabla_fotos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(MouseEvent me) {
                if (me.getClickCount() == 1) {
                    int fila = jtabla_fotos.getSelectedRow();

                    String ruta = (String) jtabla_fotos.getValueAt(fila, 0);
                    foto_a_label(ruta, lbl_foto_1);

                    ruta_foto = ruta;
                }
            }
        });

        jtabla_fotos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(MouseEvent me) {
                if (me.getClickCount() == 2) {
                    int fila = jtabla_fotos.getSelectedRow();

                    String ruta = (String) jtabla_fotos.getValueAt(fila, 0);
                    try {
                        DB_consultas_R_D.Abrir_Archivo(ruta);
                    } catch (Exception e) {
                        System.out.println(e);
                    }
                }
            }
        });
    }

    // La metodos de bodega no trae foto_a_label: copia local del helper de cajadiaria.
    public static void foto_a_label(String ruta, final JLabel lbl_foto) {
        try {

            Image img = new ImageIcon(ruta).getImage();

            int originalWidth = img.getWidth(null);
            int originalHeight = img.getHeight(null);

            double scaleFactor = Math.min(1.0 * lbl_foto.getWidth() / originalWidth, 1.0 * lbl_foto.getHeight() / originalHeight);

            int scaledWidth = (int) (originalWidth * scaleFactor);
            int scaledHeight = (int) (originalHeight * scaleFactor);

            final Image newimg = img.getScaledInstance(scaledWidth, scaledHeight, Image.SCALE_DEFAULT);

            ImageIcon newicon = new ImageIcon(newimg) {
                @Override
                public synchronized void paintIcon(Component c, Graphics g, int x, int y) {
                    int offsetX = (lbl_foto.getWidth() - getIconWidth()) / 2;
                    int offsetY = (lbl_foto.getHeight() - getIconHeight()) / 2;

                    g.drawImage(newimg, x + offsetX, y + offsetY, c);
                }
            };

            lbl_foto.setIcon(newicon);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_ingreso = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxa_descripcion = new javax.swing.JTextArea();
        lbl_fecha = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lbl_hora = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        lbl_cuenta_titulo = new javax.swing.JLabel();
        lbl_cuenta_nombre = new javax.swing.JLabel();
        lbl_foto_1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtabla_fotos = new javax.swing.JTable();

        setTitle("Visualizador");
        setModal(true);
        setResizable(false);

        pnl_ingreso.setBackground(new java.awt.Color(1, 50, 67));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Total");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Fecha");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Detalles:");

        jtxa_descripcion.setEditable(false);
        jtxa_descripcion.setColumns(20);
        jtxa_descripcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxa_descripcion.setLineWrap(true);
        jtxa_descripcion.setRows(5);
        jScrollPane3.setViewportView(jtxa_descripcion);

        lbl_fecha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_fecha.setForeground(new java.awt.Color(102, 255, 204));
        lbl_fecha.setText("Fecha");

        lbl_total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_total.setForeground(new java.awt.Color(102, 255, 204));
        lbl_total.setText("Cantidad");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Hora");

        lbl_hora.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_hora.setForeground(new java.awt.Color(255, 0, 51));
        lbl_hora.setText("Hora");

        javax.swing.GroupLayout pnl_ingresoLayout = new javax.swing.GroupLayout(pnl_ingreso);
        pnl_ingreso.setLayout(pnl_ingresoLayout);
        pnl_ingresoLayout.setHorizontalGroup(
            pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ingresoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(pnl_ingresoLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_total)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ingresoLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_hora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_fecha)))
                .addContainerGap())
        );
        pnl_ingresoLayout.setVerticalGroup(
            pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ingresoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(lbl_total))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Usuario");

        lbl_user.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_user.setText("User");

        lbl_cuenta_titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_cuenta_titulo.setText("Cuenta");

        lbl_cuenta_nombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_cuenta_nombre.setText("cuenta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_cuenta_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_cuenta_nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_user)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_cuenta_titulo)
                        .addComponent(lbl_cuenta_nombre))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(lbl_user)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_foto_1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_foto_1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbl_foto_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_foto_1MouseClicked(evt);
            }
        });

        jtabla_fotos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtabla_fotos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtabla_fotos.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jtabla_fotos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_ingreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_foto_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_foto_1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_foto_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_foto_1MouseClicked
        try {
            DB_consultas_R_D.Abrir_Archivo(ruta_foto);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lbl_foto_1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTable jtabla_fotos;
    public static javax.swing.JTextArea jtxa_descripcion;
    public static javax.swing.JLabel lbl_cuenta_nombre;
    public static javax.swing.JLabel lbl_cuenta_titulo;
    public static javax.swing.JLabel lbl_fecha;
    public static javax.swing.JLabel lbl_foto_1;
    public static javax.swing.JLabel lbl_hora;
    public static javax.swing.JLabel lbl_total;
    public static javax.swing.JLabel lbl_user;
    public static javax.swing.JPanel pnl_ingreso;
    // End of variables declaration//GEN-END:variables

}
