/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Caja;

import Metodos.metodos;
import conexiondb.DB_Fondos;
import conexiondb.DB_consultas_R_D;
import javax.swing.JOptionPane;
import modelos.Fondos;

/**
 *
 * @author Monkeyelgrande
 */
public class jif_crear_fondo extends javax.swing.JDialog {

    /**
     * Creates new form jif_crear_cuenta
     */
    public jif_crear_fondo() {
        initComponents();
        // El id lo asigna la BD (serial); vacio = registro nuevo
        txt_id.setText("");
        this.setLocationRelativeTo(this);
        btn_editar.setVisible(false);
        metodos.addEscapeListenerWindowDialog(this);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        txt_id = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btn_limpiar = new javax.swing.JButton();
        chk_cerrar = new javax.swing.JCheckBox();
        btn_editar = new javax.swing.JButton();
        chk_predeterminado = new javax.swing.JCheckBox();
        rbtn_fisico = new javax.swing.JRadioButton();
        rbtn_digital = new javax.swing.JRadioButton();

        setModal(true);

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nombre");

        txt_nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_guardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btn_guardar.setMnemonic('g');
        btn_guardar.setText("Guardar");
        btn_guardar.setBorder(null);
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        txt_id.setEditable(false);
        txt_id.setBackground(new java.awt.Color(204, 204, 204));
        txt_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("ID");

        btn_limpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        btn_limpiar.setMnemonic('l');
        btn_limpiar.setText("Limpiar");
        btn_limpiar.setBorder(null);
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        chk_cerrar.setSelected(true);
        chk_cerrar.setText("Cerrar formulario al guardar");

        btn_editar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        chk_predeterminado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chk_predeterminado.setText("Predeterminado");

        buttonGroup1.add(rbtn_fisico);
        rbtn_fisico.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        rbtn_fisico.setSelected(true);
        rbtn_fisico.setText("Fisico");

        buttonGroup1.add(rbtn_digital);
        rbtn_digital.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        rbtn_digital.setText("Digital");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbtn_fisico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtn_digital))
                    .addComponent(chk_cerrar)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_editar)))
                    .addComponent(chk_predeterminado))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_editar))
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(chk_predeterminado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_fisico)
                    .addComponent(rbtn_digital))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_guardar)
                    .addComponent(btn_limpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chk_cerrar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        if (txt_nombre.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese un nombre para la cuenta");
        } else {

            DB_Fondos dbcuenta = new DB_Fondos();

            Fondos obj = new Fondos();

            try {
                obj.setId(Integer.parseInt(txt_id.getText()));
            } catch (Exception e) {
            }
            obj.setNombre(txt_nombre.getText());
            // Convencion heredada de cajadiaria: fisico_digital 0 = fisico
            // (efectivo), 1 = digital (banco). Los reportes consultan asi.
            if (rbtn_fisico.isSelected()) {
                obj.setFisico_digital(0);
            } else {
                obj.setFisico_digital(1);
            }
            obj.setPredeterminado(0);
            if (chk_predeterminado.isSelected()) {
                obj.setPredeterminado(1);
            }

            if (!txt_id.getText().equals("") && DB_consultas_R_D.consultarId(txt_id.getText(), "fondos") == 1) {
                dbcuenta.Actualizar(obj);
            } else {
                dbcuenta.Guardar(obj);
            }
            limpiar();
            txt_id.setText("");
            if (chk_cerrar.isSelected()) {
                this.dispose();
            }
            frm_fondos.btn_actualizar.doClick();
        }

    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        txt_nombre.setEnabled(true);
        btn_guardar.setEnabled(true);
        btn_limpiar.setEnabled(true);
        chk_cerrar.setEnabled(true);
    }//GEN-LAST:event_btn_editarActionPerformed
    public void limpiar() {
        txt_nombre.setText("");
        txt_nombre.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_editar;
    public static javax.swing.JButton btn_guardar;
    public static javax.swing.JButton btn_limpiar;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JCheckBox chk_cerrar;
    public static javax.swing.JCheckBox chk_predeterminado;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JRadioButton rbtn_digital;
    public static javax.swing.JRadioButton rbtn_fisico;
    public static javax.swing.JTextField txt_id;
    public static javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
