/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios_internos;

import Formularios.frm_Recortes;
import Formularios.frm_main;
import Metodos.TextPrompt;
import Metodos.metodos;
import conexiondb.DB_Recortes_detalle;
import conexiondb.DB_consultas_R_D;
import conexiondb.DBcontactos;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Contactos;
import modelos.Recortes_detallle;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Monkeyelgrande
 */
public class jd_orden_de_recorte extends javax.swing.JDialog {

    /**
     * Creates new form jd_ver_devolucion
     */
    public static DefaultTableModel modelo_ver_entregas = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false; //Con esto conseguimos que la tabla no se pueda editar
        }
    };

    Calendar fecha = new GregorianCalendar();

    public jd_orden_de_recorte(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        metodos.addEscapeListenerWindowDialog(this);
        lbl_id_orden_recorte.setText(DB_consultas_R_D.cargarId("recortes_detalle"));
        TextPrompt prompt = new TextPrompt("Cantidad", txt_cantidad);
        TextPrompt codigo = new TextPrompt("Código factura", txt_codigo);

        jdate_fecha.setCalendar(fecha);

        Contactos cliente = new Contactos();
        cliente.MostrarNombreContactos(jbox_cliente);

        jbox_cliente.setSelectedItem(cliente.nombreDefectoVentaDiaria());
        lbl_id_cliente.setText("1");
        if (frm_main.perfil != 1) {
            btn_eliminar.setEnabled(false);
        }

        jtabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(MouseEvent me) {
                if (me.getClickCount() == 2) {

                    int fila = jtabla.getSelectedRow();
                    String id = jtabla.getValueAt(fila, 0).toString();//suponiendo que el id lo muestras en la primera columna
                    String consulta = "select observacion from recortes_detalle where id=" + id;

                    ResultSet rs = DB_consultas_R_D.getTabla(consulta);
                    try {
                        while (rs.next()) {
                            JOptionPane.showMessageDialog(rootPane, rs.getString("observacion"));
                        }
                        rs.close();
                    } catch (Exception e) {
                        System.out.println(e);
                    }
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_eliminar = new javax.swing.JButton();
        txt_cantidad = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        btn_imprimir_media_carta = new javax.swing.JButton();
        jdate_fecha = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_id_cliente = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jbox_cliente = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_observaciones = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbl_descripcion_producto = new javax.swing.JLabel();
        lbl_id_producto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_total_producto = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_total_entregado = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_total_saldo = new javax.swing.JLabel();
        lbl_id_recorte = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        lbl_id_orden_recorte = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Abonos");
        setModal(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_eliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btn_eliminar.setMnemonic('d');
        btn_eliminar.setText("Eliminar Orden");
        btn_eliminar.setBorder(null);
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        btn_eliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_eliminarKeyPressed(evt);
            }
        });

        txt_cantidad.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_cantidad.setForeground(new java.awt.Color(0, 153, 153));
        txt_cantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cantidadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cantidadFocusLost(evt);
            }
        });
        txt_cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cantidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cantidadKeyTyped(evt);
            }
        });

        btn_guardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btn_guardar.setMnemonic('g');
        btn_guardar.setText("Guardar");
        btn_guardar.setBorder(null);
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        btn_guardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_guardarKeyPressed(evt);
            }
        });

        btn_imprimir_media_carta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_imprimir_media_carta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/print_pequeno.png"))); // NOI18N
        btn_imprimir_media_carta.setMnemonic('p');
        btn_imprimir_media_carta.setText("Imprimir");
        btn_imprimir_media_carta.setToolTipText("ATL+P");
        btn_imprimir_media_carta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimir_media_cartaActionPerformed(evt);
            }
        });

        jdate_fecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Fecha");

        lbl_id_cliente.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lbl_id_cliente.setForeground(new java.awt.Color(58, 159, 171));
        lbl_id_cliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_id_cliente.setText("-");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 204, 0));
        jButton1.setMnemonic('k');
        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(58, 159, 171));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nombre");

        jbox_cliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbox_cliente.setMaximumSize(new java.awt.Dimension(500, 400));
        jbox_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbox_clienteMouseClicked(evt);
            }
        });
        jbox_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbox_clienteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(58, 159, 171));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cliente");

        txt_codigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_codigo.setForeground(new java.awt.Color(0, 153, 153));
        txt_codigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_codigoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_codigoFocusLost(evt);
            }
        });
        txt_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_codigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_codigoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbox_cliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addComponent(lbl_id_cliente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_codigo)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lbl_id_cliente, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButton1)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbox_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txt_observaciones.setColumns(20);
        txt_observaciones.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_observaciones.setLineWrap(true);
        txt_observaciones.setRows(5);
        jScrollPane4.setViewportView(txt_observaciones);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_imprimir_media_carta, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jdate_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addComponent(btn_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_cantidad))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdate_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_imprimir_media_carta, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminar))
                .addGap(6, 6, 6))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Producto");

        lbl_descripcion_producto.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_descripcion_producto.setForeground(new java.awt.Color(0, 102, 102));
        lbl_descripcion_producto.setText("p");

        lbl_id_producto.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        lbl_id_producto.setForeground(new java.awt.Color(0, 51, 51));
        lbl_id_producto.setText("ID");

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Total recorte");

        lbl_total_producto.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_total_producto.setForeground(new java.awt.Color(0, 102, 204));
        lbl_total_producto.setText("total");

        jLabel9.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Total entregas");

        lbl_total_entregado.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_total_entregado.setForeground(new java.awt.Color(0, 204, 0));
        lbl_total_entregado.setText("total");

        jLabel10.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Total saldo");

        lbl_total_saldo.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_total_saldo.setForeground(new java.awt.Color(204, 0, 0));
        lbl_total_saldo.setText("total");

        lbl_id_recorte.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        lbl_id_recorte.setForeground(new java.awt.Color(0, 51, 51));
        lbl_id_recorte.setText("ID");

        jLabel8.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Usuario");

        lbl_user.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        lbl_user.setForeground(new java.awt.Color(0, 51, 51));
        lbl_user.setText("user");

        lbl_id_orden_recorte.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        lbl_id_orden_recorte.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        lbl_id_orden_recorte.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_descripcion_producto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_id_producto))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_total_producto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_total_entregado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_total_saldo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_id_recorte, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_id_orden_recorte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_user)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lbl_descripcion_producto)
                            .addComponent(lbl_id_producto))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lbl_total_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(lbl_total_entregado)
                            .addComponent(jLabel10)
                            .addComponent(lbl_total_saldo)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_id_recorte)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lbl_user)
                            .addComponent(lbl_id_orden_recorte))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jtabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cantidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cantidadFocusGained
//        if (!txt_cantidad.getText().equals("")) {
//            String texto = (txt_cantidad.getText());
//            txt_cantidad.setText(texto);
//        }
    }//GEN-LAST:event_txt_cantidadFocusGained

    private void txt_cantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cantidadFocusLost
        if (!txt_cantidad.getText().equals("")) {
            double to = Double.parseDouble(txt_cantidad.getText());
            String nuevo = metodos.formateador_decimal_punto_para_decimal().format(to);
            txt_cantidad.setText(nuevo);
        }
    }//GEN-LAST:event_txt_cantidadFocusLost

    private void txt_cantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantidadKeyPressed
        char num = evt.getKeyChar();
        if ((num == KeyEvent.VK_ENTER)) {
            btn_guardar.requestFocus();
        }
        if ((num == KeyEvent.VK_SPACE)) {
            txt_cantidad.setText(metodos.EliminaCaracteres(lbl_total_saldo.getText(), "."));
        }
    }//GEN-LAST:event_txt_cantidadKeyPressed

    private void txt_cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantidadKeyTyped
        char num = evt.getKeyChar();
        DB_consultas_R_D.validar_numeros(evt, num);
    }//GEN-LAST:event_txt_cantidadKeyTyped

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        if (txt_cantidad.getText().isEmpty()) {
            txt_cantidad.setBackground(Color.pink);
        } else {
            if (validaSaldo()) {
                Recortes_detallle rec = new Recortes_detallle();
                DB_Recortes_detalle db_rec = new DB_Recortes_detalle();
                rec.setId(Integer.parseInt(lbl_id_orden_recorte.getText()));
                rec.setId_cabecera(Integer.parseInt(lbl_id_recorte.getText()));
                rec.setId_user(frm_main.id_user);
                rec.setCantidad(Double.parseDouble(txt_cantidad.getText()));
                rec.setId_contacto(Integer.parseInt(lbl_id_cliente.getText()));
                rec.setObservacion(txt_observaciones.getText());
                int dia, mes, ano;
                ano = jdate_fecha.getCalendar().get(Calendar.YEAR);
                mes = jdate_fecha.getCalendar().get(Calendar.MARCH) + 1;
                dia = jdate_fecha.getCalendar().get(Calendar.DAY_OF_MONTH);
                rec.setFecha(ano + "-" + mes + "-" + dia);
                
                rec.setHora(DB_consultas_R_D.obtener_hora());
                rec.setCodigo(txt_codigo.getText());
                
                rec.setEstado(0);
                if (db_rec.Guardar(rec) > 0) {

                    frm_Recortes.btn_actualizar.doClick();
                    lbl_id_orden_recorte.setText(DB_consultas_R_D.cargarId("recortes_detalle"));
                    txt_observaciones.setText("");

                    String id = "" + rec.getId();//suponiendo que el id lo muestras en la primera columna

                    String cad = new File("").getAbsolutePath() + "/src/reportes/ImprimirRecorte.jrxml";
                    if (!cad.equals("")) {
                        Connection cn = DB_consultas_R_D.getConexion();
                        JasperReport report = null;
                        Map p = new HashMap();
                        p.put("SUBREPORT_DIR", new File("").getAbsolutePath() + "/src/reportes/");
                        p.put("id_factura", Integer.parseInt(id));
                        try {
                            try {
                                report = JasperCompileManager.compileReport(cad);
                            } catch (Exception e) {
                                JOptionPane.showMessageDialog(this, e);
                            }
                            JasperPrint print = JasperFillManager.fillReport(report, p, cn);
                            JasperViewer view = new JasperViewer(print, false);
                            cn.close();
                            JDialog dialog = new JDialog(this);//the owner
                            metodos.addEscapeListenerWindowDialog(dialog);
                            dialog.setContentPane(view.getContentPane());
                            dialog.setSize(view.getSize());
                            dialog.setModal(true);
                            dialog.setLocationRelativeTo(this);
                            dialog.setTitle("Recortes");
                            dialog.setVisible(true);

                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    }

                }

                jd_orden_de_recorte.modelo_ver_entregas.addRow(new Object[]{rec.getId(), lbl_user.getText(),
                    metodos.formateador_decimal_punto_para_decimal().format(rec.getCantidad()),
                    rec.getFecha(), rec.getHora()});

                double cantidad = rec.getCantidad();
                double saldo = Double.parseDouble(lbl_total_saldo.getText());
                double entregado = Double.parseDouble(lbl_total_entregado.getText());
                lbl_total_entregado.setText(metodos.formateador_decimal_punto_para_decimal().format(entregado + cantidad));
                lbl_total_saldo.setText(metodos.formateador_decimal_punto_para_decimal().format(saldo - cantidad));
                lbl_id_orden_recorte.setText(DB_consultas_R_D.cargarId("recortes_detalle"));
                txt_cantidad.setText("");

            }
        }
    }//GEN-LAST:event_btn_guardarActionPerformed
    public boolean validaSaldo() {
        double saldo = Double.parseDouble(metodos.EliminaCaracteres(lbl_total_saldo.getText(), "."));
        double cantidad = Double.parseDouble(txt_cantidad.getText());
        if (cantidad > saldo) {
            JOptionPane.showMessageDialog(this, "La cantidad ingresada supera el saldo de la factura \nVerifique los valores ingresados");
            txt_cantidad.setText("");
            txt_cantidad.requestFocus();
            return false;
        }
        return true;
    }
    private void btn_guardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_guardarKeyPressed
        char num = evt.getKeyChar();
        if ((num == KeyEvent.VK_ENTER)) {
            btn_guardarActionPerformed(null);
        }
    }//GEN-LAST:event_btn_guardarKeyPressed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        int fila = jtabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un registro");
        } else {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Desea eliminar este abono?", "Alerta", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
                try {
                    DefaultTableModel modelo = (DefaultTableModel) jtabla.getModel();
                    String id = (String) modelo.getValueAt(fila, 0);//suponiendo que el id lo muestras en la primera columna
                    double abonoEliminado = Double.parseDouble(Metodos.metodos.EliminaCaracteres("" + modelo.getValueAt(fila, 2), "."));
                    double saldo = Double.parseDouble(Metodos.metodos.EliminaCaracteres(lbl_total_saldo.getText(), "."));
                    double totalAbonos = Double.parseDouble(Metodos.metodos.EliminaCaracteres(lbl_total_entregado.getText(), "."));
                    lbl_total_entregado.setText(metodos.formateador_decimal_punto_para_decimal().format(totalAbonos - abonoEliminado));
                    lbl_total_saldo.setText(metodos.formateador_decimal_punto_para_decimal().format(saldo + abonoEliminado));
                    DB_consultas_R_D.eliminar("recortes_detalle", id);
                    modelo.removeRow(fila);
                    frm_Recortes.btn_actualizar.doClick();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_eliminarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_eliminarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarKeyPressed

    private void btn_imprimir_media_cartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimir_media_cartaActionPerformed
        int fila = jtabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un registro");
        } else {
            String id = jtabla.getValueAt(fila, 0).toString();//suponiendo que el id lo muestras en la primera columna

            String cad = new File("").getAbsolutePath() + "/src/reportes/ImprimirRecorte.jrxml";
            if (!cad.equals("")) {
                Connection cn = DB_consultas_R_D.getConexion();
                JasperReport report = null;
                Map p = new HashMap();
                p.put("SUBREPORT_DIR", new File("").getAbsolutePath() + "/src/reportes/");
                p.put("id_factura", Integer.parseInt(id));
                try {
                    try {
                        report = JasperCompileManager.compileReport(cad);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, e);
                    }
                    JasperPrint print = JasperFillManager.fillReport(report, p, cn);
                    JasperViewer view = new JasperViewer(print, false);
                    cn.close();
                    JDialog dialog = new JDialog(this);//the owner
                    metodos.addEscapeListenerWindowDialog(dialog);
                    dialog.setContentPane(view.getContentPane());
                    dialog.setSize(view.getSize());
                    dialog.setModal(true);
                    dialog.setLocationRelativeTo(this);
                    dialog.setTitle("Recortes");
                    dialog.setVisible(true);

                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }

    }//GEN-LAST:event_btn_imprimir_media_cartaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            String name = JOptionPane.showInputDialog(this, "Ingrese el nombre del nuevo cliente:");
            if (name.equals("")) {
                JOptionPane.showMessageDialog(this, "Por favor ingrese un nombre");
            } else {

                DBcontactos dbclientes = new DBcontactos();
                Contactos contacto = new Contactos();
                String idnuevo = DB_consultas_R_D.TraerIdMaximoNuevoContacto();

                try {
                    contacto.setId(Integer.parseInt(idnuevo));
                } catch (Exception e) {

                }
                contacto.setNombre(name);

                dbclientes.Guardar(contacto);

                DefaultComboBoxModel modeloCombo = (DefaultComboBoxModel) jbox_cliente.getModel();
                modeloCombo.addElement(new Contactos(Integer.parseInt(idnuevo), name));
                jbox_cliente.setModel(modeloCombo);
                jbox_cliente.setSelectedItem(name);

            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbox_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbox_clienteMouseClicked

    }//GEN-LAST:event_jbox_clienteMouseClicked

    private void jbox_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbox_clienteActionPerformed
        lbl_id_cliente.setText(DB_consultas_R_D.TraerIdCliente(jbox_cliente.getSelectedItem().toString()));
    }//GEN-LAST:event_jbox_clienteActionPerformed

    private void txt_codigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_codigoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoFocusGained

    private void txt_codigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_codigoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoFocusLost

    private void txt_codigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoKeyPressed

    private void txt_codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoKeyTyped
    public void limpiar() {
        txt_cantidad.setText("");
        txt_cantidad.setBackground(Color.white);
        txt_cantidad.requestFocus();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jd_orden_de_recorte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jd_orden_de_recorte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jd_orden_de_recorte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jd_orden_de_recorte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jd_orden_de_recorte dialog = new jd_orden_de_recorte(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_eliminar;
    public static javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_imprimir_media_carta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JComboBox<Contactos> jbox_cliente;
    private com.toedter.calendar.JDateChooser jdate_fecha;
    public static javax.swing.JTable jtabla;
    public static javax.swing.JLabel lbl_descripcion_producto;
    public static javax.swing.JLabel lbl_id_cliente;
    private javax.swing.JLabel lbl_id_orden_recorte;
    public static javax.swing.JLabel lbl_id_producto;
    public static javax.swing.JLabel lbl_id_recorte;
    public static javax.swing.JLabel lbl_total_entregado;
    public static javax.swing.JLabel lbl_total_producto;
    public static javax.swing.JLabel lbl_total_saldo;
    public static javax.swing.JLabel lbl_user;
    public static javax.swing.JTextField txt_cantidad;
    public static javax.swing.JTextField txt_codigo;
    private javax.swing.JTextArea txt_observaciones;
    // End of variables declaration//GEN-END:variables
}
