/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios_internos;

import Metodos.metodos;

/**
 *
 * @author Monkeyelgrande
 */
public class jd_ver_in_egre extends javax.swing.JDialog {

    /**
     * Creates new form jif_crear_ingreso_mecancia
     */
    public jd_ver_in_egre() {
        initComponents();
        this.setLocationRelativeTo(this);
        jtxa_descripcion.setWrapStyleWord(true);
        metodos.addEscapeListenerWindowDialog(this);
        lbl_cuenta_nombre.setVisible(false);
        lbl_cuenta_titulo.setVisible(false);
        lbl_caja.setVisible(false);
        jlabelcaja.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_ingreso = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxa_descripcion = new javax.swing.JTextArea();
        lbl_fecha = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lbl_hora = new javax.swing.JLabel();
        jlabelcaja = new javax.swing.JLabel();
        lbl_caja = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_cedula_contacto = new javax.swing.JLabel();
        lbl_nombre_contacto = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        lbl_cuenta_titulo = new javax.swing.JLabel();
        lbl_cuenta_nombre = new javax.swing.JLabel();

        setTitle("Visualizador");
        setModal(true);
        setResizable(false);

        pnl_ingreso.setBackground(new java.awt.Color(1, 50, 67));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Total");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Fecha");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Detalles:");

        jtxa_descripcion.setEditable(false);
        jtxa_descripcion.setColumns(20);
        jtxa_descripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxa_descripcion.setLineWrap(true);
        jtxa_descripcion.setRows(5);
        jScrollPane3.setViewportView(jtxa_descripcion);

        lbl_fecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_fecha.setForeground(new java.awt.Color(102, 255, 204));
        lbl_fecha.setText("Fecha");

        lbl_total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_total.setForeground(new java.awt.Color(102, 255, 204));
        lbl_total.setText("Cantidad");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Hora");

        lbl_hora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_hora.setForeground(new java.awt.Color(102, 255, 204));
        lbl_hora.setText("Hora");

        jlabelcaja.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlabelcaja.setForeground(new java.awt.Color(255, 255, 255));
        jlabelcaja.setText("Caja");

        lbl_caja.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_caja.setForeground(new java.awt.Color(102, 255, 204));
        lbl_caja.setText("caja");

        javax.swing.GroupLayout pnl_ingresoLayout = new javax.swing.GroupLayout(pnl_ingreso);
        pnl_ingreso.setLayout(pnl_ingresoLayout);
        pnl_ingresoLayout.setHorizontalGroup(
            pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ingresoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ingresoLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_hora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_fecha))
                    .addGroup(pnl_ingresoLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_total)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlabelcaja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_caja)))
                .addContainerGap())
        );
        pnl_ingresoLayout.setVerticalGroup(
            pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ingresoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlabelcaja)
                        .addComponent(lbl_caja))
                    .addGroup(pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(lbl_total)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Contacto");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("CC/NIT");

        lbl_cedula_contacto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_cedula_contacto.setText("Descripción");

        lbl_nombre_contacto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_nombre_contacto.setText("contacto");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Usuario");

        lbl_user.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_user.setText("User");

        lbl_cuenta_titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_cuenta_titulo.setText("Cuenta");

        lbl_cuenta_nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_cuenta_nombre.setText("cuenta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_nombre_contacto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_user))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_cedula_contacto)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lbl_cuenta_titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_cuenta_nombre)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_nombre_contacto)
                    .addComponent(jLabel4)
                    .addComponent(lbl_user))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbl_cedula_contacto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cuenta_titulo)
                    .addComponent(lbl_cuenta_nombre))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_ingreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_ingreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JLabel jlabelcaja;
    public static javax.swing.JTextArea jtxa_descripcion;
    public static javax.swing.JLabel lbl_caja;
    public static javax.swing.JLabel lbl_cedula_contacto;
    public static javax.swing.JLabel lbl_cuenta_nombre;
    public static javax.swing.JLabel lbl_cuenta_titulo;
    public static javax.swing.JLabel lbl_fecha;
    public static javax.swing.JLabel lbl_hora;
    public static javax.swing.JLabel lbl_nombre_contacto;
    public static javax.swing.JLabel lbl_total;
    public static javax.swing.JLabel lbl_user;
    public static javax.swing.JPanel pnl_ingreso;
    // End of variables declaration//GEN-END:variables

}
