/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios_internos;

import JDBuscar.*;
import Formularios.frm_contactos;
import Metodos.metodos;
import conexiondb.DB_consultas_R_D;
import static conexiondb.DB_consultas_R_D.getConexion;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelos.Contactos;

/**
 *
 * @author Monkeyelgrande
 */
public class jif_eliminar_contacto extends javax.swing.JDialog {

    /**
     * Creates new form jd_buscar_cliente
     */
    public static String id_cliente;

    public jif_eliminar_contacto(java.awt.Frame parent, boolean modal, String id_cliente) {
        super(parent, modal);
        initComponents();
        this.id_cliente = id_cliente;
        actualizar();
        this.setLocationRelativeTo(parent);
        metodos.addEscapeListenerWindowDialog(this);

        Contactos contratante = new Contactos();
        contratante.MostrarNombreContactos(cbx_contacto);

        jtabla_creditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(MouseEvent me) {
                JTable table = (JTable) me.getSource();
                Point p = me.getPoint();
                int row = table.rowAtPoint(p);
                if (me.getClickCount() == 2) {

                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla_creditos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        cbx_contacto = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lbl_cliente = new javax.swing.JLabel();
        lbl_id_cliente = new javax.swing.JLabel();
        btn_cambio = new newscomponents.RSButtonFlat_new();
        lbl_id_nuevo_cliente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtabla_cotizaciones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar contacto");

        jtabla_creditos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtabla_creditos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jtabla_creditos);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cbx_contacto.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        cbx_contacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_contactoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel1.setText("Seleccione el cliente al cual se le asignaran todos los creditos de:");

        lbl_cliente.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_cliente.setForeground(new java.awt.Color(153, 0, 0));
        lbl_cliente.setText("-");

        lbl_id_cliente.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_id_cliente.setForeground(new java.awt.Color(153, 0, 0));
        lbl_id_cliente.setText("-");

        btn_cambio.setBackground(new java.awt.Color(0, 102, 102));
        btn_cambio.setText("Realizar Cambio");
        btn_cambio.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btn_cambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cambioActionPerformed(evt);
            }
        });

        lbl_id_nuevo_cliente.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_id_nuevo_cliente.setForeground(new java.awt.Color(153, 0, 0));
        lbl_id_nuevo_cliente.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_cliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_id_cliente))
                    .addComponent(jLabel1)
                    .addComponent(cbx_contacto, 0, 911, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cambio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_id_nuevo_cliente, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_cliente)
                            .addComponent(lbl_id_cliente))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_id_nuevo_cliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbx_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel2.setText("Creditos / ventas");

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel3.setText("Devoluciones");

        jtabla_cotizaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jtabla_cotizaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cambioActionPerformed

        if (lbl_id_cliente.getText().equals(lbl_id_nuevo_cliente.getText())) {
            JOptionPane.showMessageDialog(this, "NO esta permitido eliminar seleccionar el mismo cliente para este proceso");
        } else {
            Connection con = null;
            String SSQL = "update facturas_cabeceras "
                    + "set id_contacto=" + lbl_id_nuevo_cliente.getText() + " "
                    + "where id_contacto=  " + lbl_id_cliente.getText() + ";\n"
                    + "update cotizaciones_cabeceras "
                    + "set id_contacto=" + lbl_id_nuevo_cliente.getText() + " "
                    + "where id_contacto=  " + lbl_id_cliente.getText() + ";";
            try {
                con = getConexion();
                PreparedStatement psql = con.prepareStatement(SSQL);
                psql.executeUpdate();
                psql.close();
                con.close();
                this.dispose();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "No se puede actualziar: \n" + e);
            }
        }

    }//GEN-LAST:event_btn_cambioActionPerformed

    private void cbx_contactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_contactoActionPerformed
        try {
            lbl_id_nuevo_cliente.setText("" + cbx_contacto.getItemAt(cbx_contacto.getSelectedIndex()).getId());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cbx_contactoActionPerformed
    private TableRowSorter trsFiltro;
    DefaultTableModel modelo_creditos = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false; //Con esto conseguimos que la tabla no se pueda editar
        }
    };
    DefaultTableModel modelo_cotizaciones = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false; //Con esto conseguimos que la tabla no se pueda editar
        }
    };

    public void actualizar() {
        String consulta = "select * from facturas_cabeceras where id_contacto=" + id_cliente;
        ResultSet rs = DB_consultas_R_D.getTabla(consulta);
        modelo_creditos.setColumnIdentifiers(new Object[]{"id", "Códgio", "Fecha", "Observación"});
        try {
            while (rs.next()) {
                // añade los resultado a al modelo de tabla
                modelo_creditos.addRow(new Object[]{rs.getString("id"), rs.getString("codigo"), rs.getString("fecha"), rs.getString("observacion")});
            }
            rs.close();
            // asigna el modelo a la tabla
        } catch (Exception e) {
            System.out.println(e);
        }
        jtabla_creditos.setModel(modelo_creditos);

        // Cotizaciones
        consulta = "select * from cotizaciones_cabeceras where id_contacto=" + id_cliente;
        rs = DB_consultas_R_D.getTabla(consulta);
        modelo_cotizaciones.setColumnIdentifiers(new Object[]{"id", "Códgio", "Fecha", "Observación"});
        try {
            while (rs.next()) {
                // añade los resultado a al modelo de tabla
                modelo_cotizaciones.addRow(new Object[]{rs.getString("id"), rs.getString("codigo"), rs.getString("fecha"), rs.getString("observacion")});
            }
            rs.close();
            // asigna el modelo a la tabla
        } catch (Exception e) {
            System.out.println(e);
        }
        jtabla_cotizaciones.setModel(modelo_cotizaciones);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jif_eliminar_contacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jif_eliminar_contacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jif_eliminar_contacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jif_eliminar_contacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jif_eliminar_contacto dialog = new jif_eliminar_contacto(new javax.swing.JFrame(), true, id_cliente);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private newscomponents.RSButtonFlat_new btn_cambio;
    public static javax.swing.JComboBox<Contactos> cbx_contacto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtabla_cotizaciones;
    private javax.swing.JTable jtabla_creditos;
    public static javax.swing.JLabel lbl_cliente;
    public static javax.swing.JLabel lbl_id_cliente;
    private javax.swing.JLabel lbl_id_nuevo_cliente;
    // End of variables declaration//GEN-END:variables
}
