/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios_internos;

import Formularios.frm_bodegas;
import Metodos.metodos;
import conexiondb.DB_Bodegas;
import conexiondb.DB_consultas_R_D;
import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import modelos.Bodegas;

/**
 *
 * @author Monkeyelgrande
 */
public class jif_crear_bodegas extends javax.swing.JDialog {

    /**
     * Creates new form jif_crear_familias
     */
    // Color identificador de la bodega en formato hex "#RRGGBB" (null = sin color).
    // Estatico para poder fijarlo desde frm_bodegas al editar, igual que el resto
    // de campos de este dialogo.
    public static String colorSeleccionado = null;

    public jif_crear_bodegas() {
        initComponents();
        txt_id.setText(DB_consultas_R_D.cargarId("bodegas"));
        this.setLocationRelativeTo(this);
        btn_editar.setVisible(false);
        metodos.addEscapeListenerWindowDialog(this);

        // Por defecto (Nuevo) arranca sin color. Al editar, frm_bodegas fija
        // colorSeleccionado y vuelve a llamar aplicarColorBoton().
        colorSeleccionado = null;
        aplicarColorBoton();
    }

    private void btn_colorActionPerformed(java.awt.event.ActionEvent evt) {
        Color inicial = Color.WHITE;
        if (colorSeleccionado != null && !colorSeleccionado.trim().isEmpty()) {
            try {
                inicial = Color.decode(colorSeleccionado.trim());
            } catch (NumberFormatException ignore) {
            }
        }
        Color elegido = JColorChooser.showDialog(this, "Seleccione el color de la bodega", inicial);
        if (elegido != null) {
            colorSeleccionado = String.format("#%02X%02X%02X",
                    elegido.getRed(), elegido.getGreen(), elegido.getBlue());
            aplicarColorBoton();
        }
    }

    /**
     * Refleja el color seleccionado en el boton: pinta su fondo con ese color y
     * muestra el codigo hex, con texto claro u oscuro segun el contraste. Si no
     * hay color, vuelve al texto "Seleccionar color".
     */
    public void aplicarColorBoton() {
        if (colorSeleccionado != null && !colorSeleccionado.trim().isEmpty()) {
            try {
                Color c = Color.decode(colorSeleccionado.trim());
                btn_color.setBackground(c);
                btn_color.setOpaque(true);
                btn_color.setText(colorSeleccionado);
                double lum = (0.299 * c.getRed() + 0.587 * c.getGreen() + 0.114 * c.getBlue()) / 255.0;
                btn_color.setForeground(lum < 0.55 ? Color.WHITE : Color.BLACK);
                return;
            } catch (NumberFormatException ignore) {
            }
        }
        btn_color.setBackground(null);
        btn_color.setText("Seleccionar color");
        btn_color.setForeground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        txt_id = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btn_limpiar = new javax.swing.JButton();
        chk_cerrar = new javax.swing.JCheckBox();
        btn_editar = new javax.swing.JButton();
        rbtn_Si_imprime = new javax.swing.JRadioButton();
        rbtn_NO_imprime = new javax.swing.JRadioButton();
        chk_genera_orden = new javax.swing.JCheckBox();
        chk_entrega_automatica = new javax.swing.JCheckBox();
        btn_color = new javax.swing.JButton();

        setModal(true);

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setEnabled(false);

        jLabel3.setText("Nombre");

        btn_guardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btn_guardar.setMnemonic('g');
        btn_guardar.setText("Guardar");
        btn_guardar.setBorder(null);
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        txt_id.setEditable(false);
        txt_id.setBackground(new java.awt.Color(204, 204, 204));

        jLabel12.setText("ID");

        btn_limpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        btn_limpiar.setMnemonic('l');
        btn_limpiar.setText("Limpiar");
        btn_limpiar.setBorder(null);
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        chk_cerrar.setSelected(true);
        chk_cerrar.setText("Cerrar formulario al guardar");

        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtn_Si_imprime);
        rbtn_Si_imprime.setText("Si imprime");

        buttonGroup1.add(rbtn_NO_imprime);
        rbtn_NO_imprime.setText("No, imprime");

        chk_genera_orden.setText("Genera orden de entrega automática al facturar venta");

        chk_entrega_automatica.setText("Entrega masiva: sus órdenes pendientes se entregan con el botón \"Entregar todo\"");
        chk_entrega_automatica.setToolTipText("Marca esta bodega (p. ej. Almacén Piso Uno) para poder entregar de una vez todas sus órdenes pendientes desde la pantalla de Órdenes");

        btn_color.setText("Seleccionar color");
        btn_color.setToolTipText("Color identificador de la bodega (para tablas, reportes y gráficos)");
        btn_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_colorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chk_cerrar)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_editar))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbtn_Si_imprime)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtn_NO_imprime))
                            .addComponent(chk_genera_orden)
                            .addComponent(chk_entrega_automatica)
                            .addComponent(btn_color, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_editar))
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_Si_imprime)
                    .addComponent(rbtn_NO_imprime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_genera_orden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_entrega_automatica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_color, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar)
                    .addComponent(btn_limpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chk_cerrar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        if (txt_nombre.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese un nombre para la bodega");
        } else {
            DB_Bodegas dbmarcas = new DB_Bodegas();
            Bodegas bodega = new Bodegas();
            try {
                bodega.setId(Integer.parseInt(txt_id.getText()));
            } catch (Exception e) {
            }
            bodega.setNombre(txt_nombre.getText());

            bodega.setImprime(0);
            if (rbtn_Si_imprime.isSelected()) {
                bodega.setImprime(1);
            }

            bodega.setGeneraOrdenAutomatica(chk_genera_orden.isSelected());

            bodega.setEntregaAutomatica(chk_entrega_automatica.isSelected());

            bodega.setColor(colorSeleccionado);

            if (DB_consultas_R_D.consultarId(txt_id.getText(), "bodegas") == 1) {
                dbmarcas.Actualizar(bodega);
            } else {
                dbmarcas.Guardar(bodega);
            }
            limpiar();
            txt_id.setText(DB_consultas_R_D.cargarId("bodegas"));
            if (chk_cerrar.isSelected()) {
                this.dispose();
            }
            frm_bodegas.btn_actualizar.doClick();
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        txt_nombre.setEnabled(true);
        btn_guardar.setEnabled(true);
        btn_limpiar.setEnabled(true);
        chk_cerrar.setEnabled(true);
        btn_color.setEnabled(true);
    }//GEN-LAST:event_btn_editarActionPerformed
    public void limpiar() {
        txt_nombre.setText("");
        chk_genera_orden.setSelected(false);
        chk_entrega_automatica.setSelected(false);
        colorSeleccionado = null;
        aplicarColorBoton();
        txt_nombre.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_color;
    public static javax.swing.JButton btn_editar;
    public static javax.swing.JButton btn_guardar;
    public static javax.swing.JButton btn_limpiar;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JCheckBox chk_cerrar;
    public static javax.swing.JCheckBox chk_entrega_automatica;
    public static javax.swing.JCheckBox chk_genera_orden;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JRadioButton rbtn_NO_imprime;
    public static javax.swing.JRadioButton rbtn_Si_imprime;
    public static javax.swing.JTextField txt_id;
    public static javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
