/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios_internos;

import Alertas.crear_nuevo_producto;
import Formularios.frm_main;
import Formularios.frm_traslado_productos_entre_bodegas;
import JDBuscar.jd_buscar_producto;
import JDBuscar.jd_buscar_producto_traslado;
import Metodos.TextPrompt;
import Metodos.metodos;
import Metodos.ver_factura_impresion;
import conexiondb.DB_Traslados_productos;
import conexiondb.DB_consultas_R_D;
import conexiondb.DBstock_productos;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelos.Bodegas;
import modelos.Traslados_productos;

/**
 *
 * @author Monkeyelgrande
 */
public class jif_Crear_traslado extends javax.swing.JDialog {

    /**
     * Creates new form jif_crear_ingreso_mecancia
     */
    public jif_Crear_traslado() {
        initComponents();

        Bodegas bod = new Bodegas();
        bod.mostrarBodegas(jbox_bodega_origen);
        bod.mostrarBodegas(jbox_bodega_destino);

        lbl_id_traslado.setText(DB_consultas_R_D.cargarId("traslados_productos"));
        Calendar fecha = new GregorianCalendar();
        jdate_fecha.setCalendar(fecha);
        this.setLocationRelativeTo(this);
        metodos.addEscapeListenerWindowDialog(this);
        actualizar_stock();
        TextPrompt pago_abono = new TextPrompt("Cantidad a trasladar", txt_cantidad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_producto = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        txt_cantidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jdate_fecha = new com.toedter.calendar.JDateChooser();
        jbox_bodega_origen = new javax.swing.JComboBox<>();
        jbox_bodega_destino = new javax.swing.JComboBox<>();
        btn_guardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_observacion = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        lbl_id_traslado = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setTitle("Ingreso de mercancia");
        setBackground(new java.awt.Color(0, 51, 153));
        setModal(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(225, 233, 236));
        jPanel1.setForeground(new java.awt.Color(225, 233, 236));

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(57, 75, 85));
        jLabel1.setText("Producto");

        txt_producto.setEditable(false);
        txt_producto.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        txt_producto.setForeground(new java.awt.Color(57, 75, 85));
        txt_producto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_productoFocusLost(evt);
            }
        });
        txt_producto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_productoKeyPressed(evt);
            }
        });

        btn_buscar.setBackground(new java.awt.Color(250, 171, 26));
        btn_buscar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(0, 51, 51));
        btn_buscar.setText("Buscar producto");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        txt_cantidad.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(57, 75, 85));
        jLabel2.setText("Cantidad");

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(57, 75, 85));
        jLabel3.setText("Origen");

        jLabel4.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(57, 75, 85));
        jLabel4.setText("Destino");

        jLabel23.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(57, 75, 85));
        jLabel23.setText("Fecha");

        jdate_fecha.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N

        jbox_bodega_origen.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jbox_bodega_origen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbox_bodega_origenKeyPressed(evt);
            }
        });

        jbox_bodega_destino.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jbox_bodega_destino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbox_bodega_destinoKeyPressed(evt);
            }
        });

        btn_guardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btn_guardar.setMnemonic('g');
        btn_guardar.setText("Guardar");
        btn_guardar.setBorder(null);
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(57, 75, 85));
        jLabel5.setText("Observación");

        txt_observacion.setColumns(20);
        txt_observacion.setRows(5);
        jScrollPane1.setViewportView(txt_observacion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel23)
                    .addComponent(jLabel5))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                    .addComponent(jdate_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbox_bodega_destino, 0, 532, Short.MAX_VALUE)
                    .addComponent(jbox_bodega_origen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_cantidad)
                    .addComponent(btn_buscar)
                    .addComponent(txt_producto)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jdate_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jbox_bodega_origen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jbox_bodega_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_guardar)
                .addGap(13, 13, 13))
        );

        jPanel2.setBackground(new java.awt.Color(84, 104, 120));

        lbl_id_traslado.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_id_traslado.setForeground(new java.awt.Color(255, 153, 153));
        lbl_id_traslado.setText("numero");

        jLabel25.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Nuevo Traslado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_id_traslado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(lbl_id_traslado)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void actualizar_stock() {
        // Stock is now managed via stock_productos table
    }

    public static int id_bodega_origen, id_bodega_destino;
    public static int id_producto;

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed

        int guardo_cabecera = 0;
        DB_Traslados_productos db_traslado = new DB_Traslados_productos();
        Traslados_productos obj = new Traslados_productos();
        DBstock_productos dbStock = new DBstock_productos();

        // Obtener bodegas
        int idBodegaOrigen = 0;
        int idBodegaDestino = 0;
        try {
            idBodegaOrigen = jbox_bodega_origen.getItemAt(jbox_bodega_origen.getSelectedIndex()).getId();
        } catch (Exception e) {
            idBodegaOrigen = id_bodega_origen;
        }
        try {
            idBodegaDestino = jbox_bodega_destino.getItemAt(jbox_bodega_destino.getSelectedIndex()).getId();
        } catch (Exception e) {
            idBodegaDestino = id_bodega_destino;
        }

        // Validar que origen y destino sean diferentes
        if (idBodegaOrigen == idBodegaDestino) {
            JOptionPane.showMessageDialog(this,
                    "La bodega de origen y destino no pueden ser iguales.",
                    "Error de validación",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        obj.setId_bodega_origen(idBodegaOrigen);
        obj.setId_bodega_destino(idBodegaDestino);
        obj.setId_producto(id_producto);

        double cantidad = Double.parseDouble(txt_cantidad.getText());
        obj.setCantidad(cantidad);
        obj.setId_user(frm_main.id_user);
        obj.setObservacion(txt_observacion.getText());

        int hora, minutos, segundos;
        int dia, mes, ano;
        ano = jdate_fecha.getCalendar().get(Calendar.YEAR);
        mes = jdate_fecha.getCalendar().get(Calendar.MONTH) + 1;
        dia = jdate_fecha.getCalendar().get(Calendar.DAY_OF_MONTH);
        hora = jdate_fecha.getCalendar().get(Calendar.HOUR_OF_DAY);
        minutos = jdate_fecha.getCalendar().get(Calendar.MINUTE);
        segundos = jdate_fecha.getCalendar().get(Calendar.SECOND);
        obj.setFecha("'" + ano + "-" + mes + "-" + dia + "'");
        obj.setHora("'" + hora + ":" + minutos + ":" + segundos + "'");

        int idTraslado = Integer.parseInt(lbl_id_traslado.getText());
        obj.setId(idTraslado);

        boolean esEdicion = DB_consultas_R_D.consultarId(lbl_id_traslado.getText(), "traslados_productos") == 1;

        if (esEdicion) {
            // ════════════════════════════════════════════════════════════
            // EDICIÓN: Reversar traslado anterior antes de actualizar
            // ════════════════════════════════════════════════════════════
            reversarTrasladoAnterior(idTraslado, dbStock);

            guardo_cabecera = db_traslado.Actualizar(obj);
        } else {
            guardo_cabecera = db_traslado.Guardar(obj);
        }

        if (guardo_cabecera > 0) {
            // ════════════════════════════════════════════════════════════
            // INTEGRACIÓN STOCK: Registrar traslado (salida + entrada)
            // ════════════════════════════════════════════════════════════
            String obsTraslado = "Traslado #" + idTraslado;
            if (!txt_observacion.getText().isEmpty()) {
                obsTraslado += " - " + txt_observacion.getText();
            }

            // Salida de bodega origen
            dbStock.trasladoSalida(
                    id_producto,
                    idBodegaOrigen,
                    frm_main.id_user,
                    cantidad,
                    idTraslado,
                    obsTraslado + " (Salida)"
            );

            // Entrada a bodega destino
            dbStock.trasladoEntrada(
                    id_producto,
                    idBodegaDestino,
                    frm_main.id_user,
                    cantidad,
                    idTraslado,
                    obsTraslado + " (Entrada)"
            );

            System.out.println("GUARDO EL TRASLADO CON STOCK");
        }

        frm_traslado_productos_entre_bodegas.btn_actualizar.doClick();
        this.dispose();

    }//GEN-LAST:event_btn_guardarActionPerformed
// ════════════════════════════════════════════════════════════════════════════
// MÉTODO AUXILIAR: Reversar traslado anterior (para ediciones)
// ════════════════════════════════════════════════════════════════════════════

    private void reversarTrasladoAnterior(int idTraslado, DBstock_productos dbStock) {
        String sql = "SELECT id_producto, id_bodega_origen, id_bodega_destino, cantidad "
                + "FROM traslados_productos WHERE id = " + idTraslado;

        ResultSet rs = DB_consultas_R_D.getTabla(sql);
        try {
            if (rs.next()) {
                int idProductoAnt = rs.getInt("id_producto");
                int idBodegaOrigenAnt = rs.getInt("id_bodega_origen");
                int idBodegaDestinoAnt = rs.getInt("id_bodega_destino");
                double cantidadAnt = rs.getDouble("cantidad");

                String obsAnulacion = "Reversión por edición - Traslado #" + idTraslado;

                // Anular salida anterior (devolver a origen)
                dbStock.anularTrasladoSalida(
                        idProductoAnt,
                        idBodegaOrigenAnt,
                        frm_main.id_user,
                        cantidadAnt,
                        idTraslado,
                        obsAnulacion
                );

                // Anular entrada anterior (quitar de destino)
                dbStock.anularTrasladoEntrada(
                        idProductoAnt,
                        idBodegaDestinoAnt,
                        frm_main.id_user,
                        cantidadAnt,
                        idTraslado,
                        obsAnulacion
                );
            }
            rs.close();
        } catch (SQLException e) {
            System.out.println("Error reversando traslado anterior: " + e);
        }
    }
    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        jd_buscar_producto_traslado buscar_producto = new jd_buscar_producto_traslado(null, rootPaneCheckingEnabled);
        buscar_producto.show();
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void txt_productoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_productoKeyPressed


    }//GEN-LAST:event_txt_productoKeyPressed


    private void txt_productoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_productoFocusLost

    }//GEN-LAST:event_txt_productoFocusLost

    private void jbox_bodega_origenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbox_bodega_origenKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbox_bodega_origenKeyPressed

    private void jbox_bodega_destinoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbox_bodega_destinoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbox_bodega_destinoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_buscar;
    public static javax.swing.JButton btn_guardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JComboBox<Bodegas> jbox_bodega_destino;
    public static javax.swing.JComboBox<Bodegas> jbox_bodega_origen;
    public static com.toedter.calendar.JDateChooser jdate_fecha;
    public static javax.swing.JLabel lbl_id_traslado;
    public static javax.swing.JTextField txt_cantidad;
    public static javax.swing.JTextArea txt_observacion;
    public static javax.swing.JTextField txt_producto;
    // End of variables declaration//GEN-END:variables

}
