/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Creditos;

import Creditos.EstadoCarteraRenderer;
import Metodos.ExportarExcel;
import Creditos.ExportarExcelEstadoCartera;
import Metodos.metodos;
import conexiondb.DB_consultas_R_D;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import Creditos.modelos.Contactos;

/**
 *
 * @author Monkeyelgrande
 */
public class jd_Estado_cuenta extends javax.swing.JDialog {

    /**
     * Creates new form jd_Ventas_diarias
     */
    static DefaultTableModel modelo1 = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false; //Con esto conseguimos que la tabla no se pueda editar
        }
    };

    DecimalFormat formatea = new DecimalFormat("###,###.##");
    TableColumnModel columnModelCreditos = null;

    public jd_Estado_cuenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Ingresos");
        columnModelCreditos = jtabla_creditos.getColumnModel();
        this.setLocationRelativeTo(parent);
        poner_fechas();
        metodos.addEscapeListenerWindowDialog(this);
        doble_clic_tablas();
        Contactos.MostrarNombreContactos(cbx_contacto);
        mostrar(0);
    }

    public void poner_fechas() {
        try {
            GregorianCalendar cal = new GregorianCalendar();
            jdate_fecha1.setDate(cal.getTime());

        } catch (Exception e) {
        }
    }

    public void TamanosTablaVentas(TableColumnModel cm) {
        cm.getColumn(0).setPreferredWidth(40);
        cm.getColumn(1).setPreferredWidth(300);
        cm.getColumn(2).setPreferredWidth(150);
        cm.getColumn(2).setPreferredWidth(200);
    }

    public void doble_clic_tablas() {
        jtabla_creditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(MouseEvent me) {
                JTable table = (JTable) me.getSource();
                Point p = me.getPoint();
                if (me.getClickCount() == 2) {

                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpop_1 = new javax.swing.JPopupMenu();
        jmenu_VerFactura1 = new javax.swing.JMenuItem();
        jpop_2 = new javax.swing.JPopupMenu();
        jmenu_2 = new javax.swing.JMenuItem();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jdate_fecha1 = new com.toedter.calendar.JDateChooser();
        cbx_contacto = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btn_consultar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla_creditos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_Total_Creditos = new javax.swing.JLabel();
        btn_exportar_excel = new javax.swing.JButton();
        lbl_Total_3 = new javax.swing.JLabel();
        lbl_Total_Creditos_1 = new javax.swing.JLabel();
        btn_consultar1 = new javax.swing.JButton();

        jmenu_VerFactura1.setText("Ver factura");
        jpop_1.add(jmenu_VerFactura1);

        jmenu_2.setText("jMenuItem1");
        jpop_2.add(jmenu_2);

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estado de cartera");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jdate_fecha1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cbx_contacto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbx_contactoFocusLost(evt);
            }
        });
        cbx_contacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_contactoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Fecha inicio:");

        btn_consultar.setBackground(new java.awt.Color(102, 255, 102));
        btn_consultar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_consultar.setMnemonic('r');
        btn_consultar.setText("Consultar");
        btn_consultar.setToolTipText("ATL+R");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        jtabla_creditos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtabla_creditos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtabla_creditos.setComponentPopupMenu(jpop_1);
        jtabla_creditos.setRowHeight(22);
        jtabla_creditos.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jtabla_creditos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jtabla_creditos);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Estado de cartera");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Total créditos");

        lbl_Total_Creditos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Total_Creditos.setText("0");

        btn_exportar_excel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_exportar_excel.setText("Exportar a excel");
        btn_exportar_excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exportar_excelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1496, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_Total_Creditos)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(882, Short.MAX_VALUE)
                    .addComponent(btn_exportar_excel)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbl_Total_Creditos))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(608, Short.MAX_VALUE)
                    .addComponent(btn_exportar_excel)
                    .addContainerGap()))
        );

        lbl_Total_3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Total_3.setText("Total ingresos:");

        lbl_Total_Creditos_1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Total_Creditos_1.setForeground(new java.awt.Color(0, 153, 0));
        lbl_Total_Creditos_1.setText("0");

        btn_consultar1.setBackground(new java.awt.Color(102, 255, 102));
        btn_consultar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_consultar1.setMnemonic('r');
        btn_consultar1.setText("Bucar cliente");
        btn_consultar1.setToolTipText("ATL+R");
        btn_consultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdate_fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_consultar)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_Total_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_Total_Creditos_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_consultar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jdate_fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_consultar)
                        .addComponent(lbl_Total_3)
                        .addComponent(lbl_Total_Creditos_1)
                        .addComponent(cbx_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_consultar1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void LimpiarModelos() {
        try {
            for (int i = 0; i < jtabla_creditos.getRowCount(); i++) {
                modelo1.removeRow(i);
                i -= 1;
            }
        } catch (Exception e) {
        }

    }
    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        mostrar(0);
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void btn_exportar_excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exportar_excelActionPerformed

        ExportarExcelEstadoCartera obj;

        try {
            obj = new ExportarExcelEstadoCartera();
            obj.exportarExcel(jtabla_creditos);
        } catch (IOException ex) {
            System.out.println("Error al exportar: " + ex);
        }
    }//GEN-LAST:event_btn_exportar_excelActionPerformed

    private void cbx_contactoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbx_contactoFocusLost
    }//GEN-LAST:event_cbx_contactoFocusLost

    private void cbx_contactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_contactoActionPerformed

    }//GEN-LAST:event_cbx_contactoActionPerformed

    private void btn_consultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultar1ActionPerformed
        try {
            mostrar(cbx_contacto.getItemAt(cbx_contacto.getSelectedIndex()).getId());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Seleccione un contacto");
        }
    }//GEN-LAST:event_btn_consultar1ActionPerformed
    public void mostrar(int id_cliente) {
        LimpiarModelos();
        String fecha1 = "";
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        fecha1 = sdf.format(jdate_fecha1.getDate());

        String consulta = "WITH abonos_por_credito AS (\n"
                + "    SELECT\n"
                + "        id_credito,\n"
                + "        SUM(abono) AS total_abonos\n"
                + "    FROM abonos\n"
                + "    WHERE  fecha <= '" + fecha1 + "'::date    -- solo abonos hasta esta fecha\n"
                + "    GROUP BY id_credito\n"
                + ")\n"
                + "SELECT\n"
                + "    c.id          AS id_cliente,\n"
                + "    c.nombre      AS nombre_cliente,\n"
                + "    c.cedula,\n"
                + "    c.contacto as celular,\n"
                + "    \n"
                + "    f.id          AS id_credito,\n"
                + "    f.codigo      AS codigo_credito,\n"
                + "    f.fecha_creacion,\n"
                + "    f.fecha_vencimiento,\n"
                + "    \n"
                + "    f.total                           AS total_factura,\n"
                + "    COALESCE(apc.total_abonos, 0)     AS total_abonado,\n"
                + "    (f.total - COALESCE(apc.total_abonos, 0)) AS saldo_pendiente\n"
                + "FROM creditos f\n"
                + "JOIN contactos c\n"
                + "      ON c.id = f.id_contacto\n"
                + "LEFT JOIN abonos_por_credito apc\n"
                + "      ON apc.id_credito = f.id\n"
                + "WHERE f.fecha_creacion <= '" + fecha1 + "'::date           -- solo facturas creadas hasta esta fecha\n"
                + "  AND (f.total - COALESCE(apc.total_abonos, 0)) > 0   -- solo créditos pendientes\n";

        // Agregar filtro por cliente si id_cliente > 0
        if (id_cliente > 0) {
            consulta += "  AND c.id = " + id_cliente + "\n";
        }

        consulta += "ORDER BY c.nombre, f.fecha_creacion;";

        System.out.println(consulta);

        ResultSet rs = DB_consultas_R_D.getTabla(consulta);

        modelo1.setColumnIdentifiers(new Object[]{"Col 0", "Col 1", "Col 2", "Col 3", "Col 4", "Col 5", "Col 6"});

        try {
            String clienteActual = null;
            double totalFacturaCliente = 0;
            double totalAbonadoCliente = 0;
            double totalPendienteCliente = 0;

            // Lista temporal para almacenar las filas de créditos del cliente actual
            java.util.List<Object[]> creditosCliente = new java.util.ArrayList<>();

            // Variables para datos del cliente
            String idCliente = "";
            String nombreCliente = "";
            String cedulaCliente = "";
            String celularCliente = "";

            while (rs.next()) {
                String idClienteActual = rs.getString("id_cliente");

                // Si cambiamos de cliente, volcamos el anterior
                if (clienteActual != null && !clienteActual.equals(idClienteActual)) {
                    // Agregar encabezado de cliente
                    modelo1.addRow(new Object[]{"ID", "NOMBRE", "CEDULA", "CELULAR", "", "", ""});
                    // Agregar datos del cliente
                    modelo1.addRow(new Object[]{idCliente, nombreCliente, cedulaCliente, celularCliente, "", "", ""});
                    // Agregar encabezado de créditos
                    modelo1.addRow(new Object[]{"ID", "CODIGO", "F. CREACION", "F. VENCIMIENTO", "TOTAL FACTURA", "TOTAL ABONADO", "TOTAL PENDIENTE"});

                    // Agregar todas las filas de créditos
                    for (Object[] credito : creditosCliente) {
                        modelo1.addRow(credito);
                    }

                    // Agregar fila de total
                    modelo1.addRow(new Object[]{"", "", "", "TOTAL",
                        metodos.formateador_dinero().format(totalFacturaCliente),
                        metodos.formateador_dinero().format(totalAbonadoCliente),
                        metodos.formateador_dinero().format(totalPendienteCliente)
                    });

                    // Agregar fila vacía
                    modelo1.addRow(new Object[]{"", "", "", "", "", "", ""});
                    modelo1.addRow(new Object[]{"", "", "", "", "", "", ""});

                    // Resetear acumuladores
                    creditosCliente.clear();
                    totalFacturaCliente = 0;
                    totalAbonadoCliente = 0;
                    totalPendienteCliente = 0;
                }

                // Actualizar cliente actual
                clienteActual = idClienteActual;
                idCliente = rs.getString("id_cliente");
                nombreCliente = rs.getString("nombre_cliente");
                cedulaCliente = rs.getString("cedula");
                celularCliente = rs.getString("celular");

                // Obtener datos del crédito
                double totalFactura = rs.getDouble("total_factura");
                double totalAbonado = rs.getDouble("total_abonado");
                double saldoPendiente = rs.getDouble("saldo_pendiente");

                // Acumular totales
                totalFacturaCliente += totalFactura;
                totalAbonadoCliente += totalAbonado;
                totalPendienteCliente += saldoPendiente;

                // Agregar crédito a la lista temporal
                creditosCliente.add(new Object[]{
                    rs.getString("id_credito"),
                    rs.getString("codigo_credito"),
                    rs.getString(("fecha_creacion")),
                    rs.getString("fecha_vencimiento"),
                    metodos.formateador_dinero().format(totalFactura),
                    metodos.formateador_dinero().format(totalAbonado),
                    metodos.formateador_dinero().format(saldoPendiente)
                });
            }

            // Volcar el último cliente
            if (clienteActual != null) {
                // Agregar encabezado de cliente
                modelo1.addRow(new Object[]{"ID", "NOMBRE", "CEDULA", "CELULAR", "", "", ""});
                // Agregar datos del cliente
                modelo1.addRow(new Object[]{idCliente, nombreCliente, cedulaCliente, celularCliente, "", "", ""});
                // Agregar encabezado de créditos
                modelo1.addRow(new Object[]{"ID", "CODIGO", "F. CREACION", "F. VENCIMIENTO", "TOTAL FACTURA", "TOTAL ABONADO", "TOTAL PENDIENTE"});

                // Agregar todas las filas de créditos
                for (Object[] credito : creditosCliente) {
                    modelo1.addRow(credito);
                }

                // Agregar fila de total
                modelo1.addRow(new Object[]{"", "", "", "TOTAL",
                    metodos.formateador_dinero().format(totalFacturaCliente),
                    metodos.formateador_dinero().format(totalAbonadoCliente),
                    metodos.formateador_dinero().format(totalPendienteCliente)
                });
            }

            rs.close();
            // asigna el modelo a la tabla
            jtabla_creditos.setModel(modelo1);
            // Aplicar el renderer personalizado a todas las columnas
            EstadoCarteraRenderer renderer = new EstadoCarteraRenderer();
            for (int i = 0; i < jtabla_creditos.getColumnCount(); i++) {
                jtabla_creditos.getColumnModel().getColumn(i).setCellRenderer(renderer);
            }
            TamanosTablaVentas(columnModelCreditos);
        } catch (Exception e) {
            System.out.println(e);
        }

        sumar_totales();
    }

    public void sumar_totales() {
        double total_facturas = 0;

        for (int i = 0; i < jtabla_creditos.getRowCount(); i++) {
            try {
                // Verificar si NO es una fila de TOTAL ni de encabezado
                String col3 = jtabla_creditos.getValueAt(i, 3).toString();

                if (!col3.equals("TOTAL") && !col3.equals("F. VENCIMIENTO") && !col3.equals("CELULAR")) {
                    total_facturas += Double.parseDouble(metodos.EliminaCaracteres(jtabla_creditos.getValueAt(i, 6).toString(), "."));
                }
            } catch (Exception e) {
                // Ignorar filas que no tengan número en la columna 6
            }
        }
        lbl_Total_Creditos.setText(metodos.formateador_dinero().format(total_facturas));
        lbl_Total_Creditos_1.setText(metodos.formateador_dinero().format(total_facturas));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jd_Estado_cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jd_Estado_cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jd_Estado_cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jd_Estado_cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jd_Estado_cuenta dialog = new jd_Estado_cuenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_consultar1;
    private javax.swing.JButton btn_exportar_excel;
    public static javax.swing.JComboBox<Contactos> cbx_contacto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdate_fecha1;
    private javax.swing.JMenuItem jmenu_2;
    private javax.swing.JMenuItem jmenu_VerFactura1;
    private javax.swing.JPopupMenu jpop_1;
    private javax.swing.JPopupMenu jpop_2;
    private javax.swing.JTable jtabla_creditos;
    private javax.swing.JLabel lbl_Total_3;
    private javax.swing.JLabel lbl_Total_Creditos;
    private javax.swing.JLabel lbl_Total_Creditos_1;
    // End of variables declaration//GEN-END:variables
}
