/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Creditos;

import Creditos.jd_ver_creditos_cliente;
import Metodos.ExportarExcel;
import Metodos.metodos;
import conexiondb.DB_consultas_R_D;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Monkeyelgrande
 */
public class jd_Interes_hasta_fecha extends javax.swing.JDialog {

    /**
     * Creates new form jd_Ventas_diarias
     */
    static DefaultTableModel modelo1 = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false; //Con esto conseguimos que la tabla no se pueda editar
        }
    };
    TableColumnModel columnModelVentas = null;

    public jd_Interes_hasta_fecha(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        columnModelVentas = jtabla_data.getColumnModel();
        setTitle("Ingresos");
        this.setLocationRelativeTo(parent);
        metodos.addEscapeListenerWindowDialog(this);
        Calendar fecha = new GregorianCalendar();
        jdate_buscar.setCalendar(fecha);
        btn_consultar.doClick();
        metodos.BuscarEnTabla(txt_Filtro, jtabla_data);

        jtabla_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(MouseEvent me) {
                if (me.getClickCount() == 2) {
                    AbonarCliente();
                }
            }
        });

    }

    public void AbonarCliente() {
        int fila = jtabla_data.getSelectedRow();
        jd_ver_creditos_cliente frm = new jd_ver_creditos_cliente(null, false, jtabla_data.getValueAt(fila, 0).toString());
        jd_ver_creditos_cliente.ventana = "creditos";
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un registro");
        } else {
            frm.show();
        }

    }

    public void TamanosTablaVentas(TableColumnModel cm) {
        cm.getColumn(0).setPreferredWidth(25);
        cm.getColumn(1).setPreferredWidth(250);
        cm.getColumn(2).setPreferredWidth(80);
        cm.getColumn(3).setPreferredWidth(80);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpop_1 = new javax.swing.JPopupMenu();
        jmenu_VerFactura1 = new javax.swing.JMenuItem();
        jpop_2 = new javax.swing.JPopupMenu();
        jmenu_2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jdate_buscar = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        btn_consultar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_Total_Gastos = new javax.swing.JLabel();
        txt_Filtro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla_data = new javax.swing.JTable();
        lbl_Total_3 = new javax.swing.JLabel();
        lbl_Total_ingresos = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jmenu_VerFactura1.setText("Ver factura");
        jpop_1.add(jmenu_VerFactura1);

        jmenu_2.setText("jMenuItem1");
        jpop_2.add(jmenu_2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingresos diarios");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jdate_buscar.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(20, 36, 51));
        jLabel1.setText("Seleccione fecha:");

        btn_consultar.setBackground(new java.awt.Color(250, 217, 166));
        btn_consultar.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btn_consultar.setForeground(new java.awt.Color(20, 36, 51));
        btn_consultar.setMnemonic('r');
        btn_consultar.setText("Consultar");
        btn_consultar.setToolTipText("ATL+R");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(41, 82, 100));

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 217, 166));
        jLabel2.setText("Ingresos");

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 217, 166));
        jLabel3.setText("Total");

        lbl_Total_Gastos.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lbl_Total_Gastos.setForeground(new java.awt.Color(250, 217, 166));
        lbl_Total_Gastos.setText("0");

        txt_Filtro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_FiltroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_FiltroKeyTyped(evt);
            }
        });

        jtabla_data.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jtabla_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtabla_data.setComponentPopupMenu(jpop_1);
        jtabla_data.setRowHeight(22);
        jtabla_data.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jtabla_data.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jtabla_data);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_Total_Gastos))
                            .addComponent(txt_Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbl_Total_Gastos))
                .addContainerGap())
        );

        lbl_Total_3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Total_3.setForeground(new java.awt.Color(20, 36, 51));
        lbl_Total_3.setText("Total Ingresos:");

        lbl_Total_ingresos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Total_ingresos.setForeground(new java.awt.Color(20, 36, 51));
        lbl_Total_ingresos.setText("0");

        jButton1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(20, 36, 51));
        jButton1.setText("Exportar a excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdate_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_consultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Total_3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Total_ingresos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1102, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_Total_3)
                        .addComponent(lbl_Total_ingresos)
                        .addComponent(jButton1)
                        .addComponent(btn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jdate_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void LimpiarModelos() {
        try {
            for (int i = 0; i < jtabla_data.getRowCount(); i++) {
                modelo1.removeRow(i);
                i -= 1;
            }
        } catch (Exception e) {
        }

    }
    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        LimpiarModelos();
        String fecha = "";
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        fecha = sdf.format(jdate_buscar.getDate());
        ResultSet rs = null;
        String consulta = "";

        consulta = "with resultado as (\n"
                + "	with consulta as (\n"
                + "		select c.id as id_cliente, c.nombre, c.cedula, c.contacto as celular, c.interes, sum(f.total) as total, \n"
                + "		(select max(fecha_vencimiento) from creditos where id_contacto=c.id) as ultima_factura, (select max(fecha) from abonos_cabeceras where id_contacto=c.id) as ultimo_abono,\n"
                + "		coalesce((select sum(total) from abonos_cabeceras where id_contacto=c.id and fecha < '" + fecha + "'),0) as abonos, \n"
                + "		(sum(f.total) - coalesce((select sum(total) from abonos_cabeceras where id_contacto=c.id and fecha < '" + fecha + "'),0)) as saldo \n"
                + "\n"
                + "		from creditos f, contactos c \n"
                + "\n"
                + "		where f.id_contacto=c.id and f.fecha_creacion < '" + fecha + "'\n"
                + "\n"
                + "		group by c.id, c.nombre\n"
                + "\n"
                + "		order by c.nombre\n"
                + "	)\n"
                + "	select c.id as id_cliente, c.antiguo,  c.nombre, c.cedula, c.contacto as celular, co.ultima_factura, coalesce(co.ultimo_abono||'','No abonado') as ultimo_abono, \n"
                + "	(co.ultima_factura-'" + fecha + "')*-1 as dias_vencidos_ultima_factura, \n"
                + "	(+coalesce(co.ultimo_abono-'" + fecha + "',0))*-1 as dias_vencidos_ultimo_abono, \n"
                + "	c.interes as porcentaje, co.saldo, (co.saldo*(c.interes/100)) as interes\n"
                + "	from contactos c left join consulta co on co.id_cliente=c.id\n"
                + "	where saldo != 0 \n"
                + "	order by c.nombre\n"
                + ")\n"
                + "select r.*, \n"
                + "case \n"
                + "	when dias_vencidos_ultima_factura <= 0 \n"
                + "	then 'Vigente' \n"
                + "	else \n"
                + "		case \n"
                + "			when dias_vencidos_ultima_factura > dias_vencidos_ultimo_abono \n"
                + "			then \n"
                + "				case \n"
                + "					when dias_vencidos_ultimo_abono = 0\n"
                + "					then 'se calcula con dias de factura' \n"
                + "					else 'se calcula con dias de abono' \n"
                + "				end\n"
                + "			else 'se calcula con dias de factura' \n"
                + "		end\n"
                + "\n"
                + "end as estado,\n"
                + "\n"
                + "case \n"
                + "	when dias_vencidos_ultima_factura <= 0 \n"
                + "	then 0 \n"
                + "	else \n"
                + "		case \n"
                + "			when dias_vencidos_ultima_factura > dias_vencidos_ultimo_abono \n"
                + "			then \n"
                + "				case \n"
                + "					when dias_vencidos_ultimo_abono = 0\n"
                + "					then (interes/30)* dias_vencidos_ultima_factura\n"
                + "					else (interes/30)*  dias_vencidos_ultimo_abono\n"
                + "				end\n"
                + "			else (interes/30)* dias_vencidos_ultima_factura\n"
                + "		end\n"
                + "\n"
                + "end as interes_calculado\n"
                + "\n"
                + "from resultado r;\n"
                + "\n"
                + "";
        System.out.println(consulta);
        rs = DB_consultas_R_D.getTabla(consulta);
        modelo1.setColumnIdentifiers(new Object[]{"ID Cliente", "Cliente", "Cedula", "Celular", "Vencimiento Últ. Fact", "Ultimo Abono", "Días V. Factura", "Días V. Abono", "% Interes", "Interes Mensual", "Saldo", "Estado", "Interes Calculado"});

        double T_deuda = 0;
        try {
            while (rs.next()) {
                // añade los resultado a al modelo de tabla
                modelo1.addRow(new Object[]{rs.getString("id_cliente"), rs.getString("nombre"), rs.getString("cedula"), rs.getString("celular"),
                    rs.getString("ultima_factura"), rs.getString("ultimo_abono"), rs.getString("dias_vencidos_ultima_factura"), rs.getString("dias_vencidos_ultimo_abono"),
                    rs.getDouble("porcentaje"), metodos.formateador_dinero().format(rs.getDouble("interes")), metodos.formateador_dinero().format(rs.getDouble("saldo")),
                    rs.getString("estado"), metodos.formateador_dinero().format(rs.getDouble("interes_calculado"))});
            }
            rs.close();
            // asigna el modelo a la tabla
            jtabla_data.setModel(modelo1);
            TamanosTablaVentas(columnModelVentas);
            for (int i = 0; i < this.jtabla_data.getRowCount(); i++) {
                T_deuda += Double.parseDouble(metodos.EliminaCaracteres(this.jtabla_data.getValueAt(i, 12).toString(), "."));
            }
        } catch (Exception e) {
            System.out.println(e);
        }

        lbl_Total_Gastos.setText("$ " + metodos.formateador_dinero().format(T_deuda));
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ExportarExcel obj;

        try {
            obj = new ExportarExcel();
            obj.exportarExcel(jtabla_data);
        } catch (IOException ex) {
            System.out.println("" + ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_FiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_FiltroKeyPressed
        char num = evt.getKeyChar();
        if ((num == KeyEvent.VK_DELETE)) {
            txt_Filtro.setText("");
        }
        if ((num == KeyEvent.VK_ENTER)) {

        }
    }//GEN-LAST:event_txt_FiltroKeyPressed

    private void txt_FiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_FiltroKeyTyped

    }//GEN-LAST:event_txt_FiltroKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jd_Interes_hasta_fecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jd_Interes_hasta_fecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jd_Interes_hasta_fecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jd_Interes_hasta_fecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jd_Interes_hasta_fecha dialog = new jd_Interes_hasta_fecha(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdate_buscar;
    private javax.swing.JMenuItem jmenu_2;
    private javax.swing.JMenuItem jmenu_VerFactura1;
    private javax.swing.JPopupMenu jpop_1;
    private javax.swing.JPopupMenu jpop_2;
    private javax.swing.JTable jtabla_data;
    private javax.swing.JLabel lbl_Total_3;
    private javax.swing.JLabel lbl_Total_Gastos;
    private javax.swing.JLabel lbl_Total_ingresos;
    private javax.swing.JTextField txt_Filtro;
    // End of variables declaration//GEN-END:variables
}
