/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Creditos;

import Creditos.frm_contactos;
import Formularios.frm_main;
import Metodos.TextPrompt;
import Metodos.metodos;
import conexiondb.DB_consultas_R_D;
import Creditos.db.DBcontactos;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Creditos.modelos.Contactos;

/**
 *
 * @author Monkeyelgrande
 */
public class jif_crear_contactos extends javax.swing.JDialog {

    /**
     * Creates new form jif_crear_cliente
     */
    public jif_crear_contactos() {
        initComponents();
        txt_id_contacto.setText(DB_consultas_R_D.cargarId("contactos"));
        btn_editar.setVisible(false);
        this.setLocationRelativeTo(this);
        permisos(frm_main.perfil);
        placeholders();
        jtxa_observaciones.setWrapStyleWord(true);
        metodos.addEscapeListenerWindowDialog(this);
        Contactos.mostrarContactosCiudad(txt_ciudad, false);
    }

    public void permisos(int perfil) {
        switch (perfil) {
            case 2:

                btn_editar.setEnabled(false);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txt_telefono = new javax.swing.JTextField();
        txt_celular = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        txt_cedula = new javax.swing.JTextField();
        txt_id_contacto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btn_limpiar = new javax.swing.JButton();
        chk_cerrar = new javax.swing.JCheckBox();
        btn_editar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_ciudad = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxa_observaciones = new javax.swing.JTextArea();
        txt_cupo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        chk_empleado = new javax.swing.JCheckBox();
        chk_antiguo = new javax.swing.JCheckBox();
        txt_interes = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setModal(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setEnabled(false);

        txt_telefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefonoKeyTyped(evt);
            }
        });

        txt_celular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_celular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_celularKeyTyped(evt);
            }
        });

        txt_direccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nombre y apellido*");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Cedula/NIT*");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Celular");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Teléfono");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Dirección");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Email");

        txt_nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btn_guardar.setFont(btn_guardar.getFont().deriveFont(btn_guardar.getFont().getStyle() | java.awt.Font.BOLD, 14));
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btn_guardar.setMnemonic('g');
        btn_guardar.setText("Guardar");
        btn_guardar.setBorder(null);
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        txt_cedula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_cedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cedulaFocusLost(evt);
            }
        });

        txt_id_contacto.setEditable(false);
        txt_id_contacto.setBackground(new java.awt.Color(204, 204, 204));
        txt_id_contacto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("ID");

        btn_limpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        btn_limpiar.setMnemonic('l');
        btn_limpiar.setText("Limpiar");
        btn_limpiar.setBorder(null);
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        chk_cerrar.setSelected(true);
        chk_cerrar.setText("Cerrar formulario al guardar");

        btn_editar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Campos con (*) son obligatorios");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Ciudad");

        txt_ciudad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel17.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel17.setText("Observaciones:");

        jtxa_observaciones.setColumns(20);
        jtxa_observaciones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxa_observaciones.setLineWrap(true);
        jtxa_observaciones.setRows(5);
        jScrollPane3.setViewportView(jtxa_observaciones);

        txt_cupo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_cupo.setForeground(new java.awt.Color(0, 153, 153));
        txt_cupo.setText("0");
        txt_cupo.setToolTipText("Para crédito ilimatado deje este espacio en 0");
        txt_cupo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cupoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cupoFocusLost(evt);
            }
        });
        txt_cupo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cupoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cupoKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel18.setText("Cupo");

        chk_empleado.setText("Empleado");

        chk_antiguo.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        chk_antiguo.setText("Antiguo");

        txt_interes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_interes.setForeground(new java.awt.Color(0, 153, 153));
        txt_interes.setText("0");
        txt_interes.setToolTipText("Para crédito ilimatado deje este espacio en 0");
        txt_interes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_interesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_interesFocusLost(evt);
            }
        });
        txt_interes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_interesKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_interesKeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel19.setText("Interes");

        jLabel20.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel20.setText("%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_cupo)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chk_empleado)
                                .addGap(78, 78, 78)
                                .addComponent(chk_antiguo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_interes, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txt_interes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk_empleado)
                    .addComponent(chk_antiguo))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_email)
                            .addComponent(txt_ciudad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_telefono)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chk_cerrar)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(txt_id_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btn_editar)
                                                .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_celular, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                                    .addComponent(txt_nombre))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_id_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txt_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_guardar)
                            .addComponent(btn_limpiar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chk_cerrar)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefonoKeyTyped
        char car = evt.getKeyChar();
        DB_consultas_R_D.validar_numeros(evt, car);
    }//GEN-LAST:event_txt_telefonoKeyTyped

    private void txt_celularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_celularKeyTyped
        char car = evt.getKeyChar();
        DB_consultas_R_D.validar_numeros(evt, car);
    }//GEN-LAST:event_txt_celularKeyTyped

    public void placeholders() {
        TextPrompt nombre = new TextPrompt("Obligatorio", txt_nombre);
        TextPrompt cedula = new TextPrompt("Obligatorio", txt_cedula);

    }
    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed

        if (txt_nombre.getText().equals("") || txt_cedula.getText().equals("")) {
            txt_cedula.setBackground(Color.PINK);
            txt_nombre.setBackground(Color.PINK);
            JOptionPane.showMessageDialog(this, "Los campos resaltados son obligatorios");
            if (txt_nombre.getText().equals("")) {
                txt_nombre.requestFocus();
            } else {
                txt_cedula.requestFocus();
            }
        } else {

            DBcontactos dbclientes = new DBcontactos();
            Contactos contacto = new Contactos();
            try {
                contacto.setId(Integer.parseInt(txt_id_contacto.getText()));
            } catch (Exception e) {

            }
            contacto.setNombre(txt_nombre.getText());
            contacto.setCedula(txt_cedula.getText());
            contacto.setDireccion(txt_direccion.getText());
            contacto.setCelular(txt_celular.getText());
            contacto.setTelefono(txt_telefono.getText());
            contacto.setEmail(txt_email.getText());
            contacto.setCiudad(txt_ciudad.getText());
            contacto.setObservaciones(jtxa_observaciones.getText());
            contacto.setCupo(Double.parseDouble(metodos.EliminaCaracteres(txt_cupo.getText(), ".")));
            contacto.setInteres(Double.parseDouble(txt_interes.getText()));
            if (chk_empleado.isSelected()) {
                contacto.setEmpleado(1);
            } else {
                contacto.setEmpleado(0);
            }
      
            if (chk_antiguo.isSelected()) {
                contacto.setAntiguo(1);
            } else {
                contacto.setAntiguo(0);
            }

            if (DB_consultas_R_D.consultarId(txt_id_contacto.getText(), "contactos") == 1) {
                dbclientes.Actualizar(contacto);
            } else {
                dbclientes.Guardar(contacto);
            }
            limpiar();
            frm_contactos.btn_actualizar.doClick();
            txt_id_contacto.setText(DB_consultas_R_D.cargarId("contactos"));
            if (chk_cerrar.isSelected()) {
                this.dispose();
            }

        }


    }//GEN-LAST:event_btn_guardarActionPerformed
    public void limpiar() {
        txt_nombre.setText("");
        txt_cedula.setText("");
        txt_direccion.setText("");
        txt_celular.setText("");
        txt_telefono.setText("");
        txt_email.setText("");
        txt_ciudad.setText("");
        jtxa_observaciones.setText("");
        txt_cedula.setBackground(Color.white);
        txt_celular.setBackground(Color.white);
        txt_nombre.setBackground(Color.white);
        txt_direccion.setBackground(Color.white);
        txt_nombre.requestFocus();
    }
    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        txt_nombre.setEditable(true);
        txt_cedula.setEditable(true);
        txt_celular.setEditable(true);
        txt_telefono.setEditable(true);
        txt_ciudad.setEditable(true);
        txt_direccion.setEditable(true);
        txt_email.setEditable(true);
        jtxa_observaciones.setEditable(true);
        btn_guardar.setEnabled(true);
        btn_limpiar.setEnabled(true);
        txt_cupo.setEditable(true);
        chk_cerrar.setEnabled(true);
        chk_empleado.setEnabled(true);
        chk_antiguo.setEnabled(true);
        txt_interes.setEnabled(true);
    }//GEN-LAST:event_btn_editarActionPerformed

    private void txt_cedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cedulaFocusLost
        if (DB_consultas_R_D.consultar_existencia_campo_String("cedula", txt_cedula.getText(), "contactos") == 1) {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "El numero de cédula ingresado ya esta registrado.\n ¿Desea cargar los datos?", "Alerta", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
                ResultSet rs = DB_consultas_R_D.getTabla("select * from contactos where cedula ='" + txt_cedula.getText() + "'");
                try {
                    while (rs.next()) {
                        txt_id_contacto.setText(rs.getString("id"));
                        txt_nombre.setText(rs.getString("nombre"));
                        txt_cedula.setText(rs.getString("cedula"));
                        txt_celular.setText(rs.getString("celular"));
                        txt_telefono.setText(rs.getString("telefono"));
                        txt_direccion.setText(rs.getString("direccion"));
                        txt_email.setText(rs.getString("email"));
                        txt_ciudad.setText(rs.getString("ciudad"));
                        jtxa_observaciones.setText(rs.getString("observaciones"));

                    }
                    rs.close();

                } catch (SQLException ex) {
                    Logger.getLogger(jif_crear_contactos.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                txt_cedula.setText("");
                txt_cedula.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_cedulaFocusLost

    private void txt_cupoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cupoFocusGained
        if (!txt_cupo.getText().equals("")) {
            String texto = metodos.EliminaCaracteres(txt_cupo.getText(), ".");
            txt_cupo.setText(texto);
            txt_cupo.selectAll();
        }
    }//GEN-LAST:event_txt_cupoFocusGained

    private void txt_cupoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cupoFocusLost
        if (!txt_cupo.getText().equals("")) {
            try {
                double to = Double.parseDouble(txt_cupo.getText());
                String nuevo = metodos.formateador_dinero().format(to);
                txt_cupo.setText(nuevo);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Por favor verifique se que halla ingresado un valor correcto");
            }
        }
    }//GEN-LAST:event_txt_cupoFocusLost

    private void txt_cupoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cupoKeyPressed
        char num = evt.getKeyChar();
        if ((num == KeyEvent.VK_ENTER)) {
            btn_guardar.requestFocus();
        }
    }//GEN-LAST:event_txt_cupoKeyPressed

    private void txt_cupoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cupoKeyTyped
        char num = evt.getKeyChar();
        DB_consultas_R_D.validar_numeros(evt, num);
    }//GEN-LAST:event_txt_cupoKeyTyped

    private void txt_interesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_interesFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_interesFocusGained

    private void txt_interesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_interesFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_interesFocusLost

    private void txt_interesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_interesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_interesKeyPressed

    private void txt_interesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_interesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_interesKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_editar;
    public static javax.swing.JButton btn_guardar;
    public static javax.swing.JButton btn_limpiar;
    public static javax.swing.JCheckBox chk_antiguo;
    public static javax.swing.JCheckBox chk_cerrar;
    public static javax.swing.JCheckBox chk_empleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTextArea jtxa_observaciones;
    public static javax.swing.JTextField txt_cedula;
    public static javax.swing.JTextField txt_celular;
    public static javax.swing.JTextField txt_ciudad;
    public static javax.swing.JTextField txt_cupo;
    public static javax.swing.JTextField txt_direccion;
    public static javax.swing.JTextField txt_email;
    public static javax.swing.JTextField txt_id_contacto;
    public static javax.swing.JTextField txt_interes;
    public static javax.swing.JTextField txt_nombre;
    public static javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
