/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ReportesCodigo;

import Metodos.CellRendererBalanceProductos;
import Metodos.metodos;
import com.ezware.oxbow.swingbits.table.filter.TableRowFilterSupport;
import conexiondb.ConsultasSQL;
import conexiondb.DB_consultas_R_D;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import Metodos.ExportarExcel;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.io.IOException;

/**
 *
 * @author Monkeyelgrande
 */
public class jd_Balance_productosEntreFechas extends javax.swing.JDialog {

    /**
     * Creates new form jd_Ventas_diarias
     */
    static DefaultTableModel modeloBalance = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false; //Con esto conseguimos que la tabla no se pueda editar
        }
    };

    DecimalFormat formatea = new DecimalFormat("###,###.##");
    TableColumnModel columnModelBalance = null;
    CellRendererBalanceProductos myRenderer = new CellRendererBalanceProductos();

    public jd_Balance_productosEntreFechas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        metodos.BuscarEnTabla(txt_buscar, jtabla);
        poner_fechas();
        columnModelBalance = jtabla.getColumnModel();
        metodos.addEscapeListenerWindowDialog(this);
        TableRowFilterSupport.forTable(jtabla).searchable(true).apply();
        jtabla.setDefaultRenderer(Object.class, myRenderer);
        btn_consultar.doClick();

        jtabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(MouseEvent me) {
                if (me.getClickCount() == 2) {
                    int fila = jtabla.getSelectedRow();
                    String id = jtabla.getValueAt(fila, 0).toString();
                    String fecha2 = "'"+sdf.format(jdate_fecha2.getDate())+"'";

                    jd_Ver_Balance_Producto frm = new jd_Ver_Balance_Producto(null, true, id, fecha2);

                    frm.lbl_descripcion.setText(jtabla.getValueAt(fila, 2).toString());
                    frm.lbl_codigo.setText(jtabla.getValueAt(fila, 1).toString());
                    frm.lbl_total_bodegas.setText(jtabla.getValueAt(fila, 8).toString());
                    frm.lbl_pendientes_entrega.setText(jtabla.getValueAt(fila, 7).toString());
                    frm.lbl_total_disponibles.setText(jtabla.getValueAt(fila, 6).toString());


                    frm.show();

                }
            }
        }
        );

    }

    public void LimpiarModelos() {
        try {
            for (int i = 0; i < modeloBalance.getRowCount(); i++) {
                modeloBalance.removeRow(i);
                i -= 1;
            }
        } catch (Exception e) {
        }
    }

    public void poner_fechas() {
        try {
            String fecha1 = DB_consultas_R_D.obtener_fecha_dia1();
            Date date1 = new SimpleDateFormat("yyyy-MM-dd").parse(fecha1);
            jdate_fecha1.setDate(date1);

            String fecha2 = DB_consultas_R_D.obtener_fecha_dia_ultimo();
            Date date2 = new SimpleDateFormat("yyyy-MM-dd").parse(fecha2);
            jdate_fecha2.setDate(date2);
        } catch (Exception e) {
        }
    }

    public void TamanosTablaVentas(TableColumnModel cm) {
        cm.getColumn(0).setPreferredWidth(10);
        cm.getColumn(1).setPreferredWidth(40);
        cm.getColumn(2).setPreferredWidth(600);
        cm.getColumn(3).setPreferredWidth(100);
        cm.getColumn(4).setPreferredWidth(100);
        cm.getColumn(5).setPreferredWidth(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpop_1 = new javax.swing.JPopupMenu();
        jmenu_VerFactura1 = new javax.swing.JMenuItem();
        jpop_2 = new javax.swing.JPopupMenu();
        jmenu_2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jdate_fecha1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        btn_consultar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        txt_buscar = new javax.swing.JTextField();
        jdate_fecha2 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jmenu_VerFactura1.setText("Ver factura");
        jpop_1.add(jmenu_VerFactura1);

        jmenu_2.setText("jMenuItem1");
        jpop_2.add(jmenu_2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Balance productos entre fechas");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jdate_fecha1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Fecha inicio:");

        btn_consultar.setBackground(new java.awt.Color(37, 116, 169));
        btn_consultar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_consultar.setForeground(new java.awt.Color(255, 255, 255));
        btn_consultar.setMnemonic('r');
        btn_consultar.setText("Consultar");
        btn_consultar.setToolTipText("ATL+R");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(34, 49, 63));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabla de balance por producto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jtabla.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtabla.setRowHeight(35);
        jtabla.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jtabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jtabla);

        txt_buscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_buscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1216, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jdate_fecha2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Fecha final:");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Exportar a excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdate_fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdate_fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jdate_fecha2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jdate_fecha1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public Date sumarRestarDiasFecha(Date fecha, int dias) {
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(fecha); // Configuramos la fecha que se recibe
        calendar.add(Calendar.DAY_OF_YEAR, dias); // numero de días a añadir, o restar en caso de días<0
        return calendar.getTime(); // Devuelve el objeto Date con los nuevos días añadidos

    }
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        LimpiarModelos();
        String fecha1 = "";
        String fecha2 = "";
        fecha1 = sdf.format(jdate_fecha1.getDate());
        fecha2 = sdf.format(jdate_fecha2.getDate());
        modeloBalance.setColumnIdentifiers(new Object[]{"Id producto", "Código", "Descripción", "Saldo anterior", "Entradas", "Salidas", "Saldo", "Pendiente", "Bodegas"});
        String sql = "with \n"
                + "balance as (\n"
                + "	with ingresos as (\n"
                + "	select i.id_producto, max(p.descripcion) as descripcion, max(p.codigo_barras) as codigo, coalesce(sum(i.cantidad),0) as cantidad \n"
                + "	from ingresos_mercancias_detalle i, ingresos_mercancias_cabecera ic, productos p \n"
                + "	where i.id_ingreso_cabecera=ic.id and i.id_producto=p.id and ic.fecha between '" + fecha1 + "' and '" + fecha2 + "' and ic.estado=1 group by id_producto order by id_producto\n"
                + "	),\n"
                + "	ingresos_anteriores as (\n"
                + "	select i.id_producto, max(p.descripcion) as descripcion, max(p.codigo_barras) as codigo, coalesce(sum(i.cantidad),0) as cantidad \n"
                + "	from ingresos_mercancias_detalle i, ingresos_mercancias_cabecera ic, productos p \n"
                + "	where i.id_ingreso_cabecera=ic.id and i.id_producto=p.id and ic.fecha<'" + fecha1 + "' and ic.estado=1 group by id_producto order by id_producto\n"
                + "	),\n"
                + "	salidas as (\n"
                + "	select id_producto, max(p.descripcion) as descripcion, max(p.codigo_barras) as codigo, coalesce(sum(fd.cantidad),0) as cantidad \n"
                + "	from facturas_detalles as fd, facturas_cabeceras fc, productos p \n"
                + "	where fd.id_cabecera=fc.id and fd.id_producto=p.id and fc.fecha between '" + fecha1 + "' and '" + fecha2 + "' and fc.anulado=1 group by id_producto\n"
                + "	),\n"
                + "	salidas_anteriores as (\n"
                + "	select id_producto, max(p.descripcion) as descripcion, max(p.codigo_barras) as codigo, coalesce(sum(fd.cantidad),0) as cantidad \n"
                + "	from facturas_detalles as fd, facturas_cabeceras fc, productos p \n"
                + "	where fd.id_cabecera=fc.id and fd.id_producto=p.id and fc.fecha<'" + fecha1 + "' and fc.anulado=1 group by id_producto\n"
                + "	)\n"
                + "\n"
                + "	select \n"
                + "	coalesce(i.id_producto,ia.id_producto,s.id_producto,sa.id_producto) as id_producto, \n"
                + "	coalesce(i.codigo,ia.codigo,s.codigo,sa.codigo) as codigo, \n"
                + "	coalesce(i.descripcion,ia.descripcion,s.descripcion,sa.descripcion) as descripcion, \n"
                + "	sum(coalesce(ia.cantidad,0) - coalesce(sa.cantidad,0)) as saldo_anterior,\n"
                + "	sum(coalesce(i.cantidad,0)) as ingresos, sum(coalesce(s.cantidad,0)) as salidas,\n"
                + "	sum((coalesce(ia.cantidad,0) - coalesce(sa.cantidad,0)) + coalesce(i.cantidad,0) - coalesce(s.cantidad,0)) as saldo\n"
                + "\n"
                + "	from \n"
                + "\n"
                + "	ingresos as i\n"
                + "	full outer join ingresos_anteriores as ia on i.id_producto=ia.id_producto\n"
                + "	full outer join salidas as s on s.id_producto=i.id_producto \n"
                + "	full outer join salidas_anteriores as sa on sa.id_producto=ia.id_producto \n"
                + "	group by coalesce(i.id_producto,ia.id_producto,s.id_producto,sa.id_producto), coalesce(i.codigo,ia.codigo,s.codigo,sa.codigo),coalesce(i.descripcion,ia.descripcion,s.descripcion,sa.descripcion)\n"
                + "	order by coalesce(i.descripcion,ia.descripcion,s.descripcion,sa.descripcion)\n"
                + "),\n"
                + "pendiente as (\n"
                + "\n"
                + "	with fac_det as (\n"
                + "		select f.id_producto, coalesce(sum(f.cantidad),0) as cantidad \n"
                + "		from facturas_detalles f\n"
                + "		group by f.id_producto\n"
                + "	), \n"
                + "	entregas as (\n"
                + "		select e.id_producto, coalesce(sum(e.cantidad),0) as cantidad \n"
                + "		from entregas_productos e\n"
                + "		group by e.id_producto\n"
                + "	)\n"
                + "\n"
                + "	select f.id_producto, (f.cantidad-e.cantidad) as pendiente\n"
                + "	from fac_det f left join entregas e on f.id_producto=e.id_producto\n"
                + "	group by f.id_producto, f.cantidad, e.cantidad\n"
                + "	order by f.id_producto\n"
                + ")\n"
                + "\n"
                + "select b.*, coalesce(p.pendiente,0) as pendiente, coalesce((b.saldo+coalesce(p.pendiente,0)),0) as bodega from balance b LEFT JOIN pendiente p on b.id_producto=p.id_producto;";
        System.out.println(sql);
        ResultSet rs = DB_consultas_R_D.getTabla(sql);
        try {
            fecha1 = sdf.format(jdate_fecha1.getDate());

            try {
                while (rs.next()) {

                    modeloBalance.addRow(new Object[]{rs.getString("id_producto"), rs.getString("codigo"), rs.getString("descripcion"),
                        formatea.format(rs.getDouble("saldo_anterior")), formatea.format(rs.getDouble("ingresos")),
                        formatea.format(rs.getDouble("salidas")), formatea.format(rs.getDouble("saldo")),
                        formatea.format(rs.getDouble("pendiente")), formatea.format(rs.getDouble("bodega"))});
                }
                rs.close();
                // asigna el modelo a la tabla
                jtabla.setModel(modeloBalance);
                TamanosTablaVentas(columnModelBalance);
            } catch (Exception e) {
                System.out.println(e);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Verifique las fechas", "Alerta", WIDTH);
        }
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ExportarExcel obj;

        try {
            obj = new ExportarExcel();
            obj.exportarExcel(jtabla);
        } catch (IOException ex) {
            System.out.println("" + ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_buscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarKeyPressed

    private void txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jd_Balance_productosEntreFechas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jd_Balance_productosEntreFechas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jd_Balance_productosEntreFechas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jd_Balance_productosEntreFechas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jd_Balance_productosEntreFechas dialog = new jd_Balance_productosEntreFechas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdate_fecha1;
    private com.toedter.calendar.JDateChooser jdate_fecha2;
    private javax.swing.JMenuItem jmenu_2;
    private javax.swing.JMenuItem jmenu_VerFactura1;
    private javax.swing.JPopupMenu jpop_1;
    private javax.swing.JPopupMenu jpop_2;
    private javax.swing.JTable jtabla;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
