/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ReportesCodigo;

import Metodos.CellRendererBalanceProductos;
import Metodos.ExportarExcel;
import Metodos.metodos;
import com.ezware.oxbow.swingbits.table.filter.TableRowFilterSupport;
import conexiondb.ConsultasSQL;
import conexiondb.DB_consultas_R_D;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import modelos.BuscarTablaLikeSQL;
import modelos.Facturas_cabeceras;

/**
 *
 * @author Monkeyelgrande
 */
public class jd_productos_pendientes_de_entrega extends javax.swing.JDialog {

    /**
     * Creates new form jd_Ventas_diarias
     */
    static DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false; //Con esto conseguimos que la tabla no se pueda editar
        }
    };

    DecimalFormat formatea = new DecimalFormat("###,###.##");
    TableColumnModel columnModelBalance = null;
    CellRendererBalanceProductos myRenderer = new CellRendererBalanceProductos();

    public jd_productos_pendientes_de_entrega(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        poner_fechas();
        columnModelBalance = jtabla.getColumnModel();
        metodos.addEscapeListenerWindowDialog(this);
        TableRowFilterSupport.forTable(jtabla).searchable(true).apply();
        jtabla.setDefaultRenderer(Object.class, myRenderer);

        jtabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(MouseEvent me) {
                if (me.getClickCount() == 2) {
                    Facturas_cabeceras f = new Facturas_cabeceras();
                    f.cargar_facturas(jtabla, "ver");
                }
            }
        });
        metodos.BuscarEnTabla(txt_buscar, jtabla);
        btn_consultar.doClick();
    }

    public void LimpiarModelos() {
        try {
            for (int i = 0; i < jtabla.getRowCount(); i++) {
                modelo.removeRow(i);
                i -= 1;
            }
        } catch (Exception e) {
        }
    }

    public void poner_fechas() {

        try {
            Calendar fecha = new GregorianCalendar();
            jdate_fecha1.setCalendar(fecha);

        } catch (Exception e) {
        }
    }

    public void TamanosTablaVentas(TableColumnModel cm) {
        cm.getColumn(0).setPreferredWidth(50);
        cm.getColumn(1).setPreferredWidth(50);
        cm.getColumn(2).setPreferredWidth(50);
        cm.getColumn(3).setPreferredWidth(450);
        cm.getColumn(4).setPreferredWidth(100);
        cm.getColumn(5).setPreferredWidth(80);
        cm.getColumn(6).setPreferredWidth(80);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpop_1 = new javax.swing.JPopupMenu();
        jmenu_VerFactura1 = new javax.swing.JMenuItem();
        jpop_2 = new javax.swing.JPopupMenu();
        jmenu_2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        btn_consultar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        txt_buscar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lbl_total_salida = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_total_entregadas = new javax.swing.JLabel();
        lbl_total_pendientes = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jdate_fecha1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();

        jmenu_VerFactura1.setText("Ver factura");
        jpop_1.add(jmenu_VerFactura1);

        jmenu_2.setText("jMenuItem1");
        jpop_2.add(jmenu_2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Productos pendientes de entrega");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_consultar.setBackground(new java.awt.Color(37, 116, 169));
        btn_consultar.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btn_consultar.setForeground(new java.awt.Color(255, 255, 255));
        btn_consultar.setMnemonic('r');
        btn_consultar.setText("Consultar");
        btn_consultar.setToolTipText("ATL+R");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(34, 49, 63));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabla de balance por producto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jtabla.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtabla.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jtabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jtabla);

        txt_buscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_buscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total salida:");

        lbl_total_salida.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_total_salida.setForeground(new java.awt.Color(255, 255, 255));
        lbl_total_salida.setText("0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 153));
        jLabel6.setText("Total entregadas:");

        lbl_total_entregadas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_total_entregadas.setForeground(new java.awt.Color(153, 255, 153));
        lbl_total_entregadas.setText("0");

        lbl_total_pendientes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_total_pendientes.setForeground(new java.awt.Color(255, 102, 102));
        lbl_total_pendientes.setText("0");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("Total pendientes:");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Exportar a excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1214, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_total_salida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_total_entregadas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_total_pendientes))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbl_total_salida)
                    .addComponent(jLabel6)
                    .addComponent(lbl_total_entregadas)
                    .addComponent(jLabel7)
                    .addComponent(lbl_total_pendientes)))
        );

        jdate_fecha1.setEnabled(false);
        jdate_fecha1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Fecha:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdate_fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jdate_fecha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btn_consultar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void calcular_total() {
        double total_salida = 0, total_entregado = 0, total_pendiente = 0;
        for (int i = 0; i < jtabla.getRowCount(); i++) {
            total_salida += Double.parseDouble(metodos.ReemplazarCaracteres(metodos.EliminaCaracteres(jtabla.getValueAt(i, 5).toString(), "."), ",", "."));
            total_entregado += Double.parseDouble(metodos.ReemplazarCaracteres(metodos.EliminaCaracteres(jtabla.getValueAt(i, 6).toString(), "."), ",", "."));
            total_pendiente += Double.parseDouble(metodos.ReemplazarCaracteres(metodos.EliminaCaracteres(jtabla.getValueAt(i, 7).toString(), "."), ",", "."));
        }
        lbl_total_salida.setText(formatea.format(total_salida) + "");
        lbl_total_entregadas.setText(formatea.format(total_entregado) + "");
        lbl_total_pendientes.setText(formatea.format(total_pendiente) + "");
    }


    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        LimpiarModelos();
        String fecha1 = "";
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        fecha1 = sdf.format(jdate_fecha1.getDate());
        SimpleDateFormat sdf2 = new SimpleDateFormat("dd-MMM-yyyy");
        modelo.setColumnIdentifiers(new Object[]{"Id Factura", "Codigo", "Fecha", "Descripción", "Cliente", "Cantidad", "Entregadas", "Pendiente de entrega"});
        String consulta = "WITH consulta AS (\n"
                + "    WITH salidas AS (\n"
                + "        SELECT \n"
                + "            id_cabecera AS id_cabecera, \n"
                + "            id_producto, \n"
                + "            SUM(cantidad) AS cantidad \n"
                + "        FROM \n"
                + "            facturas_detalles fd join facturas_cabeceras fc on fd.id_cabecera=fc.id\n"
                + "        WHERE \n"
                + "            fd.id IN (\n"
                + "                SELECT \n"
                + "                    id \n"
                + "                FROM \n"
                + "                    facturas_detalles fd \n"
                + "                WHERE \n"
                + "                    id_cabecera NOT IN (\n"
                + "                        SELECT \n"
                + "                            id_factura \n"
                + "                        FROM \n"
                + "                            facturas_detalles \n"
                + "                        WHERE \n"
                + "                            id_factura IS NOT NULL\n"
                + "                    )\n"
                + "                ORDER BY \n"
                + "                    id\n"
                + "            )\n"
                + "            and fc.tipo_factura in ('Salida', 'Prestamo','Eliminación')\n"
                + "        GROUP BY \n"
                + "            id_cabecera, \n"
                + "            id_producto\n"
                + "        ORDER BY \n"
                + "            id_cabecera, \n"
                + "            id_producto\n"
                + "    ),\n"
                + "    entregas AS (\n"
                + "        SELECT \n"
                + "            id_factura AS id_cabecera, \n"
                + "            id_producto, \n"
                + "            SUM(cantidad) AS cantidad \n"
                + "        FROM \n"
                + "            entregas_productos e\n"
                + "        GROUP BY \n"
                + "            id_factura, \n"
                + "            id_producto\n"
                + "        ORDER BY \n"
                + "            id_factura, \n"
                + "            id_producto\n"
                + "    )\n"
                + "    SELECT \n"
                + "        coalesce(s.id_cabecera, e.id_cabecera) as id_cabecera, \n"
                + "        coalesce(s.id_producto, e.id_producto) as id_producto,\n"
                + "        coalesce(SUM(s.cantidad),0) AS cantidad_salida, \n"
                + "        COALESCE(SUM(e.cantidad), 0) AS cantidad_entrega,\n"
                + "        (coalesce(SUM(s.cantidad),0) - COALESCE(SUM(e.cantidad), 0)) AS pendiente\n"
                + "    FROM \n"
                + "        salidas s \n"
                + "    LEFT JOIN \n"
                + "        entregas e \n"
                + "        ON s.id_cabecera = e.id_cabecera AND s.id_producto = e.id_producto\n"
                + "    GROUP BY \n"
                + "        s.id_cabecera, e.id_cabecera,\n"
                + "        s.id_producto, e.id_producto\n"
                + ")\n"
                + "SELECT \n"
                + "    co.id_cabecera, \n"
                + "    fc.codigo, \n"
                + "    fc.fecha, \n"
                + "    p.descripcion, \n"
                + "    p.codigo_barras, \n"
                + "    c.nombre AS cliente, \n"
                + "    co.cantidad_salida AS cantidad, \n"
                + "    co.cantidad_entrega AS entrega, \n"
                + "    TRUNC(co.pendiente::numeric, 1) as pendiente\n"
                + "\n"
                + "FROM \n"
                + "    consulta co\n"
                + "INNER JOIN \n"
                + "    productos p \n"
                + "    ON co.id_producto = p.id\n"
                + "INNER JOIN \n"
                + "    facturas_cabeceras fc \n"
                + "    ON co.id_cabecera = fc.id\n"
                + "INNER JOIN \n"
                + "    contactos c \n"
                + "    ON fc.id_contacto = c.id\n"
                + "WHERE \n"
                + "    co.pendiente > 0 \n"
                + "    AND fc.anulado = 1\n"
                + "    and TRUNC(co.pendiente::numeric, 1) > 0.0\n"
                + "\n"
                + "ORDER BY \n"
                + "    co.id_cabecera;";

        System.out.println(consulta);
        ResultSet rs = DB_consultas_R_D.getTabla(consulta);
        try {

            try {
                while (rs.next()) {

                    modelo.addRow(new Object[]{rs.getString("id_cabecera"), rs.getString("codigo"), rs.getDate("fecha"), 
                        rs.getString("descripcion") + " / " + rs.getString("codigo_barras"), rs.getString("cliente"),
                        formatea.format(rs.getDouble("cantidad")), formatea.format(rs.getDouble("entrega")), formatea.format(rs.getDouble("pendiente"))});
                }
                rs.close();
                // asigna el modelo a la tabla
                jtabla.setModel(modelo);
                TamanosTablaVentas(columnModelBalance);
                calcular_total();
            } catch (Exception e) {
                System.out.println(e);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Verifique las fechas", "Alerta", WIDTH);
        }

    }//GEN-LAST:event_btn_consultarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ExportarExcel obj;

        try {
            obj = new ExportarExcel();
            obj.exportarExcel(jtabla);
        } catch (IOException ex) {
            System.out.println("" + ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyReleased

    }//GEN-LAST:event_txt_buscarKeyReleased

    private void txt_buscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyPressed
        char num = evt.getKeyChar();
        if ((num == KeyEvent.VK_ENTER)) {
            calcular_total();
        }
    }//GEN-LAST:event_txt_buscarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jd_productos_pendientes_de_entrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jd_productos_pendientes_de_entrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jd_productos_pendientes_de_entrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jd_productos_pendientes_de_entrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                jd_productos_pendientes_de_entrega dialog = new jd_productos_pendientes_de_entrega(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdate_fecha1;
    private javax.swing.JMenuItem jmenu_2;
    private javax.swing.JMenuItem jmenu_VerFactura1;
    private javax.swing.JPopupMenu jpop_1;
    private javax.swing.JPopupMenu jpop_2;
    private javax.swing.JTable jtabla;
    private javax.swing.JLabel lbl_total_entregadas;
    private javax.swing.JLabel lbl_total_pendientes;
    private javax.swing.JLabel lbl_total_salida;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
