/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ReportesCodigo;

import Formularios.frm_ver_orden;
import JDBuscar.jd_buscar_salida_producto_reporte;
import Metodos.ExportarExcel;
import Metodos.metodos;
import conexiondb.ConsultasSQL;
import conexiondb.DB_consultas_R_D;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import modelos.Facturas_cabeceras;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Monkeyelgrande
 */
public class jd_Salida_productos_entre_fechas_XProducto extends javax.swing.JDialog {

    /**
     * Creates new form jd_Ventas_diarias
     */
    static DefaultTableModel modelo1 = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false; //Con esto conseguimos que la tabla no se pueda editar
        }
    };

    DecimalFormat formatea = new DecimalFormat("###,###.##");
    frm_ver_orden frm = new frm_ver_orden();
    TableColumnModel columnModelIngresos = null;

    public jd_Salida_productos_entre_fechas_XProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        metodos.EstiloTablaMaterialGlobal(jtabla_ingresos);
        columnModelIngresos = jtabla_ingresos.getColumnModel();
        this.setLocationRelativeTo(parent);
        poner_fechas();
        metodos.addEscapeListenerWindowDialog(this);
        doble_clic_tablas();
        
    }

    public void poner_fechas() {
        try {
            String fecha1 = DB_consultas_R_D.obtener_fecha_dia1();
            Date date1 = new SimpleDateFormat("yyyy-MM-dd").parse(fecha1);
            jdate_fecha1.setDate(date1);

            String fecha2 = DB_consultas_R_D.obtener_fecha_dia_ultimo();
            Date date2 = new SimpleDateFormat("yyyy-MM-dd").parse(fecha2);
            jdate_fecha2.setDate(date2);
        } catch (Exception e) {
        }
    }

    public void TamanosTablaVentas(TableColumnModel cm) {
        cm.getColumn(0).setPreferredWidth(15);
        cm.getColumn(1).setPreferredWidth(75);
        cm.getColumn(2).setPreferredWidth(250);
        cm.getColumn(3).setPreferredWidth(80);
        cm.getColumn(4).setPreferredWidth(80);
    }

    public void doble_clic_tablas() {
        jtabla_ingresos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(MouseEvent me) {
                if (me.getClickCount() == 2) {
                    Facturas_cabeceras f = new Facturas_cabeceras();
                    f.cargar_facturas(jtabla_ingresos, "ver");
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpop_1 = new javax.swing.JPopupMenu();
        jmenu_VerFactura1 = new javax.swing.JMenuItem();
        jpop_2 = new javax.swing.JPopupMenu();
        jmenu_2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jdate_fecha1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        btn_consultar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla_ingresos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        lbl_total_salida = new javax.swing.JLabel();
        jdate_fecha2 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        btn_imprimir_oi = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_cod_barras = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbl_descripcion = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_id_producto = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jmenu_VerFactura1.setText("Ver factura");
        jpop_1.add(jmenu_VerFactura1);

        jmenu_2.setText("jMenuItem1");
        jpop_2.add(jmenu_2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Salida productos entre fechas por producto");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jdate_fecha1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Fecha inicio:");

        btn_consultar.setBackground(new java.awt.Color(37, 116, 169));
        btn_consultar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_consultar.setForeground(new java.awt.Color(255, 255, 255));
        btn_consultar.setMnemonic('r');
        btn_consultar.setText("Consultar");
        btn_consultar.setToolTipText("ATL+R");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(34, 49, 63));

        jtabla_ingresos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtabla_ingresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtabla_ingresos.setComponentPopupMenu(jpop_1);
        jtabla_ingresos.setRowHeight(22);
        jtabla_ingresos.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jtabla_ingresos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jtabla_ingresos);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total salida:");

        lbl_total_salida.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_total_salida.setForeground(new java.awt.Color(255, 255, 255));
        lbl_total_salida.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1367, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_total_salida)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbl_total_salida))
                .addContainerGap())
        );

        jdate_fecha2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Fecha fin:");

        btn_imprimir_oi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/print_pequeno.png"))); // NOI18N
        btn_imprimir_oi.setMnemonic('p');
        btn_imprimir_oi.setToolTipText("ATL+P");
        btn_imprimir_oi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimir_oiActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Codigo de barras");

        txt_cod_barras.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_cod_barras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cod_barrasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cod_barrasFocusLost(evt);
            }
        });
        txt_cod_barras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cod_barrasKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Descripción");

        lbl_descripcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_descripcion.setText("Descripción");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("id");

        lbl_id_producto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btn_buscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_buscar.setMnemonic('b');
        btn_buscar.setText("Buscar");
        btn_buscar.setToolTipText("ALT+B");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Exportar a excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_id_producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_cod_barras, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_buscar))
                            .addComponent(lbl_descripcion))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_cod_barras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_buscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lbl_descripcion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lbl_id_producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdate_fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdate_fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_imprimir_oi)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_imprimir_oi)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdate_fecha2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdate_fecha1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_imprimir_oiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimir_oiActionPerformed
        if (lbl_id_producto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No ha cargado un producto");
        } else {
            String cad = metodos.TamanoHoja("/src/reportes/SalidaProductosXProducto_carta.jrxml", "/src/reportes/SalidaProductosXProducto_oficio.jrxml");
            if (!cad.equals("")) {
                Connection cn = DB_consultas_R_D.getConexion();
                JasperReport report = null;
                Map p = new HashMap();
                try {
                    p.put("fecha1", jdate_fecha1.getDate());
                    p.put("fecha2", jdate_fecha2.getDate());
                    p.put("codigo", Integer.parseInt(lbl_id_producto.getText()));
                    p.put("SUBREPORT_DIR", new File("").getAbsolutePath() + "/src/reportes/");

                    try {
                        try {
                            report = JasperCompileManager.compileReport(cad);
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(this, e);
                        }
                        JasperPrint print = JasperFillManager.fillReport(report, p, cn);
                        JasperViewer view = new JasperViewer(print, false);
                        cn.close();
                        JDialog dialog = new JDialog(this);//the owner
                        dialog.setContentPane(view.getContentPane());
                        dialog.setSize(view.getSize());
                        dialog.setModal(true);
                        dialog.setLocationRelativeTo(this);
                        dialog.setTitle("Reporte de otros ingresos por contacto");
                        dialog.setVisible(true);

                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Verifique las fechas", "Alerta", WIDTH);
                }
            }
        }
    }//GEN-LAST:event_btn_imprimir_oiActionPerformed

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        if (txt_cod_barras.getText().isEmpty() || lbl_id_producto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Cargue un producto");
            txt_cod_barras.requestFocus();
        } else {
            LimpiarModelos();
            String fecha1 = "";
            String fecha2 = "";
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat sdf2 = new SimpleDateFormat("dd-MMM-yyyy");
            try {
                fecha1 = sdf.format(jdate_fecha1.getDate());
                fecha2 = sdf.format(jdate_fecha2.getDate());

                String sql
                        = "WITH ventas_referenciadas AS ( \n"
                        + "    SELECT DISTINCT \n"
                        + "        fd_ref.id_factura AS id_factura_venta, \n"
                        + "        fc_ref.id        AS id_orden_referencia \n"
                        + "    FROM facturas_detalles fd_ref \n"
                        + "    JOIN facturas_cabeceras fc_ref ON fd_ref.id_cabecera = fc_ref.id \n"
                        + "    WHERE fc_ref.tipo_factura <> 'Venta' \n"
                        + "      AND fd_ref.id_factura > 0 \n" // solo órdenes que referencian una venta
                        + "      AND fd_ref.id_producto = " + lbl_id_producto.getText() + " \n"
                        + "), \n"
                        + "facturado_por_orden AS ( \n"
                        + "    SELECT \n"
                        + "        fc.id AS id_orden, \n"
                        + "        SUM(fd.cantidad) AS qty_facturada \n"
                        + "    FROM facturas_detalles fd \n"
                        + "    JOIN facturas_cabeceras fc ON fd.id_cabecera = fc.id \n"
                        + "    WHERE fc.tipo_factura IN ('Salida','Prestamo','Eliminacion') \n"
                        + "      AND fc.anulado = 1 \n"
                        + "      AND fd.id_producto = " + lbl_id_producto.getText() + " \n"
                        + "    GROUP BY fc.id \n"
                        + "), \n"
                        + "entregado_por_orden AS ( \n"
                        + "    SELECT \n"
                        + "        fc.id AS id_orden, \n"
                        + "        SUM(ep.cantidad) AS qty_entregada \n"
                        + "    FROM entregas_productos ep \n"
                        + "    JOIN entregas_productos_cabecera epc ON ep.id_cabecera = epc.id \n"
                        + "    JOIN facturas_cabeceras fc ON epc.id_factura = fc.id \n"
                        + "    WHERE fc.tipo_factura IN ('Salida','Prestamo','Eliminacion') \n"
                        + "      AND fc.anulado = 1 \n"
                        + "      AND ep.id_producto = " + lbl_id_producto.getText() + " \n"
                        + "    GROUP BY fc.id \n"
                        + "), \n"
                        + "pendientes_por_orden AS ( \n"
                        + "    SELECT \n"
                        + "        f.id_orden, \n"
                        + "        GREATEST(f.qty_facturada - COALESCE(e.qty_entregada, 0), 0) AS pendiente \n"
                        + "    FROM facturado_por_orden f \n"
                        + "    LEFT JOIN entregado_por_orden e ON e.id_orden = f.id_orden \n"
                        + ") \n"
                        + "SELECT \n"
                        + "    fc.id         AS id_factura, \n"
                        + "    fc.fecha, \n"
                        + "    c.nombre      AS contacto, \n"
                        + "    fd.cantidad, \n"
                        + "    fc.codigo, \n"
                        + "    fc.tipo_factura, \n"
                        + "    CASE \n"
                        + "        WHEN fc.tipo_factura = 'Venta' \n"
                        + "             AND vr.id_factura_venta IS NOT NULL THEN \n"
                        + "            'Ref: ' || vr.id_orden_referencia \n"
                        + "        WHEN fc.tipo_factura = 'Venta' THEN '0' \n"
                        + "        WHEN fc.tipo_factura IN ('Salida','Prestamo','Eliminacion') THEN \n"
                        + "            COALESCE(po.pendiente::text, '0') \n"
                        + "        ELSE '0' \n"
                        + "    END AS pendiente \n"
                        + "FROM facturas_detalles fd \n"
                        + "JOIN facturas_cabeceras fc ON fd.id_cabecera = fc.id \n"
                        + "JOIN productos prod        ON fd.id_producto = prod.id \n"
                        + "JOIN contactos c           ON fc.id_contacto = c.id \n"
                        + "LEFT JOIN ventas_referenciadas vr ON vr.id_factura_venta = fc.id \n"
                        + "LEFT JOIN pendientes_por_orden po ON po.id_orden = fc.id \n"
                        + "WHERE fd.id_producto = " + lbl_id_producto.getText() + " \n"
//                        + "  AND fd.id_factura = 0 \n"
                        + "  AND fc.fecha BETWEEN '" + fecha1 + "' AND '" + fecha2 + "' \n"
                        + "  AND fc.anulado = 1 \n"
                        + "ORDER BY fc.fecha, fc.id";
                System.out.println(sql);
                ResultSet rs = DB_consultas_R_D.getTabla(sql);

                modelo1.setColumnIdentifiers(
                        new Object[]{"Id factura", "Código", "contacto", "Fecha", "Cantidad", "Tipo", "Pendiente"}
                );

                try {
                    while (rs.next()) {
                        modelo1.addRow(new Object[]{
                            rs.getString("id_factura"),
                            rs.getString("codigo"),
                            rs.getString("contacto"),
                            sdf2.format(rs.getDate("fecha")),
                            rs.getString("cantidad"),
                            rs.getString("tipo_factura"),
                            rs.getString("pendiente") // Nueva columna
                        });
                    }
                    rs.close();
                    jtabla_ingresos.setModel(modelo1);
                    TamanosTablaVentas(columnModelIngresos);
                } catch (Exception e) {
                    System.out.println(e);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Verifique las fechas", "Alerta", WIDTH);
            }

            calcular_total();

        }
    }//GEN-LAST:event_btn_consultarActionPerformed
    public void calcular_total() {
        double total = 0;
        for (int i = 0; i < this.jtabla_ingresos.getRowCount(); i++) {
            
            total += Double.parseDouble(metodos.EliminaCaracteres(this.jtabla_ingresos.getValueAt(i, 4).toString(), "."));
        }
        
        lbl_total_salida.setText(formatea.format(total) + "");
    }
    private void txt_cod_barrasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cod_barrasFocusLost

    }//GEN-LAST:event_txt_cod_barrasFocusLost

    private void txt_cod_barrasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cod_barrasKeyPressed
        char num = evt.getKeyChar();
        if ((num == KeyEvent.VK_ENTER)) {
            consulta_producto_cod_barras();
        }
    }//GEN-LAST:event_txt_cod_barrasKeyPressed
    private void consulta_producto_cod_barras() {
        if (txt_cod_barras.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese un codigo de barras");
        } else {
            if (DB_consultas_R_D.consultar_existencia_campo_String("codigo_barras", txt_cod_barras.getText(), "productos") == 1) {
                String codigo = txt_cod_barras.getText();
                ResultSet rs = DB_consultas_R_D.getTabla("select id,codigo_barras,descripcion from productos where codigo_barras ='" + codigo + "'");

                try {
                    while (rs.next()) {
                        lbl_id_producto.setText(rs.getString("id"));
                        lbl_descripcion.setText(rs.getString("descripcion"));

                    }
                    rs.close();
                } catch (SQLException ex) {
                    Logger.getLogger(jd_Salida_productos_entre_fechas_XProducto.class.getName()).log(Level.SEVERE, null, ex);
                }
                btn_consultar.requestFocus();

            }

        }
    }
    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        jd_buscar_salida_producto_reporte buscar_producto = new jd_buscar_salida_producto_reporte(null, rootPaneCheckingEnabled);
        buscar_producto.show();
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void txt_cod_barrasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cod_barrasFocusGained
        txt_cod_barras.selectAll();
    }//GEN-LAST:event_txt_cod_barrasFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ExportarExcel obj;

        try {
            obj = new ExportarExcel();
            obj.exportarExcel(jtabla_ingresos);
        } catch (IOException ex) {
            System.out.println("" + ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public void LimpiarModelos() {
        try {
            for (int i = 0; i < jtabla_ingresos.getRowCount(); i++) {
                modelo1.removeRow(i);
                i -= 1;
            }
        } catch (Exception e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jd_Salida_productos_entre_fechas_XProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jd_Salida_productos_entre_fechas_XProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jd_Salida_productos_entre_fechas_XProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jd_Salida_productos_entre_fechas_XProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jd_Salida_productos_entre_fechas_XProducto dialog = new jd_Salida_productos_entre_fechas_XProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_buscar;
    public static javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_imprimir_oi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdate_fecha1;
    private com.toedter.calendar.JDateChooser jdate_fecha2;
    private javax.swing.JMenuItem jmenu_2;
    private javax.swing.JMenuItem jmenu_VerFactura1;
    private javax.swing.JPopupMenu jpop_1;
    private javax.swing.JPopupMenu jpop_2;
    private javax.swing.JTable jtabla_ingresos;
    public static javax.swing.JLabel lbl_descripcion;
    public static javax.swing.JLabel lbl_id_producto;
    private javax.swing.JLabel lbl_total_salida;
    public static javax.swing.JTextField txt_cod_barras;
    // End of variables declaration//GEN-END:variables
}
