/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ReportesCodigo;

import Formularios.frm_main;
import java.awt.Dimension;

/**
 *
 * @author Monkeyelgrande
 */
public class jif_PrincipalReportes extends javax.swing.JInternalFrame {

    /**
     * Creates new form jif_PrincipalReportes
     */
    public jif_PrincipalReportes() {
        initComponents();
        Dimension desktopSize = frm_main.escritorio.getSize();
        Dimension FrameSize = this.getSize();
        this.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btn_Ingresosdiarios1 = new javax.swing.JButton();
        btn_IngresosBetwin2 = new javax.swing.JButton();
        btn_Ingresos_entre_fechas_por_producto = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btn_Ingresosdiarios2 = new javax.swing.JButton();
        btn_IngresosBetwin3 = new javax.swing.JButton();
        btn_IngresosBetwin5 = new javax.swing.JButton();
        btn_IngresosBetwin6 = new javax.swing.JButton();
        btn_IngresosBetwin8 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btn_IngresosBetwin7 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btn_Ingresosdiarios3 = new javax.swing.JButton();
        btn_ordenes_entre_fechas = new javax.swing.JButton();
        btn_ordenes_entre_fechas1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Reportes");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingresos Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btn_Ingresosdiarios1.setBackground(new java.awt.Color(78, 205, 196));
        btn_Ingresosdiarios1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Ingresosdiarios1.setText("Ingresos diarios");
        btn_Ingresosdiarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Ingresosdiarios1ActionPerformed(evt);
            }
        });

        btn_IngresosBetwin2.setBackground(new java.awt.Color(78, 205, 196));
        btn_IngresosBetwin2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_IngresosBetwin2.setText("Ingresos entre fechas");
        btn_IngresosBetwin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresosBetwin2ActionPerformed(evt);
            }
        });

        btn_Ingresos_entre_fechas_por_producto.setBackground(new java.awt.Color(78, 205, 196));
        btn_Ingresos_entre_fechas_por_producto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Ingresos_entre_fechas_por_producto.setText("Ingresos entre fechas por producto");
        btn_Ingresos_entre_fechas_por_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Ingresos_entre_fechas_por_productoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btn_Ingresosdiarios1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(392, 392, 392))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btn_IngresosBetwin2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btn_Ingresos_entre_fechas_por_producto)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Ingresosdiarios1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_IngresosBetwin2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Ingresos_entre_fechas_por_producto)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Salida Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btn_Ingresosdiarios2.setBackground(new java.awt.Color(236, 100, 75));
        btn_Ingresosdiarios2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Ingresosdiarios2.setForeground(new java.awt.Color(255, 255, 255));
        btn_Ingresosdiarios2.setText("Salidas diarios");
        btn_Ingresosdiarios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Ingresosdiarios2ActionPerformed(evt);
            }
        });

        btn_IngresosBetwin3.setBackground(new java.awt.Color(236, 100, 75));
        btn_IngresosBetwin3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_IngresosBetwin3.setForeground(new java.awt.Color(255, 255, 255));
        btn_IngresosBetwin3.setText("Salidas entre fechas");
        btn_IngresosBetwin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresosBetwin3ActionPerformed(evt);
            }
        });

        btn_IngresosBetwin5.setBackground(new java.awt.Color(236, 100, 75));
        btn_IngresosBetwin5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_IngresosBetwin5.setForeground(new java.awt.Color(255, 255, 255));
        btn_IngresosBetwin5.setText("Salidas entre fechas por producto");
        btn_IngresosBetwin5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresosBetwin5ActionPerformed(evt);
            }
        });

        btn_IngresosBetwin6.setBackground(new java.awt.Color(236, 100, 75));
        btn_IngresosBetwin6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_IngresosBetwin6.setForeground(new java.awt.Color(255, 255, 255));
        btn_IngresosBetwin6.setText("Productos pendientes de entrega");
        btn_IngresosBetwin6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresosBetwin6ActionPerformed(evt);
            }
        });

        btn_IngresosBetwin8.setBackground(new java.awt.Color(236, 100, 75));
        btn_IngresosBetwin8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_IngresosBetwin8.setForeground(new java.awt.Color(255, 255, 255));
        btn_IngresosBetwin8.setText("Productos entregados");
        btn_IngresosBetwin8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresosBetwin8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btn_Ingresosdiarios2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(392, 392, 392))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btn_IngresosBetwin3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_IngresosBetwin5)
                            .addComponent(btn_IngresosBetwin6)
                            .addComponent(btn_IngresosBetwin8))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Ingresosdiarios2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_IngresosBetwin3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_IngresosBetwin5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_IngresosBetwin6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_IngresosBetwin8)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Balance productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btn_IngresosBetwin7.setBackground(new java.awt.Color(255, 255, 0));
        btn_IngresosBetwin7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_IngresosBetwin7.setText("Balance entre fechas");
        btn_IngresosBetwin7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresosBetwin7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_IngresosBetwin7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_IngresosBetwin7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_Ingresosdiarios3.setBackground(new java.awt.Color(78, 205, 196));
        btn_Ingresosdiarios3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Ingresosdiarios3.setText("Productos mas vendidos");
        btn_Ingresosdiarios3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Ingresosdiarios3ActionPerformed(evt);
            }
        });

        btn_ordenes_entre_fechas.setBackground(new java.awt.Color(78, 205, 196));
        btn_ordenes_entre_fechas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_ordenes_entre_fechas.setText("Facturas entre fechas");
        btn_ordenes_entre_fechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ordenes_entre_fechasActionPerformed(evt);
            }
        });

        btn_ordenes_entre_fechas1.setBackground(new java.awt.Color(78, 205, 196));
        btn_ordenes_entre_fechas1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_ordenes_entre_fechas1.setText("Errores en entregas");
        btn_ordenes_entre_fechas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ordenes_entre_fechas1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_ordenes_entre_fechas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ordenes_entre_fechas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Ingresosdiarios3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(392, 392, 392))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Ingresosdiarios3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ordenes_entre_fechas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ordenes_entre_fechas1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 377, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 377, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Ingresosdiarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Ingresosdiarios1ActionPerformed
        jd_Ingreso_productosDiario j = new jd_Ingreso_productosDiario(null, closable);
        j.show();
    }//GEN-LAST:event_btn_Ingresosdiarios1ActionPerformed

    private void btn_IngresosBetwin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresosBetwin2ActionPerformed
        jd_Ingreso_productosEntreFechas j = new jd_Ingreso_productosEntreFechas(null, closable);
        j.show();
    }//GEN-LAST:event_btn_IngresosBetwin2ActionPerformed

    private void btn_Ingresosdiarios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Ingresosdiarios2ActionPerformed
        jd_Salida_productosDiario j = new jd_Salida_productosDiario(null, closable);
        j.show();
    }//GEN-LAST:event_btn_Ingresosdiarios2ActionPerformed

    private void btn_IngresosBetwin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresosBetwin3ActionPerformed
        jd_Salida_productos_Entre_Fechas j = new jd_Salida_productos_Entre_Fechas(null, closable);
        j.show();
    }//GEN-LAST:event_btn_IngresosBetwin3ActionPerformed

    private void btn_IngresosBetwin5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresosBetwin5ActionPerformed
        jd_Salida_productos_entre_fechas_XProducto j = new jd_Salida_productos_entre_fechas_XProducto(null, closable);
        j.show();
    }//GEN-LAST:event_btn_IngresosBetwin5ActionPerformed

    private void btn_IngresosBetwin7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresosBetwin7ActionPerformed
        jd_Balance_productosEntreFechas j = new jd_Balance_productosEntreFechas(null, closable);
        j.show();
    }//GEN-LAST:event_btn_IngresosBetwin7ActionPerformed

    private void btn_Ingresos_entre_fechas_por_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Ingresos_entre_fechas_por_productoActionPerformed
        jd_Ingreso_productosEntreFechas_x_producto j = new jd_Ingreso_productosEntreFechas_x_producto(null, closable);
        j.show();
    }//GEN-LAST:event_btn_Ingresos_entre_fechas_por_productoActionPerformed

    private void btn_IngresosBetwin6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresosBetwin6ActionPerformed
        jd_productos_pendientes_de_entrega j = new jd_productos_pendientes_de_entrega(null, closable);
        j.show();
    }//GEN-LAST:event_btn_IngresosBetwin6ActionPerformed

    private void btn_IngresosBetwin8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresosBetwin8ActionPerformed
        jd_productos_entregados j = new jd_productos_entregados(null, closable);
        j.show();
    }//GEN-LAST:event_btn_IngresosBetwin8ActionPerformed

    private void btn_Ingresosdiarios3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Ingresosdiarios3ActionPerformed
        jd_Salida_productos_Entre_Fechas_cantidad j = new jd_Salida_productos_Entre_Fechas_cantidad(null, closable);
        j.show();
    }//GEN-LAST:event_btn_Ingresosdiarios3ActionPerformed

    private void btn_ordenes_entre_fechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ordenes_entre_fechasActionPerformed
        jd_Facturas_entre_fechas j = new jd_Facturas_entre_fechas(null, closable);
        j.show();
    }//GEN-LAST:event_btn_ordenes_entre_fechasActionPerformed

    private void btn_ordenes_entre_fechas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ordenes_entre_fechas1ActionPerformed
        jd_Errores_entregas j = new jd_Errores_entregas(null, closable);
        j.show();
    }//GEN-LAST:event_btn_ordenes_entre_fechas1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_IngresosBetwin2;
    private javax.swing.JButton btn_IngresosBetwin3;
    private javax.swing.JButton btn_IngresosBetwin5;
    private javax.swing.JButton btn_IngresosBetwin6;
    private javax.swing.JButton btn_IngresosBetwin7;
    private javax.swing.JButton btn_IngresosBetwin8;
    private javax.swing.JButton btn_Ingresos_entre_fechas_por_producto;
    private javax.swing.JButton btn_Ingresosdiarios1;
    private javax.swing.JButton btn_Ingresosdiarios2;
    private javax.swing.JButton btn_Ingresosdiarios3;
    private javax.swing.JButton btn_ordenes_entre_fechas;
    private javax.swing.JButton btn_ordenes_entre_fechas1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
