/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Metodos.CellRendererFacturas;
import Metodos.TextPrompt;
import Metodos.metodos;
import com.ezware.oxbow.swingbits.table.filter.TableRowFilterSupport;
import conexiondb.ConsultasSQL;
import conexiondb.DB_consultas_R_D;
import conexiondb.DBfacturas_cabeceras;
import conexiondb.DBstock_productos;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;
import modelos.Facturas_cabeceras;

/**
 *
 * @author Monkeyelgrande
 */
public class frm_Ordenes extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_clientes
     */
    frm_ver_orden frm = new frm_ver_orden();
    frm_editar_orden frm_editar_orden = new frm_editar_orden();
    static TableColumnModel columnModel = null;
    static TableColumnModel columncolumnModel_Editar = null;
    CellRendererFacturas myRenderer = new CellRendererFacturas();

    static DefaultTableModel modelo_facturas = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false; //Con esto conseguimos que la tabla no se pueda editar
        }
    };

    public frm_Ordenes() {
        initComponents();
        // Selección múltiple para poder unir varias órdenes (Ctrl/Shift + clic).
        // getSelectedRow() de ver/editar/anular sigue devolviendo la primera fila.
        jtabla_facturas.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        actualizar("pendientes");
        columnModel = jtabla_facturas.getColumnModel();
        columncolumnModel_Editar = frm_editar_orden.jtabla_Ventas.getColumnModel();
        TamanosTablaAbonos();
        jtabla_facturas.setDefaultRenderer(Object.class, myRenderer);
        metodos.BuscarEnTabla(txt_Filtro, jtabla_facturas);

        lbl_titulo.setText("Ordenes");
//        Contactos.mostrarContactosNombre(txt_FiltroNombre, false);
        TableRowFilterSupport.forTable(jtabla_facturas).searchable(true).apply();

        jtabla_facturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(MouseEvent me) {
                if (me.getClickCount() == 2) {
                    btn_verActionPerformed(null);
                }
            }
        });
        jtabla_facturas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(KeyEvent me) {
                char num = me.getKeyChar();
                if (num == KeyEvent.VK_ENTER) {
                    btn_verActionPerformed(null);

                }
            }
        });
        TextPrompt orden = new TextPrompt("Buscar", txt_Filtro);
        permisos();
        txt_Filtro.requestFocus();
    }


    public void permisos() {
        if (frm_main.perfil == 2) {
            btn_editar.setEnabled(false);
            btn_eliminar.setEnabled(false);
        }
        // Unir órdenes es una propiedad por usuario (opcion 'ordenes_unir');
        // con la BD sin migrar solo el admin ve el botón.
        if (Metodos.Permisos.estaCargado()) {
            btn_unir.setVisible(Metodos.Permisos.puede("ordenes_unir"));
        } else {
            btn_unir.setVisible(frm_main.perfil == 1);
        }
    }

    public static void TamanosTablaAbonos() {
        columnModel.getColumn(0).setPreferredWidth(10);
        columnModel.getColumn(1).setPreferredWidth(10);
        columnModel.getColumn(2).setPreferredWidth(400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpop_cliente = new javax.swing.JPopupMenu();
        mn_clientes = new javax.swing.JMenuItem();
        lbl_cant_clientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla_facturas = new javax.swing.JTable();
        txt_Filtro = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btn_actualizar = new javax.swing.JButton();
        btn_ver = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_unir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btn_ver_con_entregadas = new javax.swing.JButton();

        mn_clientes.setText("Actualizar");
        mn_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_clientesActionPerformed(evt);
            }
        });
        jpop_cliente.add(mn_clientes);

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        lbl_cant_clientes.setBackground(new java.awt.Color(52, 73, 94));

        jtabla_facturas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtabla_facturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtabla_facturas.setRowHeight(35);
        jtabla_facturas.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jtabla_facturas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jtabla_facturas);

        txt_Filtro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Filtro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_FiltroFocusGained(evt);
            }
        });
        txt_Filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_FiltroKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout lbl_cant_clientesLayout = new javax.swing.GroupLayout(lbl_cant_clientes);
        lbl_cant_clientes.setLayout(lbl_cant_clientesLayout);
        lbl_cant_clientesLayout.setHorizontalGroup(
            lbl_cant_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbl_cant_clientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lbl_cant_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(lbl_cant_clientesLayout.createSequentialGroup()
                        .addComponent(txt_Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        lbl_cant_clientesLayout.setVerticalGroup(
            lbl_cant_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbl_cant_clientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(33, 33, 33));

        btn_actualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        btn_actualizar.setText("Actualizar");
        btn_actualizar.setBorder(null);
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        btn_ver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ver.png"))); // NOI18N
        btn_ver.setMnemonic('e');
        btn_ver.setText("Ver");
        btn_ver.setBorder(null);
        btn_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verActionPerformed(evt);
            }
        });

        btn_eliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btn_eliminar.setMnemonic('d');
        btn_eliminar.setText("Anular");
        btn_eliminar.setBorder(null);
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_editar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.setBorder(null);
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_unir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_unir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Chain.png"))); // NOI18N
        btn_unir.setText("Unir órdenes");
        btn_unir.setBorder(null);
        btn_unir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_unirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ver, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_unir, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_actualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_unir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(34, 49, 63));
        jPanel4.setPreferredSize(new java.awt.Dimension(146, 80));

        lbl_titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setText("Ordenes");

        jButton2.setBackground(new java.awt.Color(102, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setMnemonic('w');
        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btn_ver_con_entregadas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_ver_con_entregadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ver.png"))); // NOI18N
        btn_ver_con_entregadas.setText("Ver con entregadas");
        btn_ver_con_entregadas.setBorder(null);
        btn_ver_con_entregadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ver_con_entregadasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 698, Short.MAX_VALUE)
                .addComponent(btn_ver_con_entregadas, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_titulo)
                    .addComponent(btn_ver_con_entregadas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1112, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_cant_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_cant_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mn_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_clientesActionPerformed
        actualizar("");
    }//GEN-LAST:event_mn_clientesActionPerformed
    public static void actualizar(String tipo) {
        modelo_facturas.setRowCount(0);
        modelo_facturas.setColumnIdentifiers(new Object[]{"id", "# Factura", "Nombre cliente", "Fecha", "Tipo orden", "Estado", "Bodega"});
        String SQL_FACTURAS = "WITH\n"
                + "  detalles AS (\n"
                + "    SELECT \n"
                + "      id_cabecera, \n"
                + "      SUM(cantidad) AS total_detalles\n"
                + "    FROM facturas_detalles\n"
                + "    GROUP BY id_cabecera\n"
                + "  ),\n"
                + "  entregas AS (\n"
                + "    SELECT \n"
                + "      id_factura AS id_cabecera, \n"
                + "      SUM(cantidad) AS total_entregas\n"
                + "    FROM entregas_productos\n"
                + "    GROUP BY id_factura\n"
                + "  )\n"
                + "SELECT\n"
                + "  fc.id,\n"
                + "  fc.codigo,\n"
                + "  c.nombre      AS cliente,\n"
                + "  fc.fecha,\n"
                + "  fc.tipo_factura,\n"
                + "  GREATEST(\n"
                + "    COALESCE(d.total_detalles, 0)\n"
                + "    - COALESCE(e.total_entregas,  0),\n"
                + "    0\n"
                + "  ) AS pendiente,\n"
                + "  b.nombre AS bodega\n"
                + "FROM facturas_cabeceras fc\n"
                + "JOIN contactos c\n"
                + "  ON fc.id_contacto = c.id\n"
                + "LEFT JOIN detalles d\n"
                + "  ON d.id_cabecera = fc.id\n"
                + "LEFT JOIN entregas e\n"
                + "  ON e.id_cabecera = fc.id\n"
                + "LEFT JOIN bodegas b\n"
                + "  ON b.id = fc.id_bodega\n"
                + "WHERE\n"
                + "  fc.anulado = 1\n"
                + "  AND fc.tipo_factura <> 'Venta'\n"
                + "ORDER BY fc.id desc;";
//        System.out.println(SQL_FACTURAS);

        try (ResultSet rs = DB_consultas_R_D.getTabla(SQL_FACTURAS)) {

            while (rs.next()) {
                double pendiente = rs.getDouble("pendiente");

                // 3. Si el filtro es "pendientes", saltarse las que estén en 0
                if ("pendientes".equalsIgnoreCase(tipo) && pendiente == 0) {
                    continue;
                }
                if (frm_main.lbl_perfil.getText().equals("bodeguero") && !frm_main.lbl_bodega_user.getText().equals(rs.getString("bodega"))) {
                    continue;
                }

                String estado = (pendiente != 0) ? "Pendiente" : "Entregado";

                modelo_facturas.addRow(new Object[]{
                    rs.getString("id"),
                    rs.getString("codigo"),
                    rs.getString("cliente"),
                    rs.getString("fecha"),
                    rs.getString("tipo_factura"),
                    estado,
                    rs.getString("bodega") // ← NUEVA COLUMNA AL FINAL
                });
            }

            // 4. Asignar modelo y ajustar columnas
            jtabla_facturas.setModel(modelo_facturas);
            TamanosTablaAbonos();

        } catch (Exception e) {
            System.out.println("Error consultando frm_facturas: " + e.getMessage());
        }
    }

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        actualizar("pendientes");
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verActionPerformed
        Facturas_cabeceras f = new Facturas_cabeceras();
        f.cargar_facturas(jtabla_facturas, "");

    }//GEN-LAST:event_btn_verActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        if (DB_consultas_R_D.validar_admin()) {
            int fila = jtabla_facturas.getSelectedRow();
            if (fila == -1) {
                JOptionPane.showMessageDialog(null, "Seleccione un registro");
            } else {
                try {
                    String id = (String) jtabla_facturas.getValueAt(fila, 0);
                    int idOrden = Integer.parseInt(id);

                    // ════════════════════════════════════════════════════════════
                    // VALIDACIÓN: No permitir anular si tiene entregas asociadas
                    // ════════════════════════════════════════════════════════════
                    if (tieneEntregasAsociadas(idOrden)) {
                        JOptionPane.showMessageDialog(null,
                                "No se puede anular esta orden porque ya tiene entregas registradas.\n\n"
                                + "Debe eliminar primero las entregas asociadas antes de anular la orden.",
                                "Operación no permitida",
                                JOptionPane.WARNING_MESSAGE);
                        return;
                    }

                    int dialogButton = JOptionPane.YES_NO_OPTION;
                    int dialogResult = JOptionPane.showConfirmDialog(null,
                            "¿Desea anular esta orden?\n"
                            + "TAMBIEN SE ANULARAN LAS SALIDAS DE LOS PRODUCTOS ASOCIADAS A ESTA ORDEN",
                            "Alerta", dialogButton, 2);

                    if (dialogResult == JOptionPane.YES_OPTION) {
                        DefaultTableModel modelo = (DefaultTableModel) jtabla_facturas.getModel();

                        // ════════════════════════════════════════════════════════════
                        // INTEGRACIÓN STOCK: Reversar stock antes de anular
                        // ════════════════════════════════════════════════════════════
                        reversarStockOrdenAnulada(idOrden);

                        // Marcar como anulado
                        DBfacturas_cabeceras.ActualizaAnulado(id, 0);

                        // Quitar de la tabla visual
                        for (int i = 0; i < modelo.getRowCount(); i++) {
                            if (modelo.getValueAt(i, 0).equals(id)) {
                                modelo.removeRow(i);
                                break;
                            }
                        }
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed
    private boolean tieneEntregasAsociadas(int idOrden) {
        String sql = "SELECT COUNT(*) AS total FROM entregas_productos_cabecera WHERE id_factura = " + idOrden;
        ResultSet rs = DB_consultas_R_D.getTabla(sql);
        try {
            if (rs.next()) {
                int total = rs.getInt("total");
                rs.close();
                return total > 0;
            }
            rs.close();
        } catch (SQLException e) {
            System.out.println("Error verificando entregas: " + e);
        }
        return false;
    }
// ════════════════════════════════════════════════════════════════════════════
// MÉTODO AUXILIAR: Reversar stock de orden anulada
// ════════════════════════════════════════════════════════════════════════════

    private void reversarStockOrdenAnulada(int idOrden) {
        DBstock_productos dbStock = new DBstock_productos();

        // Obtener bodega de la orden
        int idBodega = 1;
        String sqlBodega = "SELECT id_bodega FROM facturas_cabeceras WHERE id = " + idOrden;
        ResultSet rsBodega = DB_consultas_R_D.getTabla(sqlBodega);
        try {
            if (rsBodega.next()) {
                idBodega = rsBodega.getInt("id_bodega");
            }
            rsBodega.close();
        } catch (SQLException e) {
            System.out.println("Error obteniendo bodega: " + e);
        }

        // Obtener detalles y reversar cada producto
        String sql = "SELECT id_producto, cantidad, id_factura FROM facturas_detalles WHERE id_cabecera = " + idOrden;
        ResultSet rs = DB_consultas_R_D.getTabla(sql);
        try {
            while (rs.next()) {
                int idProducto = rs.getInt("id_producto");
                double cantidad = rs.getDouble("cantidad");
                int idFacturaRef = rs.getInt("id_factura");

                if (idFacturaRef == 0) {
                    // Orden normal: solo liberar pendientes
                    dbStock.anulacionOrden(
                            idProducto,
                            idBodega,
                            frm_main.id_user,
                            cantidad,
                            idOrden,
                            "Anulación de orden"
                    );
                } else {
                    // Orden referenciada: revertir cantidad Y pendientes
                    dbStock.anulacionOrdenReferenciada(
                            idProducto,
                            idBodega,
                            frm_main.id_user,
                            cantidad,
                            idOrden,
                            "Anulación orden ref. - Factura WO: " + idFacturaRef
                    );
                }
            }
            rs.close();
        } catch (SQLException e) {
            System.out.println("Error reversando stock orden anulada: " + e);
        }
    }
    private void btn_ver_con_entregadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ver_con_entregadasActionPerformed
        actualizar("");
    }//GEN-LAST:event_btn_ver_con_entregadasActionPerformed

    private void btn_unirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_unirActionPerformed
        int[] filas = jtabla_facturas.getSelectedRows();
        if (filas.length < 2) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione al menos 2 órdenes para unir.\n"
                    + "Use Ctrl + clic (o Shift + clic) para seleccionar varias.");
            return;
        }

        java.util.List<Integer> ids = new java.util.ArrayList<>();
        try {
            for (int fila : filas) {
                // getValueAt sobre la JTable mapea vista -> modelo (compatible con el filtro)
                ids.add(Integer.parseInt((String) jtabla_facturas.getValueAt(fila, 0)));
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Selección inválida. Actualice el listado e intente de nuevo.");
            return;
        }

        java.util.List<conexiondb.DBfusion_ordenes.OrdenResumen> resumen = new java.util.ArrayList<>();
        String error = conexiondb.DBfusion_ordenes.validarUnion(ids, resumen);
        if (error != null) {
            JOptionPane.showMessageDialog(this, error, "No se puede unir", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // El resumen viene ordenado por id: la primera (más antigua) sobrevive.
        conexiondb.DBfusion_ordenes.OrdenResumen sobrev = resumen.get(0);
        int totalLineas = 0;
        StringBuilder msg = new StringBuilder();
        msg.append("Se unirán ").append(resumen.size())
                .append(" órdenes de la bodega ").append(sobrev.bodega).append(":\n\n");
        msg.append("CONSERVA:  #").append(sobrev.id);
        if (!sobrev.codigo.isEmpty()) {
            msg.append(" (").append(sobrev.codigo).append(")");
        }
        msg.append(" - ").append(sobrev.cliente)
                .append("  [").append(sobrev.lineas).append(" líneas]\n");
        for (int i = 1; i < resumen.size(); i++) {
            conexiondb.DBfusion_ordenes.OrdenResumen o = resumen.get(i);
            totalLineas += o.lineas;
            msg.append("Se anula:  #").append(o.id);
            if (!o.codigo.isEmpty()) {
                msg.append(" (").append(o.codigo).append(")");
            }
            msg.append(" - ").append(o.cliente)
                    .append("  [").append(o.lineas).append(" líneas]\n");
        }
        msg.append("\nLas ").append(totalLineas)
                .append(" líneas de las órdenes anuladas pasarán a la orden #").append(sobrev.id)
                .append(".\nEl stock pendiente NO cambia.\n\n¿Desea continuar?");

        int dialogResult = JOptionPane.showConfirmDialog(this, msg.toString(),
                "Unir órdenes", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (dialogResult != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            int idSobrev = conexiondb.DBfusion_ordenes.unirOrdenes(ids, frm_main.id_user);
            JOptionPane.showMessageDialog(this, "Órdenes unidas en la orden #" + idSobrev);
            actualizar("pendientes");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                    "No se realizó la fusión (no se hizo ningún cambio):\n" + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_unirActionPerformed

    private void txt_FiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_FiltroKeyTyped

    }//GEN-LAST:event_txt_FiltroKeyTyped

    private void txt_FiltroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_FiltroFocusGained

    }//GEN-LAST:event_txt_FiltroFocusGained

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        boolean autorizado = false;
        if (frm_main.perfil == 3) { // VENDEDOR: puede editar solo si no ha impreso
            int fila_sel = jtabla_facturas.getSelectedRow();
            if (fila_sel < 0) {
                JOptionPane.showMessageDialog(null, "Seleccione un registro");
                return;
            }
            String id_orden_sel = (String) jtabla_facturas.getValueAt(fila_sel, 0);
            try {
                Connection con = DB_consultas_R_D.getConexion();
                PreparedStatement ps = con.prepareStatement(
                        "SELECT COALESCE(impreso_vendedor, 0) FROM facturas_cabeceras WHERE id = ?");
                ps.setInt(1, Integer.parseInt(id_orden_sel));
                ResultSet rsi = ps.executeQuery();
                int impreso = 0;
                if (rsi.next()) {
                    impreso = rsi.getInt(1);
                }
                rsi.close();
                ps.close();
                con.close();
                if (impreso == 1) {
                    JOptionPane.showMessageDialog(this,
                            "Esta orden ya fue impresa. No puede modificarla.");
                    return;
                }
                autorizado = true;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error validando impresion: " + ex.getMessage());
                return;
            }
        } else {
            autorizado = DB_consultas_R_D.validar_admin();
        }
        if (autorizado) {
            DecimalFormatSymbols sim = new DecimalFormatSymbols();
            sim.setDecimalSeparator('.');
            DecimalFormat formatea = new DecimalFormat("###,###.##", sim);
            columnModel = frm_editar_orden.jtabla_Ventas.getColumnModel();

            int fila = jtabla_facturas.getSelectedRow();
            if (fila < 0) {
                JOptionPane.showMessageDialog(null, "Seleccione un registro");
            } else {
                String id_orden = (String) jtabla_facturas.getValueAt(fila, 0);

                if (DB_consultas_R_D.consutla_entregas(id_orden) > 0) {
                    JOptionPane.showMessageDialog(this, "Esta orden ya tiene entregas realziadas\nNO puede editarla hasta eliminar estas entregas priemero\nDepues debe volver a crear estas entregas");
                } else {

                    ResultSet rs = DB_consultas_R_D.getTabla(
                            "SELECT "
                            + "   f.id AS id_f, "
                            + "   f.fecha, "
                            + "   f.hora, "
                            + "   c.id AS id_c, "
                            + "   c.cedula, "
                            + "   c.nombre, "
                            + "   c.direccion, "
                            + "   c.contacto, "
                            + "   f.tipo_factura, "
                            + "   u.user_name, "
                            + "   f.codigo, "
                            + "   f.observacion, "
                            + "   b.id as id_bodega, "
                            + "   b.nombre AS bodega "
                            + "FROM facturas_cabeceras f "
                            + "JOIN contactos c ON f.id_contacto = c.id "
                            + "JOIN users u ON f.id_user = u.id "
                            + "LEFT JOIN bodegas b ON b.id = f.id_bodega "
                            + "WHERE f.id = " + id_orden
                    );
                    try {
                        while (rs.next()) {
                            frm_editar_orden.lbl_numerofactura.setText(rs.getString("id_f"));
                            frm_editar_orden.lbl_id_cliente.setText(rs.getString("id_c"));
                            frm_editar_orden.jbox_cliente.setSelectedItem(rs.getString("nombre"));
                            frm_editar_orden.txt_codigo.setText(rs.getString("codigo"));
                            frm_editar_orden.txt_observaciones.setText(rs.getString("observacion"));
                            String tipo_salida = rs.getString("tipo_factura");
                            if (tipo_salida.equals("Salida")) {
                                frm_editar_orden.rb_salida.setSelected(true);
                            } else if (tipo_salida.equals("Eliminación")) {
                                frm_editar_orden.rb_eliminacion.setSelected(true);
                            } else {
                                frm_editar_orden.rb_prestamo.setSelected(true);
                            }
                            frm_editar_orden.jbox_bodega.setSelectedItem(rs.getString("bodega"));
                            frm_editar_orden.id_bodega = rs.getInt("id_bodega");
                        }
                        rs.close();

                    } catch (SQLException ex) {
                        Logger.getLogger(frm_ver_orden.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    rs = DB_consultas_R_D.getTabla("select p.id, p.codigo_barras, p.descripcion, f.cantidad, f.id_factura "
                            + "from facturas_detalles f, productos p where f.id_producto=p.id and id_cabecera=" + id_orden);

                    frm_editar_orden.modelo.setRowCount(0);
                    frm_editar_orden.TamanosTablaVentas();

                    frm_editar_orden.modelo.setColumnIdentifiers(new Object[]{"ID", "CODIGO", "DESCRIPCIÓN", "CANTIDAD", "R"});
                    try {
                        while (rs.next()) {
                            frm_editar_orden.modelo.addRow(new Object[]{rs.getString("id"), rs.getString("codigo_barras"), rs.getString("descripcion"),
                                metodos.formateador_x_decimal(3).format(rs.getDouble("cantidad")), rs.getString("id_factura")
                            });
                        }
                        rs.close();
                        frm_editar_orden.jtabla_Ventas.setModel(frm_editar_orden.modelo);
                        frm_editar_orden.TamanosTablaVentas();
                    } catch (SQLException ex) {
                        Logger.getLogger(frm_ver_orden.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    frm_editar_orden.show(true);
                }
            }
        }

    }//GEN-LAST:event_btn_editarActionPerformed
    public void TamanosTablaEditar() {
        columncolumnModel_Editar.getColumn(0).setPreferredWidth(40);
        columncolumnModel_Editar.getColumn(1).setPreferredWidth(600);
        columncolumnModel_Editar.getColumn(2).setPreferredWidth(80);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Ordenes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Ordenes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Ordenes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Ordenes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Ordenes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_actualizar;
    public static javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_unir;
    public static javax.swing.JButton btn_ver;
    private javax.swing.JButton btn_ver_con_entregadas;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu jpop_cliente;
    private static javax.swing.JTable jtabla_facturas;
    private javax.swing.JPanel lbl_cant_clientes;
    public static javax.swing.JLabel lbl_titulo;
    public static javax.swing.JMenuItem mn_clientes;
    private javax.swing.JTextField txt_Filtro;
    // End of variables declaration//GEN-END:variables
}
