/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Formularios_internos.jif_crear_ingreso_mercancia;
import Metodos.CellRendererIngresos;
import Metodos.metodos;
import conexiondb.DB_consultas_R_D;
import conexiondb.DBingresosMercancias;
import conexiondb.DBstock_productos;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Monkeyelgrande
 */
public class frm_ingreso_mercancia extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_clientes
     */
    TableColumnModel columnModel = null;
    CellRendererIngresos myRenderer = new CellRendererIngresos();

    public frm_ingreso_mercancia() {
        initComponents();
        actualizar();
        columnModel = jtabla.getColumnModel();
        TamanosTabla();
        jtabla.setDefaultRenderer(Object.class, myRenderer);

        jtabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(MouseEvent me) {
                if (me.getClickCount() == 2) {
                    int fila = jtabla.rowAtPoint(me.getPoint());
                    int columna = jtabla.columnAtPoint(me.getPoint());
                    // Doble clic sobre la columna Estado de un ingreso PENDIENTE:
                    // ofrece pasarlo a RECIBIDO. En cualquier otro caso, abre el ver.
                    if (fila >= 0 && columna >= 0
                            && jtabla.convertColumnIndexToModel(columna) == 5
                            && "Pendiente".equals("" + jtabla.getValueAt(fila, columna))) {
                        pasar_a_recibido(fila);
                    } else {
                        btn_verActionPerformed(null);
                    }
                }
            }
        });

        if (frm_main.perfil == 2) {
            btn_eliminar.setEnabled(false);
            btn_editar.setEnabled(false);
        }
        metodos.BuscarEnTabla(txt_Filtro, jtabla);
//        metodos.EstiloTablaMaterialGlobal(jtabla);
    }

    DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false; //Con esto conseguimos que la tabla no se pueda editar
        }
    };

    public void TamanosTabla() {
        columnModel.getColumn(0).setPreferredWidth(20);
        columnModel.getColumn(1).setPreferredWidth(300);
        columnModel.getColumn(2).setPreferredWidth(100);
        columnModel.getColumn(3).setPreferredWidth(100);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_cant_clientes = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        txt_Filtro = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btn_crear = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_ver = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btn_cerrar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ingreso mercancia");

        lbl_cant_clientes.setBackground(new java.awt.Color(33, 33, 33));

        jtabla.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtabla.setRowHeight(35);
        jtabla.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jtabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jtabla);

        txt_Filtro.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        txt_Filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_FiltroKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout lbl_cant_clientesLayout = new javax.swing.GroupLayout(lbl_cant_clientes);
        lbl_cant_clientes.setLayout(lbl_cant_clientesLayout);
        lbl_cant_clientesLayout.setHorizontalGroup(
            lbl_cant_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbl_cant_clientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lbl_cant_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
                    .addGroup(lbl_cant_clientesLayout.createSequentialGroup()
                        .addComponent(txt_Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        lbl_cant_clientesLayout.setVerticalGroup(
            lbl_cant_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbl_cant_clientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(33, 33, 33));

        btn_crear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        btn_crear.setMnemonic('n');
        btn_crear.setText("Nuevo");
        btn_crear.setBorder(null);
        btn_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearActionPerformed(evt);
            }
        });

        btn_eliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btn_eliminar.setMnemonic('d');
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setBorder(null);
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_actualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        btn_actualizar.setText("Actualizar");
        btn_actualizar.setBorder(null);
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        btn_ver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ver.png"))); // NOI18N
        btn_ver.setMnemonic('e');
        btn_ver.setText("Ver");
        btn_ver.setBorder(null);
        btn_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verActionPerformed(evt);
            }
        });

        btn_editar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        btn_editar.setMnemonic('e');
        btn_editar.setText("Editar");
        btn_editar.setBorder(null);
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_actualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ver, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_crear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_actualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(3, 155, 229));
        jPanel4.setPreferredSize(new java.awt.Dimension(146, 80));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Ingreso Mercancia");

        btn_cerrar.setBackground(new java.awt.Color(102, 0, 0));
        btn_cerrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cerrar.setMnemonic('w');
        btn_cerrar.setText("Cerrar");
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 758, Short.MAX_VALUE)
                .addComponent(btn_cerrar)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cerrar)
                    .addComponent(jLabel13))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1088, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_cant_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_cant_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 309, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearActionPerformed
        jif_crear_ingreso_mercancia jif_crear_ingreso = new jif_crear_ingreso_mercancia();
        jif_crear_ingreso.show();


    }//GEN-LAST:event_btn_crearActionPerformed

    public int consultarId(String id) {
        ResultSet rs = DB_consultas_R_D.getTabla("select count(id) as id from ingresos_mercancias_cabecera where id = " + id + "");
        try {
            while (rs.next()) {
                // añade los resultado a al modelo de tabla
                return Integer.parseInt(rs.getString("id"));
            }
            rs.close();
            // asigna el modelo a la tabla
            jtabla.setModel(modelo);
        } catch (Exception e) {
            System.out.println(e);
            return 0;
        }
        return 0;
    }
    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed

        if (DB_consultas_R_D.validar_admin()) {
            int fila = jtabla.getSelectedRow();
            if (fila == -1) {
                JOptionPane.showMessageDialog(null, "Seleccione un registro");
            } else {
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog(null, "Desea eliminar este ingreso de mercancia? "
                        + "\nAl eliminar este INGRESO se restara de sl stock de PRODUCTOS", "Alerta", dialogButton);
                if (dialogResult == JOptionPane.YES_OPTION) {

                    try {
                        DefaultTableModel modelo = (DefaultTableModel) jtabla.getModel();
                        String id = (String) jtabla.getValueAt(fila, 0);//suponiendo que el id lo muestras en la primera columna
                        DBingresosMercancias dbIngreso = new DBingresosMercancias();
                        if (dbIngreso.eliminarConReversion(Integer.parseInt(id), frm_main.id_user)) {
                            for (int i = 0; i < modelo.getRowCount(); i++) {
                                if (modelo.getValueAt(i, 0).equals(id)) {
                                    modelo.removeRow(i);
                                    break;
                                }
                            }
                            JOptionPane.showMessageDialog(null,
                                    "Ingreso eliminado y stock revertido correctamente.");
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    public void validar_numeros(java.awt.event.KeyEvent evt, char car) {
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        actualizar();
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verActionPerformed
        ver_ingreso_mercancia("ver");
    }//GEN-LAST:event_btn_verActionPerformed
    public void ver_ingreso_mercancia(String ver_editar) {
        DecimalFormatSymbols simbolos = new DecimalFormatSymbols();
        simbolos.setDecimalSeparator('.');
        DecimalFormat formateador = new DecimalFormat("####.##", simbolos);
        int fila = jtabla.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un registro");
        } else {
            String id = (String) jtabla.getValueAt(fila, 0);
            int estadoIngreso = 0; // 0=pendiente, 1=recibido; define cómo mostrar la columna ACTUAL
            // LEFT JOIN para que la cabecera siempre devuelva su fila aunque el
            // transportador, bodega, proveedor o tipo estén nulos o sin coincidencia;
            // así se cargan todos los campos disponibles al ver/editar.
            ResultSet rs = DB_consultas_R_D.getTabla("select i.id, i.descripcion, i.no_factura, i.id_transportador, i.id_bodega, b.nombre as bodega, tra.nombre as transportador, "
                    + "p.nombre as proveedor, p.id as id_proveedor, t.nombre as tipo, t.id as id_tipo, i.fecha, i.fecha_vencimiento, i.estado "
                    + "from ingresos_mercancias_cabecera i "
                    + "left join contactos p on i.id_proveedor = p.id "
                    + "left join tipo_ingreso t on i.id_tipo = t.id "
                    + "left join contactos tra on i.id_transportador = tra.id "
                    + "left join bodegas b on i.id_bodega = b.id "
                    + "where i.id=" + id);

            jif_crear_ingreso_mercancia frm = new jif_crear_ingreso_mercancia();
            // Fijar el id real de la fila seleccionada de inmediato. El constructor
            // pone un id nuevo (cargarId = max+1) y la consulta de abajo usa joins que
            // pueden no devolver filas (p. ej. transportador/bodega sin coincidencia),
            // dejando el id nuevo y provocando que al guardar se cree otro registro.
            jif_crear_ingreso_mercancia.lbl_id.setText(id);

            try {
                while (rs.next()) {
                    jif_crear_ingreso_mercancia.lbl_id.setText(rs.getString("id"));
                    jif_crear_ingreso_mercancia.jdate_fecha_entrada.setDate(rs.getDate("fecha"));
                    java.util.Date fechaVencimiento = rs.getDate("fecha_vencimiento");
                    if (fechaVencimiento != null) {
                        jif_crear_ingreso_mercancia.jdate_fecha_vencimiento.setDate(fechaVencimiento);
                    }
                    jif_crear_ingreso_mercancia.jbox_proveedor.setSelectedItem(rs.getString("proveedor"));
                    jif_crear_ingreso_mercancia.id_proveedor = (rs.getInt("id_proveedor"));
                    jif_crear_ingreso_mercancia.id_transportador = (rs.getInt("id_transportador"));
                    // El combo de transportador muestra "nombre - cedula" y no usa
                    // autocompletar, por lo que seleccionar por nombre nunca coincide.
                    // Se selecciona por id para que cargue al ver/editar.
                    seleccionar_transportador(jif_crear_ingreso_mercancia.id_transportador);
                    jif_crear_ingreso_mercancia.jbox_tipo.setSelectedItem(rs.getString("tipo"));
                    jif_crear_ingreso_mercancia.jbox_bodega.setSelectedItem(rs.getString("bodega"));
                    jif_crear_ingreso_mercancia.id_tipo = (rs.getInt("id_tipo"));
                    jif_crear_ingreso_mercancia.txt_no_factura.setText(rs.getString("no_factura"));
                    jif_crear_ingreso_mercancia.id_bodega = (rs.getInt("id_bodega"));
                    jif_crear_ingreso_mercancia.txt_descripcion.setText(rs.getString("descripcion"));

                    estadoIngreso = rs.getInt("estado");
                    if (estadoIngreso == 0) {
                        jif_crear_ingreso_mercancia.rbtn_pendiente.setSelected(true);
                    } else {
                        jif_crear_ingreso_mercancia.rbtn_recibido.setSelected(true);
                    }
                    jif_crear_ingreso_mercancia.btn_agregar_pago.setEnabled(true);
                }

                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(jif_crear_ingreso_mercancia.class.getName()).log(Level.SEVERE, null, ex);
            }
            String consulta = "select p.id,p.codigo_barras,p.descripcion,i.cantidad, i.precio_costo, p.precio_venta "
                    + "from ingresos_mercancias_detalle i, productos p, ingresos_mercancias_cabecera ic "
                    + "where i.id_producto=p.id and i.id_ingreso_cabecera=ic.id and ic.id=" + id + " order by id";
            rs = DB_consultas_R_D.getTabla(consulta);

            try {
                while (rs.next()) {
                    double stock = DB_consultas_R_D.consultar_stock(rs.getString("codigo_barras"));
                    double cantidad = rs.getDouble("cantidad");

                    // Si el ingreso está RECIBIDO, su cantidad ya está sumada en el stock
                    // actual, así que la columna ACTUAL = stock - cantidad. Si está
                    // PENDIENTE, el stock todavía no lo incluye, así que ACTUAL = stock.
                    // La columna NUEVO TOTAL (col 5) se calcula sola como (agregar + actual).
                    double actual = (estadoIngreso == 1) ? stock - cantidad : stock;

                    jif_crear_ingreso_mercancia.modelo_productos.addRow(new Object[]{rs.getString("id"), rs.getString("codigo_barras"), rs.getString("descripcion"),
                        formateador.format(cantidad), actual, stock,
                        metodos.formateador_dinero().format(rs.getDouble("precio_costo")), metodos.formateador_dinero().format(rs.getDouble("precio_venta"))});

                }
                jif_crear_ingreso_mercancia.jtabla.setModel(jif_crear_ingreso_mercancia.modelo_productos);

                consulta = "select p.* \n"
                        + "from pagos_ingresos p \n"
                        + "where id_ingresos_mercancias_cabecera =" + id + " order by id";
                rs = DB_consultas_R_D.getTabla(consulta);

                for (int i = 0; i < jif_crear_ingreso_mercancia.modelo_pagos.getRowCount(); i++) {
                    jif_crear_ingreso_mercancia.modelo_pagos.removeRow(i);
                    i -= 1;
                }
                while (rs.next()) {
                    jif_crear_ingreso_mercancia.modelo_pagos.addRow(new Object[]{rs.getString("id"), metodos.formateador_dinero().format(rs.getDouble("total")),
                        rs.getDate("fecha"), rs.getString("cod_pago")});
                }

                rs.close();
                jif_crear_ingreso_mercancia.jtabla_Pagos.setModel(jif_crear_ingreso_mercancia.modelo_pagos);

            } catch (SQLException ex) {
                System.out.println(ex);
            }

            if (ver_editar.equals("ver")) {
                jif_crear_ingreso_mercancia.jbox_proveedor.setEnabled(false);
                jif_crear_ingreso_mercancia.jbox_transportador.setEnabled(false);
                jif_crear_ingreso_mercancia.jbox_tipo.setEnabled(false);
                jif_crear_ingreso_mercancia.jbox_bodega.setEnabled(false);
                jif_crear_ingreso_mercancia.txt_descripcion.setEnabled(false);
                jif_crear_ingreso_mercancia.txt_no_factura.setEnabled(false);
                jif_crear_ingreso_mercancia.txt_codigo_barras.setEnabled(false);
                jif_crear_ingreso_mercancia.btn_buscar.setEnabled(false);
                jif_crear_ingreso_mercancia.jdate_fecha_entrada.setEnabled(false);
                jif_crear_ingreso_mercancia.btn_guardar.setEnabled(false);
                jif_crear_ingreso_mercancia.btn_limpiar.setEnabled(false);
                jif_crear_ingreso_mercancia.chk_cerrar.setEnabled(false);
                jif_crear_ingreso_mercancia.jtabla.setEnabled(false);
                jif_crear_ingreso_mercancia.rbtn_recibido.setEnabled(false);
                jif_crear_ingreso_mercancia.rbtn_pendiente.setEnabled(false);
                jif_crear_ingreso_mercancia.btn_imprimir.setVisible(true);
            } else {
                jif_crear_ingreso_mercancia.chk_cerrar.setEnabled(false);
                jif_crear_ingreso_mercancia.btn_guardar.setText("Actualizar");
            }
            frm.calcular_total();
            frm.show();
        }
    }
    /**
     * Selecciona en el combo de transportador el contacto cuyo id coincide. El
     * combo se llena con items "nombre - cedula" y sin autocompletar, así que
     * seleccionar por texto no funciona; se busca por id como en el proveedor.
     */
    private void seleccionar_transportador(int idTransportador) {
        javax.swing.JComboBox<modelos.Contactos> combo = jif_crear_ingreso_mercancia.jbox_transportador;
        for (int i = 0; i < combo.getItemCount(); i++) {
            modelos.Contactos c = combo.getItemAt(i);
            if (c != null && c.getId() == idTransportador) {
                combo.setSelectedIndex(i);
                return;
            }
        }
    }

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        if (DB_consultas_R_D.validar_admin()) {
            ver_ingreso_mercancia("editar");
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    /**
     * Pasa un ingreso PENDIENTE a RECIBIDO desde la tabla (doble clic en la
     * columna Estado). Replica el mismo efecto que editar el ingreso, marcar
     * "Recibido" y darle Actualizar: cambia el estado en la cabecera y registra
     * el movimiento de inventario (suma stock) por cada producto del detalle.
     */
    private void pasar_a_recibido(int fila) {
        String id = "" + jtabla.getValueAt(fila, 0);

        int dialogResult = JOptionPane.showConfirmDialog(this,
                "¿Desea pasar este ingreso a RECIBIDO?\n"
                + "Se registrará el movimiento de inventario y se sumará el stock de los productos.",
                "Cambiar estado", JOptionPane.YES_NO_OPTION);
        if (dialogResult != JOptionPane.YES_OPTION) {
            return;
        }

        if (!DB_consultas_R_D.validar_admin()) {
            return;
        }

        int idIngreso = Integer.parseInt(id);
        int estadoActual = 0;
        int idBodega = 0;
        String noFactura = "";
        try {
            ResultSet rs = DB_consultas_R_D.getTabla("select estado, id_bodega, no_factura "
                    + "from ingresos_mercancias_cabecera where id=" + idIngreso);
            if (rs.next()) {
                estadoActual = rs.getInt("estado");
                idBodega = rs.getInt("id_bodega");
                noFactura = rs.getString("no_factura");
            }
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(frm_ingreso_mercancia.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }

        // Si otro usuario ya lo recibió, no volver a sumar stock
        if (estadoActual == 1) {
            JOptionPane.showMessageDialog(this, "Este ingreso ya se encuentra RECIBIDO");
            actualizar();
            return;
        }

        try {
            Connection con = DB_consultas_R_D.getConexion();
            PreparedStatement psql = con.prepareStatement(
                    "update ingresos_mercancias_cabecera set estado=1, id_user=" + frm_main.id_user
                    + " where id=" + idIngreso);
            psql.executeUpdate();
            psql.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(frm_ingreso_mercancia.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "No se pudo cambiar el estado del ingreso");
            return;
        }

        DBstock_productos dbStock = new DBstock_productos();
        try {
            ResultSet rs = DB_consultas_R_D.getTabla("select id_producto, cantidad, precio_costo "
                    + "from ingresos_mercancias_detalle where id_ingreso_cabecera=" + idIngreso);
            while (rs.next()) {
                dbStock.ingreso(
                        rs.getInt("id_producto"),
                        idBodega,
                        frm_main.id_user,
                        rs.getDouble("cantidad"),
                        rs.getDouble("precio_costo"),
                        idIngreso,
                        "Ingreso de mercancía - Factura: " + noFactura
                );
            }
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(frm_ingreso_mercancia.class.getName()).log(Level.SEVERE, null, ex);
        }

        modelo.setValueAt("Recibido", jtabla.convertRowIndexToModel(fila), 5);
        JOptionPane.showMessageDialog(this, "Ingreso marcado como RECIBIDO y stock actualizado");
    }

    private void txt_FiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_FiltroKeyTyped

    }//GEN-LAST:event_txt_FiltroKeyTyped
    boolean act = true;

    public void actualizar() {
        modelo.setRowCount(0);
        ResultSet rs = null;
        String consulta = "";

        modelo.setColumnIdentifiers(new Object[]{"id", "proveedor", "Numero factura", "Fecha", "Fecha vencimiento", "Estado", "Total", "Abono", "Saldo", "Dias"});
        if (act) {
            consulta = "with con2 as (\n"
                    + "	with consulta as (\n"
                    + "		select i.id, c.nombre as proveedor, i.fecha, coalesce(i.fecha_vencimiento,i.fecha) as fecha_vencimiento, i.no_factura, i.estado, coalesce(sum(id.precio_costo*id.cantidad),0) as total\n"
                    + "		from ingresos_mercancias_cabecera i \n"
                    + "		inner join ingresos_mercancias_detalle id on id.id_ingreso_cabecera=i.id, contactos c\n"
                    + "		where i.id_proveedor=c.id \n"
                    + "		group by i.id, c.nombre, i.fecha, i.fecha_vencimiento, i.no_factura, i.estado\n"
                    + "		order by fecha desc,  i.id desc\n"
                    + "	)\n"
                    + "	select c.*, (current_date-c.fecha_vencimiento) as dias, coalesce(sum(p.total),0) as abono, c.total-coalesce(sum(p.total),0) as saldo\n"
                    + "	from consulta c left join pagos_ingresos p on p.id_ingresos_mercancias_cabecera=c.id\n"
                    + "	group by c.id, c.proveedor, c.fecha, c.fecha_vencimiento, c.no_factura, c.estado, c.total\n"
                    + ")\n"
                    + "select * from con2 where saldo>0 order by id desc";
            act = false;
        } else {
            consulta = "with con2 as (\n"
                    + "	with consulta as (\n"
                    + "		select i.id, c.nombre as proveedor, i.fecha, coalesce(i.fecha_vencimiento,i.fecha) as fecha_vencimiento, i.no_factura, i.estado, coalesce(sum(id.precio_costo*id.cantidad),0) as total\n"
                    + "		from ingresos_mercancias_cabecera i \n"
                    + "		inner join ingresos_mercancias_detalle id on id.id_ingreso_cabecera=i.id, contactos c\n"
                    + "		where i.id_proveedor=c.id \n"
                    + "		group by i.id, c.nombre, i.fecha, i.fecha_vencimiento, i.no_factura, i.estado\n"
                    + "		order by fecha desc,  i.id desc\n"
                    + "	)\n"
                    + "	select c.*, (current_date-c.fecha_vencimiento) as dias, coalesce(sum(p.total),0) as abono, c.total-coalesce(sum(p.total),0) as saldo\n"
                    + "	from consulta c left join pagos_ingresos p on p.id_ingresos_mercancias_cabecera=c.id\n"
                    + "	group by c.id, c.proveedor, c.fecha, c.fecha_vencimiento, c.no_factura, c.estado, c.total\n"
                    + ")\n"
                    + "select * from con2 order by id desc";
            act = true;
        }

        System.out.println(consulta);
        rs = DB_consultas_R_D.getTabla(consulta);
        try {
            while (rs.next()) {
                // añade los resultado a al modelo de tabla
                String estado = "Recibido";
                if (rs.getInt("estado") == 0) {
                    estado = "Pendiente";
                }

                String dias = rs.getInt("dias") + "";
                if (rs.getDouble("saldo") == 0) {
                    dias = "Pagado";
                }
                if (rs.getDouble("saldo") > 0 && rs.getInt("dias") >= 0) {
                    dias = "+ " + dias;
                }
                modelo.addRow(new Object[]{rs.getString("id"), rs.getString("proveedor"), rs.getString("no_factura"), rs.getDate("fecha"), rs.getDate("fecha_vencimiento"), estado,
                    metodos.formateador_dinero().format(rs.getDouble("total")), metodos.formateador_dinero().format(rs.getDouble("abono")),
                    metodos.formateador_dinero().format(rs.getDouble("saldo")), dias});

            }
            rs.close();
            // asigna el modelo a la tabla
            jtabla.setModel(modelo);
            TamanosTabla();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_ingreso_mercancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_ingreso_mercancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_ingreso_mercancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_ingreso_mercancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_ingreso_mercancia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_crear;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_ver;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jtabla;
    private javax.swing.JPanel lbl_cant_clientes;
    private javax.swing.JTextField txt_Filtro;
    // End of variables declaration//GEN-END:variables
}
