/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Metodos.CellRendererFacturas;
import Metodos.TextPrompt;
import Metodos.metodos;
import com.ezware.oxbow.swingbits.table.filter.TableRowFilterSupport;
import conexiondb.ConsultasSQL;
import conexiondb.DB_consultas_R_D;
import conexiondb.DBfacturas_cabeceras;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;
import modelos.Facturas_cabeceras;

/**
 *
 * @author Monkeyelgrande
 */
public class frm_cotizaciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_clientes
     */
    frm_ver_orden frm = new frm_ver_orden();
    frm_editar_venta frm_editar_venta = new frm_editar_venta();
    static TableColumnModel columnModel = null;
    static TableColumnModel columncolumnModel_Editar = null;
    CellRendererFacturas myRenderer = new CellRendererFacturas();

    static DefaultTableModel modelo_facturas = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false; //Con esto conseguimos que la tabla no se pueda editar
        }
    };

    public frm_cotizaciones() {
        initComponents();
        actualizar("pendientes");
        columnModel = jtabla_facturas.getColumnModel();
        columncolumnModel_Editar = frm_editar_venta.jtabla_Ventas.getColumnModel();
        TamanosTablaAbonos();
        jtabla_facturas.setDefaultRenderer(Object.class, myRenderer);
        metodos.BuscarEnTabla(txt_Filtro, jtabla_facturas);

        TableRowFilterSupport.forTable(jtabla_facturas).searchable(true).apply();

        jtabla_facturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(MouseEvent me) {
                if (me.getClickCount() == 2) {
                    btn_verActionPerformed(null);
                }
            }
        });
        jtabla_facturas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(KeyEvent me) {
                char num = me.getKeyChar();
                if (num == KeyEvent.VK_ENTER) {
                    btn_verActionPerformed(null);

                }
            }
        });
        TextPrompt orden = new TextPrompt("Buscar", txt_Filtro);
        permisos();
        txt_Filtro.requestFocus();
        metodos.EstiloTablaMaterialGlobal(jtabla_facturas);

    }

    public void permisos() {
        if (frm_main.perfil == 2) {
            btn_editar.setEnabled(false);

        }
    }

    public static void TamanosTablaAbonos() {
        columnModel.getColumn(0).setPreferredWidth(10);
        columnModel.getColumn(1).setPreferredWidth(10);
        columnModel.getColumn(2).setPreferredWidth(400);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpop_cliente = new javax.swing.JPopupMenu();
        mn_clientes = new javax.swing.JMenuItem();
        lbl_cant_clientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla_facturas = new javax.swing.JTable();
        txt_Filtro = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btn_actualizar = new javax.swing.JButton();
        btn_ver = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        mn_clientes.setText("Actualizar");
        mn_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_clientesActionPerformed(evt);
            }
        });
        jpop_cliente.add(mn_clientes);

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        lbl_cant_clientes.setBackground(new java.awt.Color(52, 73, 94));

        jtabla_facturas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtabla_facturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtabla_facturas.setRowHeight(35);
        jtabla_facturas.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jtabla_facturas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jtabla_facturas);

        txt_Filtro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Filtro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_FiltroFocusGained(evt);
            }
        });
        txt_Filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_FiltroKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout lbl_cant_clientesLayout = new javax.swing.GroupLayout(lbl_cant_clientes);
        lbl_cant_clientes.setLayout(lbl_cant_clientesLayout);
        lbl_cant_clientesLayout.setHorizontalGroup(
            lbl_cant_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbl_cant_clientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lbl_cant_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 934, Short.MAX_VALUE)
                    .addGroup(lbl_cant_clientesLayout.createSequentialGroup()
                        .addComponent(txt_Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        lbl_cant_clientesLayout.setVerticalGroup(
            lbl_cant_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbl_cant_clientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(33, 33, 33));

        btn_actualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        btn_actualizar.setText("Actualizar");
        btn_actualizar.setBorder(null);
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        btn_ver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ver.png"))); // NOI18N
        btn_ver.setMnemonic('e');
        btn_ver.setText("Ver");
        btn_ver.setBorder(null);
        btn_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verActionPerformed(evt);
            }
        });

        btn_editar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.setBorder(null);
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ver, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_ver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_actualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_editar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 49, 63));
        jPanel4.setPreferredSize(new java.awt.Dimension(146, 80));

        lbl_titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setText("Cotizaciones");

        jButton2.setBackground(new java.awt.Color(102, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setMnemonic('w');
        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_titulo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1112, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_cant_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_cant_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mn_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_clientesActionPerformed
        actualizar("");
    }//GEN-LAST:event_mn_clientesActionPerformed
    public static void actualizar(String tipo) {
        try {
            for (int i = 0; i < jtabla_facturas.getRowCount(); i++) {
                modelo_facturas.removeRow(i);
                i -= 1;
            }
        } catch (Exception m) {
        }
        ResultSet rs = null;

        String consulta = "";

        consulta = "select f.id, f.codigo, c.nombre as cliente, f.fecha, coalesce((select max(id_factura) from cotizaciones_detalles where id_factura=f.id),0) as estado, f.tipo_pago \n"
                + "from cotizaciones_cabeceras f inner join contactos c on f.id_contacto=c.id\n"
                + "where f.anulado=1 order by f.id desc";

//        System.out.println(consulta);
        rs = DB_consultas_R_D.getTabla(consulta);
        modelo_facturas.setColumnIdentifiers(new Object[]{"id", "# Factura", "Nombre cliente", "Fecha", "Estado", "Tipo pago"});
        try {
            while (rs.next()) {
                // añade los resultado a al modelo de tabla
                String estado = "";
                String tipo_pago = "";

                if (rs.getDouble("tipo_pago") == 0) {
                    tipo_pago = "Contado";
                } else {
                    tipo_pago = "Credito";
                }

                if (rs.getDouble("estado") != 0) {
                    estado = "Orden " + rs.getInt("estado");
                } else {
                    estado = "Venta";
                }
                modelo_facturas.addRow(new Object[]{rs.getString("id"), rs.getString("codigo"), rs.getString("cliente"), rs.getString("fecha"), estado, tipo_pago});
            }
            rs.close();
            // asigna el modelo a la tabla
            jtabla_facturas.setModel(modelo_facturas);
            TamanosTablaAbonos();
        } catch (Exception e) {
            System.out.println("Error consutando frm_facturas: " + e);
        }
    }

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        actualizar("pendientes");
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verActionPerformed
        Facturas_cabeceras f = new Facturas_cabeceras();
        f.cargar_cotizaciones(jtabla_facturas, "");

    }//GEN-LAST:event_btn_verActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_FiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_FiltroKeyTyped

    }//GEN-LAST:event_txt_FiltroKeyTyped

    private void txt_FiltroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_FiltroFocusGained

    }//GEN-LAST:event_txt_FiltroFocusGained

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        if (DB_consultas_R_D.validar_admin()) {

            DecimalFormatSymbols sim = new DecimalFormatSymbols();
            sim.setDecimalSeparator('.');
            DecimalFormat formatea = new DecimalFormat("###,###.##", sim);
            columnModel = frm_editar_venta.jtabla_Ventas.getColumnModel();

            int fila = jtabla_facturas.getSelectedRow();
            if (fila < 0) {
                JOptionPane.showMessageDialog(null, "Seleccione un registro");
            } else {
                String id_orden = (String) jtabla_facturas.getValueAt(fila, 0);

                ResultSet rs = DB_consultas_R_D.getTabla("select f.id as id_f, tipo_pago, fecha,f.hora, c.id as id_c, c.cedula, c.nombre, c.direccion, "
                        + "c.contacto,f.tipo_factura, u.user_name, f.codigo, f.observacion "
                        + "from cotizaciones_cabeceras f,contactos c, users u where f.id_user=u.id and f.id_contacto=c.id and f.id =" + id_orden);
                try {
                    while (rs.next()) {
                        frm_editar_venta.lbl_id_factura.setText(rs.getString("id_f"));
                        frm_editar_venta.lbl_id_cliente.setText(rs.getString("id_c"));
                        frm_editar_venta.jbox_cliente.setSelectedItem(rs.getString("nombre"));
                        frm_editar_venta.txt_codigo.setText(rs.getString("codigo"));
                        frm_editar_venta.txt_observaciones.setText(rs.getString("observacion"));
                        int tipo_salida = rs.getInt("tipo_pago");
                        if (tipo_salida == 0) {
                            frm_editar_venta.rb_contado.setSelected(true);
                        } else {
                            frm_editar_venta.rb_credito.setSelected(true);
                        }
                    }

                    rs.close();

                } catch (SQLException ex) {
                    Logger.getLogger(frm_ver_orden.class.getName()).log(Level.SEVERE, null, ex);
                }

                String consulta = "with consulta as (\n"
                        + "	select fd.id, coalesce(fd.id_factura,0) as id_factura, p.id as id_producto, p.codigo_barras, p.descripcion, fd.cantidad, fd.subtotal, (fd.cantidad*fd.subtotal) as total, "
                        + "coalesce((select sum(e.cantidad) from entregas_productos e where e.id_factura=fd.id_cabecera and e.id_producto=p.id),0) as entrega\n"
                        + "	from productos p inner join cotizaciones_detalles fd on fd.id_producto=p.id \n"
                        + "	where fd.id_cabecera=" + id_orden + " \n"
                        + "group by fd.id, p.id, p.codigo_barras, p.descripcion, fd.cantidad, fd.subtotal \n"
                        + ")\n"
                        + "select *, (cantidad-entrega) as saldo from consulta";
                System.out.println(consulta);
                rs = DB_consultas_R_D.getTabla(consulta);

                for (int i = 0; i < frm_editar_venta.modelo.getRowCount(); i++) {
                    frm_editar_venta.modelo.removeRow(i);
                    i -= 1;
                }
                frm_editar_venta.TamanosTablaVentas();

                frm_editar_venta.modelo.setColumnIdentifiers(new Object[]{"ID", "CODIGO", "DESCRIPCIÓN", "CANTIDAD", "PRECIO", "TOTAL"});
                try {
                    while (rs.next()) {
                        double cantidad = rs.getDouble("cantidad");

                        frm_editar_venta.modelo.addRow(new Object[]{rs.getString("id_producto"), rs.getString("codigo_barras"), rs.getString("descripcion"),
                            (cantidad), metodos.formateador_dinero().format(rs.getDouble("subtotal")),
                            metodos.formateador_dinero().format(rs.getDouble("total"))});
                    }
                    rs.close();
                    frm_editar_venta.jtabla_Ventas.setModel(frm_editar_venta.modelo);
                    frm_editar_venta.TamanosTablaVentas();
                } catch (SQLException ex) {
                    Logger.getLogger(frm_ver_orden.class.getName()).log(Level.SEVERE, null, ex);
                }
                frm_editar_venta.calcular_total();
                frm_editar_venta.show(true);
            }
        }
    }//GEN-LAST:event_btn_editarActionPerformed
    public void TamanosTablaEditar() {
        columncolumnModel_Editar.getColumn(0).setPreferredWidth(40);
        columncolumnModel_Editar.getColumn(1).setPreferredWidth(600);
        columncolumnModel_Editar.getColumn(2).setPreferredWidth(80);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_cotizaciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_cotizaciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_cotizaciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_cotizaciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_cotizaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_actualizar;
    public static javax.swing.JButton btn_editar;
    public static javax.swing.JButton btn_ver;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu jpop_cliente;
    private static javax.swing.JTable jtabla_facturas;
    private javax.swing.JPanel lbl_cant_clientes;
    public static javax.swing.JLabel lbl_titulo;
    public static javax.swing.JMenuItem mn_clientes;
    private javax.swing.JTextField txt_Filtro;
    // End of variables declaration//GEN-END:variables
}
