/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Formularios_internos.jif_Crear_traslado;

import Metodos.metodos;
import conexiondb.DB_consultas_R_D;
import conexiondb.DBstock_productos;
import java.awt.Point;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelos.Contactos;

/**
 *
 * @author Monkeyelgrande
 */
public class frm_traslado_productos_entre_bodegas extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_clientes
     */
    boolean ver = false;

    public frm_traslado_productos_entre_bodegas() {
        initComponents();
        actualizar();
        jtabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(MouseEvent me) {
                if (me.getClickCount() == 2 && btn_ver.isVisible()) {
                    btn_verActionPerformed(null);
                }
            }
        });
        Contactos.mostrarContactosNombre(txt_Filtro, false);
        metodos.BuscarEnTabla(txt_Filtro, jtabla);
        metodos.EstiloTablaMaterialGlobal(jtabla);
        permisos();
    }

    /**
     * Cada acción del traslado es una opción gobernable propia
     * ('traslados_ver/crear/editar/eliminar'). Con la BD sin la migración
     * de permisos se conserva lo anterior: todos los botones visibles para
     * quien alcance a abrir la pantalla.
     */
    private void permisos() {
        if (!Metodos.Permisos.estaCargado()) {
            return;
        }
        btn_ver.setVisible(Metodos.Permisos.puede("traslados_ver"));
        btn_crear.setVisible(Metodos.Permisos.puede("traslados_crear"));
        btn_editar.setVisible(Metodos.Permisos.puede("traslados_editar"));
        btn_eliminar.setVisible(Metodos.Permisos.puede("traslados_eliminar"));
    }

    DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false; //Con esto conseguimos que la tabla no se pueda editar
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpop_cliente = new javax.swing.JPopupMenu();
        mn_clientes = new javax.swing.JMenuItem();
        textPainter1 = new org.jdesktop.swingx.painter.TextPainter();
        lbl_cant_clientes = new javax.swing.JPanel();
        txt_Filtro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btn_crear = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_ver = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        mn_clientes.setText("Actualizar");
        mn_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_clientesActionPerformed(evt);
            }
        });
        jpop_cliente.add(mn_clientes);

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Traslado Productos Entre Bodegas");

        lbl_cant_clientes.setBackground(new java.awt.Color(33, 33, 33));

        txt_Filtro.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        txt_Filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_FiltroKeyTyped(evt);
            }
        });

        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jtabla);

        javax.swing.GroupLayout lbl_cant_clientesLayout = new javax.swing.GroupLayout(lbl_cant_clientes);
        lbl_cant_clientes.setLayout(lbl_cant_clientesLayout);
        lbl_cant_clientesLayout.setHorizontalGroup(
            lbl_cant_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbl_cant_clientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lbl_cant_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(lbl_cant_clientesLayout.createSequentialGroup()
                        .addComponent(txt_Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 276, Short.MAX_VALUE)))
                .addContainerGap())
        );
        lbl_cant_clientesLayout.setVerticalGroup(
            lbl_cant_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbl_cant_clientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(33, 33, 33));

        btn_crear.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btn_crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        btn_crear.setMnemonic('n');
        btn_crear.setText("Nuevo");
        btn_crear.setBorder(null);
        btn_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearActionPerformed(evt);
            }
        });

        btn_eliminar.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btn_eliminar.setMnemonic('d');
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setBorder(null);
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_editar.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        btn_editar.setMnemonic('e');
        btn_editar.setText("Editar");
        btn_editar.setBorder(null);
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_actualizar.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        btn_actualizar.setText("Actualizar");
        btn_actualizar.setBorder(null);
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        btn_ver.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btn_ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ver.png"))); // NOI18N
        btn_ver.setMnemonic('e');
        btn_ver.setText("Ver");
        btn_ver.setBorder(null);
        btn_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_crear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_crear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_actualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(102, 0, 51));
        jPanel4.setPreferredSize(new java.awt.Dimension(146, 80));

        lbl_titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setText("Traslado Productos Entre Bodegas");

        jButton1.setBackground(new java.awt.Color(102, 0, 0));
        jButton1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setMnemonic('w');
        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbl_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 465, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(lbl_titulo))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1019, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_cant_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_cant_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 286, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearActionPerformed
        jif_Crear_traslado jd = new jif_Crear_traslado();
        jd.show();
    }//GEN-LAST:event_btn_crearActionPerformed


    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        int fila = jtabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un registro");
        } else {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null,
                    "¿Desea eliminar este traslado?\n\n"
                    + "Se revertirá el movimiento de stock entre las bodegas.",
                    "Alerta", dialogButton);

            if (dialogResult == JOptionPane.YES_OPTION) {
                try {
                    DefaultTableModel modelo = (DefaultTableModel) jtabla.getModel();
                    String id = jtabla.getValueAt(fila, 0).toString();
                    int idTraslado = Integer.parseInt(id);

                    // ════════════════════════════════════════════════════════════
                    // INTEGRACIÓN STOCK: Reversar traslado antes de eliminar
                    // ════════════════════════════════════════════════════════════
                    reversarTrasladoEliminado(idTraslado);

                    // Eliminar de la base de datos
                    DB_consultas_R_D.eliminar("traslados_productos", id);

                    // Quitar de la tabla visual
                    for (int i = 0; i < modelo.getRowCount(); i++) {
                        if (modelo.getValueAt(i, 0).toString().equals(id)) {
                            modelo.removeRow(i);
                            break;
                        }
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

// ════════════════════════════════════════════════════════════════════════════
// MÉTODO AUXILIAR: Reversar traslado eliminado
// ════════════════════════════════════════════════════════════════════════════
    private void reversarTrasladoEliminado(int idTraslado) {
        DBstock_productos dbStock = new DBstock_productos();

        String sql = "SELECT id_producto, id_bodega_origen, id_bodega_destino, cantidad "
                + "FROM traslados_productos WHERE id = " + idTraslado;

        ResultSet rs = DB_consultas_R_D.getTabla(sql);
        try {
            if (rs.next()) {
                int idProducto = rs.getInt("id_producto");
                int idBodegaOrigen = rs.getInt("id_bodega_origen");
                int idBodegaDestino = rs.getInt("id_bodega_destino");
                double cantidad = rs.getDouble("cantidad");

                String obsAnulacion = "Anulación traslado #" + idTraslado;

                // Anular salida (devolver a origen)
                dbStock.anularTrasladoSalida(
                        idProducto,
                        idBodegaOrigen,
                        frm_main.id_user,
                        cantidad,
                        idTraslado,
                        obsAnulacion
                );

                // Anular entrada (quitar de destino)
                dbStock.anularTrasladoEntrada(
                        idProducto,
                        idBodegaDestino,
                        frm_main.id_user,
                        cantidad,
                        idTraslado,
                        obsAnulacion
                );
            }
            rs.close();
        } catch (SQLException e) {
            System.out.println("Error reversando traslado eliminado: " + e);
        }
    }
    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        jif_Crear_traslado frm = new jif_Crear_traslado();
        int fila = jtabla.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un registro");
        } else {
            String id = jtabla.getValueAt(fila, 0).toString();
            String consulta = "SELECT \n"
                    + "    t.id,\n"
                    + "    p.codigo_barras AS codigo_barras,\n"
                    + "    p.descripcion,\n"
                    + "    p.id as id_producto,\n"
                    + "    bo.nombre AS origen,\n"
                    + "    bo.id AS id_origen,\n"
                    + "    bd.nombre AS destino,\n"
                    + "    bd.id AS id_destino,\n"
                    + "    t.cantidad,\n"
                    + "    t.observacion,\n"
                    + "    t.fecha\n"
                    + "FROM traslados_productos t\n"
                    + "INNER JOIN bodegas bo \n"
                    + "    ON t.id_bodega_origen = bo.id\n"
                    + "INNER JOIN bodegas bd \n"
                    + "    ON t.id_bodega_destino = bd.id\n"
                    + "INNER JOIN productos p \n"
                    + "    ON t.id_producto = p.id\n "
                    + "WHERE t.id=" + id + " \n"
                    + "ORDER BY t.fecha DESC;";
            System.out.println(consulta);
            ResultSet rs = DB_consultas_R_D.getTabla(consulta);
            try {
                while (rs.next()) {
                    
                    jif_Crear_traslado.lbl_id_traslado.setText(id);
                    jif_Crear_traslado.id_producto = rs.getInt("id_producto");
                    jif_Crear_traslado.id_bodega_origen = rs.getInt("id_origen");
                    jif_Crear_traslado.id_bodega_destino = rs.getInt("id_destino");

                    jif_Crear_traslado.jbox_bodega_origen.setSelectedItem(rs.getString("origen"));
                    jif_Crear_traslado.jbox_bodega_destino.setSelectedItem(rs.getString("destino"));
                    jif_Crear_traslado.txt_producto.setText(rs.getString("descripcion"));
                    jif_Crear_traslado.txt_observacion.setText(rs.getString("observacion"));
                    jif_Crear_traslado.txt_cantidad.setText("" + rs.getDouble("cantidad"));
                    jif_Crear_traslado.jdate_fecha.setDate(rs.getDate("fecha"));

                }
                rs.close();

            } catch (SQLException ex) {
                Logger.getLogger(frm_traslado_productos_entre_bodegas.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (ver) {
                jif_Crear_traslado.jbox_bodega_origen.setEnabled(false);
                jif_Crear_traslado.jbox_bodega_destino.setEnabled(false);
                jif_Crear_traslado.txt_producto.setEnabled(false);
                jif_Crear_traslado.txt_observacion.setEnabled(false);
                jif_Crear_traslado.txt_cantidad.setEnabled(false);
                jif_Crear_traslado.jdate_fecha.setEnabled(false);
                jif_Crear_traslado.btn_guardar.setEnabled(false);
            }
            ver = false;
            frm.show();

        }

    }//GEN-LAST:event_btn_editarActionPerformed

    private void txt_FiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_FiltroKeyTyped

    }//GEN-LAST:event_txt_FiltroKeyTyped

    private void mn_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_clientesActionPerformed
        actualizar();
    }//GEN-LAST:event_mn_clientesActionPerformed
    public void actualizar() {
        modelo.setRowCount(0);

        String consulta = "SELECT \n"
                + "    t.id,\n"
                + "    p.codigo_barras AS codigo_barras,\n"
                + "    p.descripcion,\n"
                + "    bo.nombre AS origen,\n"
                + "    bd.nombre AS destino,\n"
                + "    t.cantidad,\n"
                + "    t.fecha\n"
                + "FROM traslados_productos t\n"
                + "INNER JOIN bodegas bo \n"
                + "    ON t.id_bodega_origen = bo.id\n"
                + "INNER JOIN bodegas bd \n"
                + "    ON t.id_bodega_destino = bd.id\n"
                + "INNER JOIN productos p \n"
                + "    ON t.id_producto = p.id\n"
                + "ORDER BY t.fecha DESC;";

        ResultSet rs = DB_consultas_R_D.getTabla(consulta);
        modelo.setColumnIdentifiers(new Object[]{
            "ID", "Código Barras", "Descripción", "Origen", "Destino", "Cantidad", "Fecha"
        });
        try {
            while (rs.next()) {
                // Agrega cada fila con los alias/columnas de la consulta
                modelo.addRow(new Object[]{
                    rs.getInt("id"), // t.id
                    rs.getString("codigo_barras"), // p.codigo_barras AS codigo_barras
                    rs.getString("descripcion"), // p.descripcion
                    rs.getString("origen"), // bo.nombre AS origen
                    rs.getString("destino"), // bd.nombre AS destino
                    rs.getInt("cantidad"), // t.cantidad
                    rs.getString("fecha") // t.fecha (puedes formatear si lo prefieres)
                });
            }
            rs.close();
            jtabla.setModel(modelo);
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        actualizar();


    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verActionPerformed
        ver = true;
        btn_editarActionPerformed(evt);

    }//GEN-LAST:event_btn_verActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_traslado_productos_entre_bodegas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_traslado_productos_entre_bodegas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_traslado_productos_entre_bodegas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_traslado_productos_entre_bodegas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_traslado_productos_entre_bodegas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_crear;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_ver;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu jpop_cliente;
    private javax.swing.JTable jtabla;
    private javax.swing.JPanel lbl_cant_clientes;
    private javax.swing.JLabel lbl_titulo;
    public static javax.swing.JMenuItem mn_clientes;
    private org.jdesktop.swingx.painter.TextPainter textPainter1;
    private javax.swing.JTextField txt_Filtro;
    // End of variables declaration//GEN-END:variables
}
