/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Metodos.CellRendererFacturas;
import Metodos.TextPrompt;
import Metodos.metodos;
import com.ezware.oxbow.swingbits.table.filter.TableRowFilterSupport;
import conexiondb.ConsultasSQL;
import conexiondb.DB_consultas_R_D;
import conexiondb.DBfacturas_cabeceras;
import conexiondb.DBstock_productos;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;
import modelos.Contactos;
import modelos.Facturas_cabeceras;
import modelos.Productos;

/**
 *
 * @author Monkeyelgrande
 */
public class frm_facturas_anuladas extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_clientes
     */
    frm_ver_orden frm = new frm_ver_orden();
    frm_editar_orden frm_editar_orden = new frm_editar_orden();
    static TableColumnModel columnModel = null;
    static TableColumnModel columncolumnModel_Editar = null;
    CellRendererFacturas myRenderer = new CellRendererFacturas();

    static DefaultTableModel modelo_facturas = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false; //Con esto conseguimos que la tabla no se pueda editar
        }
    };

    public frm_facturas_anuladas() {
        initComponents();
        actualizar("pendientes");
        columnModel = jtabla_facturas.getColumnModel();
        columncolumnModel_Editar = frm_editar_orden.jtabla_Ventas.getColumnModel();
        TamanosTablaAbonos();
        jtabla_facturas.setDefaultRenderer(Object.class, myRenderer);

        lbl_titulo.setText("Ordenes");

        jtabla_facturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(MouseEvent me) {
                if (me.getClickCount() == 2) {
                    btn_verActionPerformed(null);
                }
            }
        });
        jtabla_facturas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(KeyEvent me) {
                char num = me.getKeyChar();
                if (num == KeyEvent.VK_ENTER) {
                    btn_verActionPerformed(null);

                }
            }
        });
        metodos.BuscarEnTabla(txt_Filtro, jtabla_facturas);
        TextPrompt orden = new TextPrompt("Buscar", txt_Filtro);
        permisos();
    }

    public void permisos() {
        if (frm_main.perfil == 2) {
            btn_restablecer.setEnabled(false);
        }
    }

    public static void TamanosTablaAbonos() {
        columnModel.getColumn(0).setPreferredWidth(10);
        columnModel.getColumn(1).setPreferredWidth(10);
        columnModel.getColumn(2).setPreferredWidth(400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpop_cliente = new javax.swing.JPopupMenu();
        mn_clientes = new javax.swing.JMenuItem();
        lbl_cant_clientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla_facturas = new javax.swing.JTable();
        txt_Filtro = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btn_actualizar = new javax.swing.JButton();
        btn_ver = new javax.swing.JButton();
        btn_restablecer = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        mn_clientes.setText("Actualizar");
        mn_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_clientesActionPerformed(evt);
            }
        });
        jpop_cliente.add(mn_clientes);

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        lbl_cant_clientes.setBackground(new java.awt.Color(52, 73, 94));

        jtabla_facturas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtabla_facturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtabla_facturas.setRowHeight(35);
        jtabla_facturas.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jtabla_facturas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jtabla_facturas);

        txt_Filtro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_Filtro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_FiltroFocusGained(evt);
            }
        });
        txt_Filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_FiltroKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout lbl_cant_clientesLayout = new javax.swing.GroupLayout(lbl_cant_clientes);
        lbl_cant_clientes.setLayout(lbl_cant_clientesLayout);
        lbl_cant_clientesLayout.setHorizontalGroup(
            lbl_cant_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbl_cant_clientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lbl_cant_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
                    .addGroup(lbl_cant_clientesLayout.createSequentialGroup()
                        .addComponent(txt_Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        lbl_cant_clientesLayout.setVerticalGroup(
            lbl_cant_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbl_cant_clientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(33, 33, 33));

        btn_actualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        btn_actualizar.setText("Actualizar");
        btn_actualizar.setBorder(null);
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        btn_ver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ver.png"))); // NOI18N
        btn_ver.setMnemonic('e');
        btn_ver.setText("Ver");
        btn_ver.setBorder(null);
        btn_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verActionPerformed(evt);
            }
        });

        btn_restablecer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_restablecer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/database_grande.png"))); // NOI18N
        btn_restablecer.setMnemonic('d');
        btn_restablecer.setText("Restablecer");
        btn_restablecer.setBorder(null);
        btn_restablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restablecerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_restablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ver, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_restablecer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_actualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(146, 80));

        lbl_titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setText("Ordenes anuladas");

        jButton2.setBackground(new java.awt.Color(102, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setMnemonic('w');
        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_titulo)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1081, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_cant_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_cant_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mn_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_clientesActionPerformed
        actualizar("");
    }//GEN-LAST:event_mn_clientesActionPerformed
    public static void actualizar(String tipo) {
        try {
            for (int i = 0; i < jtabla_facturas.getRowCount(); i++) {
                modelo_facturas.removeRow(i);
                i -= 1;
            }
        } catch (Exception m) {
        }
        String consulta = "with pendientes as (\n"
                + "	with fac_detalle as (\n"
                + "		select fd.id_cabecera, sum(cantidad) as cantidad\n"
                + "		from facturas_detalles fd\n"
                + "		group by fd.id_cabecera\n"
                + "		order by fd.id_cabecera\n"
                + "	),\n"
                + "	entregas as (\n"
                + "		select e.id_factura, coalesce(sum(e.cantidad),0) as cantidad\n"
                + "		from entregas_productos e\n"
                + "		group by  e.id_factura\n"
                + "		order by e.id_factura\n"
                + "	)\n"
                + "	select fd.id_cabecera, coalesce((fd.cantidad-coalesce(sum(e.cantidad),0)),0) as pendiente \n"
                + "	from fac_detalle fd left join entregas e on fd.id_cabecera=e.id_factura\n"
                + "	group by fd.id_cabecera,fd.cantidad,e.cantidad\n"
                + "	order by fd.id_cabecera\n"
                + ")\n"
                + "\n"
                + "select fc.id, fc.codigo, c.nombre as cliente, fc.fecha, fc.tipo_factura, p.pendiente\n"
                + "from facturas_cabeceras fc left join pendientes p on fc.id=p.id_cabecera, contactos c\n"
                + "where fc.anulado=0 and fc.id_contacto=c.id;";

        ResultSet rs = DB_consultas_R_D.getTabla(consulta);

        modelo_facturas.setColumnIdentifiers(new Object[]{"id", "# Factura", "Nombre cliente", "Fecha", "Tipo orden", "Estado"});
        try {
            while (rs.next()) {
                // añade los resultado a al modelo de tabla
                String estado = "";
                if (rs.getDouble("pendiente") > 0) {
                    estado = "Pendiente";
                } else {
                    estado = "Entregado";
                }
                modelo_facturas.addRow(new Object[]{rs.getString("id"), rs.getString("codigo"), rs.getString("cliente"), rs.getString("fecha"), rs.getString("tipo_factura"), estado});
            }
            rs.close();
            // asigna el modelo a la tabla
            jtabla_facturas.setModel(modelo_facturas);
            TamanosTablaAbonos();
        } catch (Exception e) {
            System.out.println("Error consutando frm_facturas: " + e);
        }
    }

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        actualizar("pendientes");
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verActionPerformed
        Facturas_cabeceras f = new Facturas_cabeceras();
        f.cargar_facturas(jtabla_facturas, "");

    }//GEN-LAST:event_btn_verActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_restablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restablecerActionPerformed
        if (DB_consultas_R_D.validar_admin()) {
            int fila = jtabla_facturas.getSelectedRow();
            if (fila == -1) {
                JOptionPane.showMessageDialog(null, "Seleccione un registro");
            } else {
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog(null, "¿Desea restaurar esta orden?\n"
                        + "TAMBIEN SE RESTAURARAN LAS SALIDAS DE LOS PRODUCTOS ASOCIADAS A ESTA ORDEN", "Alerta", dialogButton, 2);
                if (dialogResult == JOptionPane.YES_OPTION) {
                    try {
                        DefaultTableModel modelo = (DefaultTableModel) jtabla_facturas.getModel();
                        String id = (String) jtabla_facturas.getValueAt(fila, 0);
                        int idOrden = Integer.parseInt(id);

                        // ════════════════════════════════════════════════════════════
                        // INTEGRACIÓN STOCK: Re-aplicar stock al restablecer
                        // ════════════════════════════════════════════════════════════
                        reaplicarStockOrdenRestablecida(idOrden);

                        // Marcar como activo (no anulado)
                        DBfacturas_cabeceras.ActualizaAnulado(id, 1);

                        // Quitar de la tabla de anuladas
                        for (int i = 0; i < modelo.getRowCount(); i++) {
                            if (modelo.getValueAt(i, 0).equals(id)) {
                                modelo.removeRow(i);
                                break;
                            }
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        }
    }//GEN-LAST:event_btn_restablecerActionPerformed
    private void reaplicarStockOrdenRestablecida(int idOrden) {
        DBstock_productos dbStock = new DBstock_productos();

        // Obtener bodega y tipo de la orden
        int idBodega = 1;
        String tipoOrden = "Salida";
        String sqlCabecera = "SELECT id_bodega, tipo_factura FROM facturas_cabeceras WHERE id = " + idOrden;
        ResultSet rsCabecera = DB_consultas_R_D.getTabla(sqlCabecera);
        try {
            if (rsCabecera.next()) {
                idBodega = rsCabecera.getInt("id_bodega");
                tipoOrden = rsCabecera.getString("tipo_factura");
            }
            rsCabecera.close();
        } catch (SQLException e) {
            System.out.println("Error obteniendo cabecera: " + e);
        }

        // Obtener detalles y re-aplicar cada producto
        String sql = "SELECT id_producto, cantidad, id_factura FROM facturas_detalles WHERE id_cabecera = " + idOrden;
        ResultSet rs = DB_consultas_R_D.getTabla(sql);
        try {
            while (rs.next()) {
                int idProducto = rs.getInt("id_producto");
                double cantidad = rs.getDouble("cantidad");
                int idFacturaRef = rs.getInt("id_factura");

                if (idFacturaRef == 0) {
                    // Orden normal: compromete pendientes
                    dbStock.orden(
                            idProducto,
                            idBodega,
                            frm_main.id_user,
                            cantidad,
                            idOrden,
                            "Restablecimiento orden - " + tipoOrden
                    );
                } else {
                    // Orden referenciada: suma cantidad Y compromete pendientes
                    dbStock.ordenReferenciada(
                            idProducto,
                            idBodega,
                            frm_main.id_user,
                            cantidad,
                            idOrden,
                            "Restablecimiento orden ref. - Factura WO: " + idFacturaRef
                    );
                }
            }
            rs.close();
        } catch (SQLException e) {
            System.out.println("Error reaplicando stock orden restablecida: " + e);
        }
    }
    private void txt_FiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_FiltroKeyTyped

    }//GEN-LAST:event_txt_FiltroKeyTyped

    private void txt_FiltroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_FiltroFocusGained
    }//GEN-LAST:event_txt_FiltroFocusGained
    public void TamanosTablaEditar() {
        columncolumnModel_Editar.getColumn(0).setPreferredWidth(40);
        columncolumnModel_Editar.getColumn(1).setPreferredWidth(600);
        columncolumnModel_Editar.getColumn(2).setPreferredWidth(80);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_facturas_anuladas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_facturas_anuladas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_facturas_anuladas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_facturas_anuladas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_facturas_anuladas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_restablecer;
    private javax.swing.JButton btn_ver;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu jpop_cliente;
    private static javax.swing.JTable jtabla_facturas;
    private javax.swing.JPanel lbl_cant_clientes;
    public static javax.swing.JLabel lbl_titulo;
    public static javax.swing.JMenuItem mn_clientes;
    private javax.swing.JTextField txt_Filtro;
    // End of variables declaration//GEN-END:variables
}
