/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Metodos.ExportarExcel;
import Metodos.TextPrompt;
import ReportesCodigo.*;
import Metodos.metodos;
import conexiondb.DB_Stock;
import conexiondb.DB_consultas_R_D;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;


/**
 *
 * @author Monkeyelgrande
 */
public class frm_consulta_old extends javax.swing.JDialog {

    /**
     * Creates new form jd_Ventas_diarias
     */
    static DefaultTableModel modeloBalance = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false; //Con esto conseguimos que la tabla no se pueda editar
        }
    };

    DecimalFormat formatea = new DecimalFormat("###,###.##");
    static TableColumnModel columnModel = null;

    public frm_consulta_old(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        consulta();
        this.setLocationRelativeTo(parent);
        columnModel = jtabla.getColumnModel();
        TamanosTablaConsulta();
        metodos.addEscapeListenerWindowDialog(this);
        Metodos.metodos.TablaAptaParaBusquedaAndSSM(jtabla);
        TextPrompt codigo = new TextPrompt("Busqueda", txt_Filtro_codigo);
        txt_Filtro_codigo.requestFocus();
        metodos.BuscarEnTabla(txt_Filtro_codigo, jtabla);
        metodos.EstiloTablaMaterialGlobal(jtabla);
        jtabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(MouseEvent me) {
                if (me.getClickCount() == 2) {
                    int fila = jtabla.getSelectedRow();
                    String id = jtabla.getValueAt(fila, 0).toString();

                    jd_Ver_Balance_Producto frm = new jd_Ver_Balance_Producto(null, true, "(select id from productos where codigo_barras='" + id + "')",
                            "(select coalesce(max(fecha_entrega),current_date) from entregas_productos_cabecera)");

                    frm.lbl_descripcion.setText(jtabla.getValueAt(fila, 1).toString());
                    frm.lbl_codigo.setText(jtabla.getValueAt(fila, 0).toString());
                    frm.lbl_total_bodegas.setText(jtabla.getValueAt(fila, 3).toString());
                    frm.lbl_pendientes_entrega.setVisible(false);
                    frm.lbl_total_disponibles.setVisible(false);
                    frm.jlabel1.setVisible(false);
                    frm.jlabel3.setVisible(false);
                    frm.show();

                }
            }
        }
        );

    }

    public void LimpiarModelos() {
        try {
            for (int i = 0; i < jtabla.getRowCount(); i++) {
                modeloBalance.removeRow(i);
                i -= 1;
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpop_1 = new javax.swing.JPopupMenu();
        jmenu_VerFactura1 = new javax.swing.JMenuItem();
        jpop_2 = new javax.swing.JPopupMenu();
        jmenu_2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new org.jdesktop.swingx.JXTable();
        txt_Filtro_codigo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jmenu_VerFactura1.setText("Ver factura");
        jpop_1.add(jmenu_VerFactura1);

        jmenu_2.setText("jMenuItem1");
        jpop_2.add(jmenu_2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta existencia de productos");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(34, 49, 63));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulta existencia de productos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jtabla.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(jtabla);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1216, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );

        txt_Filtro_codigo.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        txt_Filtro_codigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_Filtro_codigoFocusGained(evt);
            }
        });
        txt_Filtro_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_Filtro_codigoKeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Exportar a excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_Filtro_codigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Filtro_codigo)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Filtro_codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Filtro_codigoKeyTyped

    }//GEN-LAST:event_txt_Filtro_codigoKeyTyped

    private void txt_Filtro_codigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Filtro_codigoFocusGained
    }//GEN-LAST:event_txt_Filtro_codigoFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ExportarExcel obj;

        try {
            obj = new ExportarExcel();
            obj.exportarExcel(jtabla);
        } catch (IOException ex) {
            System.out.println("" + ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void consulta() {
        DB_Stock stock = new DB_Stock();
        stock.CargarStock();
        try {
            for (int i = 0; i < modeloBalance.getRowCount(); i++) {
                modeloBalance.removeRow(i);
                i -= 1;
            }
        } catch (Exception m) {
        }
        modeloBalance.setColumnIdentifiers(new Object[]{"Código", "Descripción", "Unidad", "Stock Disponible para venta", "Pendientes de entrega"});

        String consulta = "select p.codigo_barras, p.descripcion, u.nombre as unidad, coalesce(s.stock,0) as stock, pendientes_entregas "
                + "from productos p left join stock s on p.codigo_barras=s.codigo_barras, unidades_medidas u where p.id_unidad=u.id";

//        System.out.println(consulta);
        ResultSet rs = DB_consultas_R_D.getTabla(consulta);

        try {
            while (rs.next()) {

                modeloBalance.addRow(new Object[]{rs.getString("codigo_barras"), rs.getString("descripcion"),
                    rs.getString("unidad"), metodos.formateador_decimal().format(rs.getDouble("stock")), metodos.formateador_decimal().format(rs.getDouble("pendientes_entregas"))});
            }
            rs.close();
            // asigna el modelo a la tabla
            jtabla.setModel(modeloBalance);
            TamanosTablaConsulta();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void TamanosTablaConsulta() {
        columnModel.getColumn(0).setPreferredWidth(50);
        columnModel.getColumn(1).setPreferredWidth(500);
        columnModel.getColumn(2).setPreferredWidth(40);
        columnModel.getColumn(3).setPreferredWidth(120);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_consulta_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_consulta_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_consulta_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_consulta_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frm_consulta_old dialog = new frm_consulta_old(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jmenu_2;
    private javax.swing.JMenuItem jmenu_VerFactura1;
    private javax.swing.JPopupMenu jpop_1;
    private javax.swing.JPopupMenu jpop_2;
    private org.jdesktop.swingx.JXTable jtabla;
    private javax.swing.JTextField txt_Filtro_codigo;
    // End of variables declaration//GEN-END:variables
}
