/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JDBuscar;

import Formularios.frm_Crear_Orden;
import Formularios.frm_contactos;
import Formularios.frm_cotizacion;
import Formularios.frm_editar_orden;
import Formularios.frm_facturacion_ventas;
import Metodos.metodos;
import conexiondb.DB_consultas_R_D;
import java.awt.Point;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelos.Contactos;

/**
 *
 * @author Monkeyelgrande
 */
public class jd_buscar_contacto extends javax.swing.JDialog {

    /**
     * Creates new form jd_buscar_cliente
     */
    public static String formulario = "";

    public jd_buscar_contacto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        mostrar();
        this.setLocationRelativeTo(parent);
        txt_Filtro.requestFocus();
        metodos.addEscapeListenerWindowDialog(this);
        metodos.BuscarEnTabla(txt_Filtro, jtabla);
        metodos.EstiloTablaMaterialGlobal(jtabla);
        jtabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(KeyEvent me) {
                char num = me.getKeyChar();
                if (num == KeyEvent.VK_ENTER) {
                    btn_agregar.doClick();
                }
            }
        });
        jtabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(MouseEvent me) {
                JTable table = (JTable) me.getSource();
                Point p = me.getPoint();
                int row = table.rowAtPoint(p);
                if (me.getClickCount() == 2) {
                    btn_agregarActionPerformed(null);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        txt_Filtro = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setResizable(false);

        jtabla.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtabla.setRowHeight(30);
        jtabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jtabla);

        txt_Filtro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_FiltroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_FiltroKeyTyped(evt);
            }
        });

        btn_agregar.setText("Agregar cliente");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1034, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_agregar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_agregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_FiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_FiltroKeyTyped
//        txt_Filtro.addKeyListener(new KeyAdapter() {
//            public void keyReleased(final KeyEvent e) {
//                String cadena = (txt_Filtro.getText());
//                //                txt_Filtro.setText(cadena);
//                repaint();
//                filtro();
//            }
//        });
//        trsFiltro = new TableRowSorter(jtabla.getModel());
//        jtabla.setRowSorter(trsFiltro);
    }//GEN-LAST:event_txt_FiltroKeyTyped

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        int fila = jtabla.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un registro");
        } else {
            String id = (String) jtabla.getValueAt(fila, 0);
            ResultSet rs = DB_consultas_R_D.getTabla("select * from contactos where id =" + id);
            try {
                while (rs.next()) {

                    if (formulario.equals("venta")) {

                        frm_facturacion_ventas.lbl_id_cliente.setText(rs.getString("id"));
                        frm_facturacion_ventas.txt_cedula_cliente.setText(rs.getString("cedula"));
                        frm_facturacion_ventas.lbl_nombre_cliente.setText(rs.getString("nombre"));

                        frm_facturacion_ventas.txt_codigo_barras.requestFocus();
                    }
                    if (formulario.equals("cotizacion")) {

                        frm_cotizacion.lbl_id_cliente.setText(rs.getString("id"));
                        frm_cotizacion.txt_cedula_cliente.setText(rs.getString("cedula"));
                        frm_cotizacion.lbl_nombre_cliente.setText(rs.getString("nombre"));

                        frm_cotizacion.txt_codigo_barras.requestFocus();
                    }
                    if (formulario.equals("orden")) {

                        frm_Crear_Orden.lbl_id_cliente.setText(rs.getString("id"));
                        frm_Crear_Orden.lbl_nombre_cliente.setText(rs.getString("nombre"));
                        frm_Crear_Orden.lbl_cedula.setText(rs.getString("cedula"));

                        frm_Crear_Orden.txt_codigo_barras.requestFocus();
                    }
                    if (formulario.equals("editar_orden")) {

                        int idContacto = rs.getInt("id");
                        String display = rs.getString("nombre") + " - " + rs.getString("cedula");
                        javax.swing.JComboBox<Contactos> cb = frm_editar_orden.jbox_cliente;
                        boolean encontrado = false;
                        for (int i = 0; i < cb.getItemCount(); i++) {
                            if (cb.getItemAt(i).getId() == idContacto) {
                                cb.setSelectedIndex(i);
                                encontrado = true;
                                break;
                            }
                        }
                        if (!encontrado) {
                            javax.swing.DefaultComboBoxModel<Contactos> modeloCombo =
                                    (javax.swing.DefaultComboBoxModel<Contactos>) cb.getModel();
                            modeloCombo.addElement(new Contactos(idContacto, display));
                            cb.setSelectedIndex(cb.getItemCount() - 1);
                        }
                        frm_editar_orden.lbl_id_cliente.setText(rs.getString("id"));
                    }

                }
                rs.close();
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(frm_contactos.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void txt_FiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_FiltroKeyPressed
        int key = evt.getKeyCode();
        if ((key == KeyEvent.VK_DOWN)) {
            jtabla.requestFocus();
            jtabla.getSelectionModel().setSelectionInterval(0, 0);
        }
    }//GEN-LAST:event_txt_FiltroKeyPressed
    DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false; //Con esto conseguimos que la tabla no se pueda editar
        }
    };

    public void mostrar() {

        ResultSet rs = DB_consultas_R_D.getTabla("select id,nombre,cedula,contacto from contactos order by id");
        modelo.setColumnIdentifiers(new Object[]{"id", "Nombre", "Cedula", "Celular"});
        try {
            while (rs.next()) {
                // añade los resultado a al modelo de tabla
                modelo.addRow(new Object[]{rs.getString("id"), rs.getString("nombre"), rs.getString("cedula"), rs.getString("contacto")});
            }
            rs.close();
            // asigna el modelo a la tabla
            jtabla.setModel(modelo);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jd_buscar_contacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jd_buscar_contacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jd_buscar_contacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jd_buscar_contacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jd_buscar_contacto dialog = new jd_buscar_contacto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtabla;
    private javax.swing.JTextField txt_Filtro;
    // End of variables declaration//GEN-END:variables
}
